### ISSUE TITLE
[solved]Can you add to support .pac header files Wii party u

### ISSUE THREAD

**Issue by kavid** [IcySon55/Kuriimu#186]
solved

Can you help me to add to support .pac header files Wii party u ,mario party 10.

add extract and repack function.

this is origin files

https://mega.nz/#!c44k1AoL!kQfcN7QK7pBUKkKt_W_SuvCzD3P4_nQzDQ2aalKy-Yg

thank you

**Comment by IcySon55** [comment]
@kavid Please update your request using the template shown in the Kuriimu OP: https://gbatemp.net/threads/release-kuriimu-a-general-purpose-game-translation-toolkit-for-authors-of-fan-translations.452375/

**Comment by kavid** [comment]
ok

**Comment by IcySon55** [comment]
Hi @kavid, you can actually edit your original post with the new template. Without using the template, your issue will be ignored.

**Comment by onepiecefreak3** [comment]
Added loading in newest commit;

**Comment by onepiecefreak3** [comment]
Added nearly working Save in newest commit;
Only hash recreation is missing and the hash still is a bit mysterious.

**Comment by onepiecefreak3** [comment]
Hash recreation done;
