### ISSUE TITLE
[nevermind, stupid mistake]

### ISSUE THREAD

**Issue by mariomadproductions** [IcySon55/Kuriimu#197]
[nevermind, stupid mistake]

**Comment by IcySon55** [comment]
@mariomadproductions Please update your request using the template shown in the Kuriimu OP: https://gbatemp.net/threads/release-kuriimu-a-general-purpose-game-translation-toolkit-for-authors-of-fan-translations.452375/

**Comment by mariomadproductions** [comment]
Oh, I didn't expect a template to be on the thread. I'll update both issues.
