### ISSUE TITLE
Add BMG support

### ISSUE THREAD

**Issue by mariomadproductions** [IcySon55/Kuriimu#198]
Console: Game Boy Advance, GameCube, Nintendo DS(i), Wii
Format extension(s): `bmg`, none (for _2 Games in One! - Dr. Mario + Puzzle League_)
Original game name: 2 Games in One! - Dr. Mario + Puzzle League (may not be the first - [extended list](https://pastebin.com/65cyVMk0))

First 8 byte of file(s):
`bmg`, none - `4D 45 53 47 62 6D 67 31` - `MESGbmg1`

More details?:
- _WPFTextEditor_ and _TheWindWaker_Text_Editor_ have support for editing the bmg files used in _The Legend of Zelda: The Wind Waker_
- _Tinke_ has very partial support of the bmg files used in _2 Games in One! - Dr. Mario + Puzzle League_
- _Editor Arquivo BMG_, _MKDS Course Modifier_ and _Tinke_ have partial support of the ones used in _New Super Mario Bros_. and other DS/i games such as _Mario Kart DS_ and _WarioWare D.I.Y._.
- _BMGView_ has partial support for the bmg and associated files used in _Super Mario Galaxy_.
- _CTools_ and _Wiimms ISO Tools_ has (partial?) support of bmg files used in _Mario Kart Wii_ and other Wii games such as _New Super Mario Bros. Wii_
- SM64DSe has support for the SM64DS BMG(?) format
- Various documentations can be found for the various bmg formats

Sample files (if possible):
- [_2 Games in One! - Dr. Mario + Puzzle League (USA, Australia)_ - first five bmg files](https://drive.google.com/file/d/0B_yBl-184usma1pGNGNLRVBhX1U/view?usp=sharing)
- [_New Super Mario Bros. (USA)_ - 'script' folder bmg files](https://drive.google.com/open?id=0B_yBl-184usmckhETTBHSkRDaU0)
- [_Super Mario Galaxy (USA)_ - English bmg and associated files](https://drive.google.com/open?id=0B_yBl-184usmLVdMWHpZWU0yN1E)
- [_New Super Mario Bros. Wii (USA) (v1.01)_ - English bmg file](https://drive.google.com/file/d/0B_yBl-184usmay1TVGNHTkVBOXM/view?usp=sharing)
- [can upload SM64DS examples if wanted]

**Comment by IcySon55** [comment]
@mariomadproductions Please update your request using the template shown in the Kuriimu OP: https://gbatemp.net/threads/release-kuriimu-a-general-purpose-game-translation-toolkit-for-authors-of-fan-translations.452375/

**Comment by mariomadproductions** [comment]
Done.

**Comment by onepiecefreak3** [comment]
http://wiki.tockdom.com/wiki/BMG_(File_Format)
I will just leave the link to a BMG documentation here. Will look into format later on.

**Comment by onepiecefreak3** [comment]
Added Loading in newest commit.
Saving will follow.

**Comment by onepiecefreak3** [comment]
Saving added in newest commit.
Issue (finally) finished.

**Comment by mariomadproductions** [comment]
Thanks! I'll test it out. You probably want to add it to here: https://github.com/IcySon55/Kuriimu/wiki/Completed#Text

**Comment by mariomadproductions** [comment]
Not working with Super Mario Galaxy files.
