### ISSUE TITLE
Tingle's Balloon Trip of Love

### ISSUE THREAD

**Issue by joesteve1914** [IcySon55/Kuriimu#201]
**Console**: NDS
**Format extension(s)**: Archive has no extension, INF/VIW

**Original Game Name**: Ripened Tingle's Balloon Trip of Love (Irodzuki Tingle no Koi no Balloon Trip)

**First 8 bytes of files**:
Archive - varies, there is no header, it's just all the LZ77 compressed files one after another.
INF - varies, there is also no header. The pointers and lengths start right at $0x00
VIW - varies, no header. I think you get the idea 😄 

**More details**:
- The INF files contain the pointers and lengths of each file in the archive, and the VIW contains the names of the files in the archive. The archives contain various LZ77 compressed graphic files. The only relevant ones to translation are resLibAnm#, resLibBG#, and resLib3D# (with # being any number 1-11). 
- It should probably be noted that Freshly-Picked Tingle's Rosy Rupeeland (NDS) and Too Much Tingle Pack (DSi) also use these formats.

**Sample files**:
https://drive.google.com/open?id=0Bzi52yTfVXCQOGJYYkNacHVtcG8

**Comment by IcySon55** [comment]
I've done what I can in terms of early plugins but won't be able to move this any further on my own.

**Comment by IcySon55** [comment]
I've now added saving for supported VIW/INF files.

The following files are known to not be supported for both loading and saving:
resLib3D9.viw
resLibAnm2.viw

**Comment by onepiecefreak3** [comment]
This was addressed in Kuriimu2. The mentioned unsupported files are also supported as best as possible.
The plugin allows general saving. Refer to Kuriimu2 in the future if any bugs should arise.
