### ISSUE TITLE
Angelique Retour

### ISSUE THREAD

**Issue by LadyLyndis** [IcySon55/Kuriimu#202]
Console: PSP
Format extension(s): .psarc, (.arc, .bin?)
Original game name: Angelique Retour

First 8 byte of file(s):
~~psarc - [5053415200010004] - [PSAR....]~~
arc - [4D49472E30302E31] - [MIG.00.1] -> bin contains filename strings and file meta
bin - [5041410000000000] - [PAA.....]

More details?:
This is for the text plugin. The archive plugin has already been completed.

Sample files (if possible):
The .psarc and .arc files are about a gig each, so they're too large to really have a link for.
The .bin file is here: https://mega.nz/#!4CwQXTqR!7EPIiQpzRnceEAHqyQTEBYqlbzVy9aG88NZuWEavBFA

**Comment by IcySon55** [comment]
@LadyLyndis Please delete the attached file and LINK to it somewhere else.

**Comment by LadyLyndis** [comment]
Done.

**Comment by IcySon55** [comment]
The link didn't include the decryption string and is not usable. Can you fix the link?

**Comment by LadyLyndis** [comment]
I've updated the post with a link that should work now.

**Comment by IcySon55** [comment]
Support for extracting PSARC has been added in the latest commits.

**Comment by LadyLyndis** [comment]
I thought the archive extraction plugin was already completed several months ago? Or is this something different?

**Comment by IcySon55** [comment]
This is for PSARC which you also added in this issue. I've noticed that there is a plugin collision with Ange.bin (PAA) and the Mario Maker Plugin though.

**Comment by IcySon55** [comment]
The PSARC plugin is now ready to use for ZLib compressed PSARC files. LZMA is not yet implemented.

The plugin is available in the latest beta that you can download on our Discord server.

**Comment by onepiecefreak3** [comment]
the file ange.bin doesn't contain ingame text. Rather it seems to be a collection of filenames and their meta information. So most likely the accompanying file to the MIG-arc file.
Since PSARC is finished in loading and saving I cross it from the list.

**Comment by onepiecefreak3** [comment]
This plugin was originally meant for support in helping to add text support. However, all mentioned formats are a sort of archive plugin.
Since we don't help in finding text ourselves, but help in adding support for formats after it is known which files contain it, this issue will be closed, since PSArc and PAA (in combination with the MIG-arc file) are fully supported by Kuriimu2.

If further help is needed or bugs arise, please refer to Kuriimu2 and create issues there.
