### ISSUE TITLE
Shin Megami Tensei IV

### ISSUE THREAD

**Issue by Megaflan** [IcySon55/Kuriimu#204]
Console: N3DS
Format extension(s): ".bam"
Original game name: Shin Megami Tensei IV

First 8 byte of file(s):
BAM - [41 54 42 43 80 5D 1E 00] - [ATBC€]..]

More details:
Compressed CGFX file, if you remove the first 180 bytes until you have the CGFX header, the file acts like a CGFX, but you can't save the file.

Sample files (if possible):
https://mega.nz/#!tuJWlAQT!nQTQ7po7WkDxFpkPwJy9A1h9l4FHdvfEBJz8aOoCRj4 (BAM file)
https://mega.nz/#!l7BCSZJa!Dsm9ZhVXbDitCyCOmlQw7EQr8EKMIt9R7HlSDkR2H0M (CGFX file [BAM modified])

**Comment by Megaflan** [comment]
Console: N3DS
Format extension(s): ".stex"
Original game name: Shin Megami Tensei IV

First 8 byte of file(s):
STEX - [53 54 45 58 00 00 00 00] - [STEX....]

More details:
Plugin finished, but it crashes with some files
Sample files (if possible):
https://mega.nz/#!FyRTWBDT!bJ1VkWpKTm0gVtCEygnOZSNIKJLEQUHaI-pHoqPzc94

**Comment by Megaflan** [comment]
More sample files:
https://mega.nz/#!Fn513bDJ!FOMVB72KE4wDFMxR8vJ-WOj2toOqUMW2Fd6y81zg70s

**Comment by onepiecefreak3** [comment]
Added BAM Load/Save;
Issue closed;
