### ISSUE TITLE
[Karameru Plugin] Dragon Ball Heroes Ultimate Mission X

### ISSUE THREAD

**Issue by Insighter2k** [IcySon55/Kuriimu#208]
I request support for this file type.
Onepiecefreak has sample files already. Should be enough to analyze and extract / repack it's contents.

Thx.
Console: 3DS
Format extension(s): .AMB
Original game name: Dragon Ball Heroes Ultimate Mission X

First 8 byte of file(s): 23 41 4D 42 00 00 00 20
Extension - [23 41 4D 42 00 00 00 20] - [AMB]

More details?:
It is a container which contains several files.

Sample files (if possible):
http://s000.tinyupload.com/index.php?file_id=07265303521870282230

**Comment by onepiecefreak3** [comment]
Doesn't follow our template.
This issue will be ignored until the template was used properly.

**Comment by ericjwg** [comment]
i thought the py script works.

**Comment by onepiecefreak3** [comment]
Just reminding that we don't work on this before having the correct template used here.

**Comment by Insighter2k** [comment]
Console: <>
Format extension(s): <>
Original game name: Dragon Ball Heroes Ultimate Mission X

First 8 byte of file(s): 23 41 4D 42
Extension - [41 4D 42] - [AMB]

More details?:
It is a container which contains several files.

Sample files (if possible):
Onepiecefreak has sample files.

@ericjwg this script must be included to the kuriimu application environment. it is a workaround at the moment which i havent used actually. we haven't finished our current folder. if we switch to the next one, i will have to use it if kuriimu hasn't implemented it yet.

**Comment by onepiecefreak3** [comment]
Ehm, I don't understand what you mean about multilayer, but it is one of easiest and most straightforward archive ever.
Not even 15 minutes took the Load function.

**Comment by onepiecefreak3** [comment]
Added Load/Save in the newest commit.
Issue closed.

**Comment by ericjwg** [comment]
cuz there are some cases that another #amb container burring inside... somewhat like a double pointer.. thus multilayer like?

**Comment by ericjwg** [comment]
could add file extension support.
since filter out essential files(ctpk in translation case) from all those export binary is necessary.
