### ISSUE TITLE
Rhythm Heaven Megamix [ENG] Spaceball Graphics Error

### ISSUE THREAD

**Issue by T0paz** [IcySon55/Kuriimu#212]
Console: Nintendo 3DS
Format extension: *.ctpk
Original game name: Rhythm Heaven Megamix [English Ver.]
File Location: APP:\romfs\agbBatter_long.zlib\arc\batter_XX.ctpk
First 8 byte of file (batter_00.ctpk): 43 54 50 4B 01 00 01 00
.ctpk - [150070] - [Unknown, presumably same]
More details:
The minigame, Spaceball, uses an image file of different scales saved in one .ctpk, to allow for smoother scaling in-game due to the extreme camera zooms. Each size of an object's image is displayed at a given distance from the camera; when an object appears closer, it gradually fades out the smaller scale image and fades in the larger scale image. 
With this system in mind, the file presumably consists of the header, one palette for textures, and an unknown amount of sprite sheets, the largest ending at 100080. Because the largest image ends at 100080, Kukkii appears to only read the file up to that point, and the last 50000 bytes are erased from the file when saving, regardless of whether the image is replaced or not. 
Playing the game with the shorter 1.00 MB asset causes the game to only have the largest-scale image, and load other sheets from memory, where there are none, causing other game sheets or trash data to become drawn instead. However, saving the file (shortening it to 100080) and then manually re-adding the last 50000 bytes (using HxD) from the original untouched file fully restores the missing sheets, and the game plays entirely normal, and appears normal.
I've tried to get Kukkii to read the smaller files within the package by manually replacing the image data in the 1.00 MB file with all of the data after 100080 in the original file, but then the file fails to fetch the colors from the texture, which leads me to believe that the colors are presented once and used for all sheets.
What I am asking for is support for this unusual .ctpk, so that I may edit it in its entirety without losing the smaller images. Thank you for your time.

**Comment by T0paz** [comment]
Additionally, what files am I permitted to attach to help troubleshoot the issue?

**Comment by onepiecefreak3** [comment]
CTPK now supports Mipmaps and shows the right Image Encoding.
That should solve this issue.
