### ISSUE TITLE
[Kuriimu Plugin Request] Yo-kai Watch 2

### ISSUE THREAD

**Issue by DarkSynopsis** [IcySon55/Kuriimu#214]
Console: 3DS
Format extension(s): .cfg.bin
Original game name: Yo-kai Watch 2: Bony Spirits / Fleshy Souls

First 8 byte of file(s):
(ev) .cfg.bin - [0A 00 00 00 F0 00 00 00] - [........]

More details?:
Game appears to use different types of .cfg.bin, event files "ev" seem to be the above bytes and text related to menus is a different of .cfg.bin, didn't post the first 8 bytes since different in each file

Sample files (if possible):
Included 10 .cfg.bin files, 6 related to menu text and 4 related to event text.
https://mega.nz/#!EhhmABgR!lI05VjxoyfS9JB2ZfqXtdJQoImuCXzzOdjc_Ttt69Q4

**Comment by DarkSynopsis** [comment]
After looking at the files a bit more they appear to be "t2b" files? after some Google someone had looked into the format with Ni No Kuni on PS3.

https://gbatemp.net/threads/ni-no-kuni-us-save-modification.341864/page-6#post-4545818

Don't know if its much help and might not have even needed the extra info since I see Time Travelers is also using .cfg.bin so maybe the format is similar?

**Comment by IcySon55** [comment]
@DarkSynopsis Please delete the attached file and LINK to it somewhere else.

**Comment by DarkSynopsis** [comment]
Done.

**Comment by onepiecefreak3** [comment]
The files indeed are t2b. Seems like cfg.bin is a generic extension in Level5 games containing various formats for string storage in this way.
The gbatemp link is rly helpful to write a plugin, thx. I will do that today.

**Comment by onepiecefreak3** [comment]
So Load should be possible for these t2b cfg.bin's.
Save will follow someday.

**Comment by DarkSynopsis** [comment]
Awesome, look forward to save.

**Comment by onepiecefreak3** [comment]
Save committed.
Therefore I would close the issue.
