### ISSUE TITLE
[Kukkii] Yo-kai Watch 2 .xi Graphical Error

### ISSUE THREAD

**Issue by DarkSynopsis** [IcySon55/Kuriimu#220]
Console: 3DS
Format extension(s): .xi
Original game name: Yo-kai Watch 2: Bony Spirits / Fleshy Souls

First 8 byte of file(s):
.xi - [49 4D 47 43 30 30 00 00] - [IMGC00..]

More details?:
Now with ARC0 Save Support added I decided to take a look into the game some more, some .xi files open fine and others are just a mess when opened.

Sample files (if possible):
Included 18 .xi files that are broke, let me know if some of the working ones are needed.
[YW2BrokenXIs.zip](https://github.com/IcySon55/Kuriimu/files/1203657/YW2BrokenXIs.zip)

**Comment by onepiecefreak3** [comment]
Fixed by switching 2 image formats in the plugin;
Issue closed.
