### ISSUE TITLE
[Karameru Plugin Request] Retro City Rampage

### ISSUE THREAD

**Issue by djmatheusito** [IcySon55/Kuriimu#221]
Console: 3DS
Format extension(s): bfp
Original game name: Retro City Rampage: DX

First 8 byte of file(s):
.bfp - [52 54 46 50 71 00 00 00] - [RTFPq]

More details?:
The pointer table start at 0x20 and consists 3 entries: unkown 4 bytes| Adress of file | size of decompressed file.
The files are Zlib compressed with a 0x789C header.

Sample:
https://mega.nz/#!14IUGKBb!qOM21H5RpjMzWIiIprIrFhLzL2SmBRL0AwajVjrupBo

**Comment by IcySon55** [comment]
You're not supposed to keep all of the <>.

**Comment by onepiecefreak3** [comment]
BFP Load/Save added.
