### ISSUE TITLE
[Kuriimu Plugin Request] Professor Layton vs Ace Attorney

### ISSUE THREAD

**Issue by ghostfeesh** [IcySon55/Kuriimu#222]
Console: 3DS
Format extension(s): .xs
Original game name: Professor Layton vs Ace Attorney

First 8 byte of file(s):
Extension - A2 20 63 36 01 37 38 FF - ¢ c6.78ÿL

More details?:
Opening up the vs1.fa file in Karameru (using the recently added XFSA plugin) rendered most if not all of the files encrypted.

Sample files (if possible):
XS file: https://my.mixtape.moe/olcsgu.7z
vs1.fa file: https://drive.google.com/file/d/0B_S0wgZdscAiMFBvQ0lHSjNpdlU/view?usp=sharing

**Comment by onepiecefreak3** [comment]
The error was a wrong offset map in XFSA. This was fixed in my newest commit.
The format xs (XSCR) will be supported later on (I'm working on it right now).
Issue closed.
