### ISSUE TITLE
[Kukkii Request] jtex files save error

### ISSUE THREAD

**Issue by FlameBeam** [IcySon55/Kuriimu#223]
Here is a jtex file in _The Legend of Zelda: Twilight Princess_. 

[CommonL_Switch_aen.zip](https://github.com/IcySon55/Kuriimu/files/1205110/CommonL_Switch_aen.zip)

When I Export a png then Import it, the jtex will be wrong.

**Comment by FlameBeam** [comment]
emmm....it's the Picross Game on 3DS.

**Comment by onepiecefreak3** [comment]
Revised Raw/JTEX. The provided RawJTEX now loads correctly and is savable.
Therefore this issue is solved.

**Comment by IcySon55** [comment]
@FlameBeam This fix has been released in a patch for 1.0.6. Check the v1.0.6 release page.

**Comment by FlameBeam** [comment]
Many thanks!

**Comment by FlameBeam** [comment]
@IcySon55 Still something wrong.The jtex I uploaded is edited and it can be open correct. But Kukkii can't open the original jtex. 

[HowToMenuL_Switch_aen.zip](https://github.com/IcySon55/Kuriimu/files/1206547/HowToMenuL_Switch_aen.zip)
