### ISSUE TITLE
[Bug] Ie.b not work in Karameru V.1.6

### ISSUE THREAD

**Issue by blouche** [IcySon55/Kuriimu#225]
Console: 3ds
Format extension(s): .fa
Original game name: Inazuma Eleven Go (Shadow/Light), Inazuma Eleven Go ChronoStone (Thunderflash/Wildfire) and Inazuma eleven Go Galaxy (BigBang/Supernova)

First 8 byte of file(s): 
Extension - 41 52 43 30 48 - ARC0H

More details ?:
Hey hi i have a problem when i open .FA files (ARC0) everything works fine except V.1.6
Can not open files ie.b, ie.a not works in .b
Thank you for solving the problem

Sample files (if possible):
https://mega.nz/#!Jh0gVQJa!opas_UEy8T1pcIRV5hMjEJlzRVXi_7qzHAMDNfQDLiQ

**Comment by onepiecefreak3** [comment]
Problem was a wrong encoding for name hashing. Problem is fixed in the newest commit.
Issue closed.
