### ISSUE TITLE
[Kukkii] DQ8 .bch mipmap issue

### ISSUE THREAD

**Issue by DarkSynopsis** [IcySon55/Kuriimu#226]
Console: 3DS
Format extension(s): .bch
Original game name: Dragon Quest VIII: Journey of the Cursed King

First 8 byte of file(s):
.bch - [42 43 48 00 22 23 44 AD] - [BCH."#D.]

More details?:
.bch files from DQ8 don't seem to be loading mipmaps correctly, in the example files most of them have a face and body texture, the body texture should have 4 mipmaps, most of the files load the highest res mipmap then the second is a mess and then it doesn't load the other 2 mipmaps and the face texture which I believe only has 1 mipmap.

In the example files "c004_5" loads 3 of the body textures fine but is missing another mip and the face.

Also with no changes hitting Save on these files throws up an error, imagine its because they aren't loading correctly in the first place?

Sample files (if possible):
Included are 4 .bch files.
[DQ8BCH.zip](https://github.com/IcySon55/Kuriimu/files/1206192/DQ8BCH.zip)

**Comment by onepiecefreak3** [comment]
Added a mipmap routine in BCH and added right alignment of textures in the newest commit.
Issue closed.
