### ISSUE TITLE
[Plugin Request] Lady Layton Mobile .xi files

### ISSUE THREAD

**Issue by ultramario1998** [IcySon55/Kuriimu#228]
Console: Android, 3DS
Format: .xi
Game name: Layton's Mystery Journey - Katrielle and the Millionaires' Conspiracy

First 8 bytes:
`494D47413030000030 IMGA00..0`

**Comment by onepiecefreak3** [comment]
The font is load-/savable. Most other xi use KTX (Khronos Texture), which needs further information gathering and implementation of a library for that.
But for now I can close this issue because adding new formats won't be difficult at all.
