### ISSUE TITLE
[Kuriimu Plugin Request] Tingle's Balloon Trip of Love

### ISSUE THREAD

**Issue by joesteve1914** [IcySon55/Kuriimu#234]
**Console**: NDS
**Format extension(s)**: .bin
**Original game name**: Ripened Tingle's Balloon Trip of Love (Irodzuki Tingle no Koi no Balloon Trip)

**First 8 byte of file(s)**: 
lang.bin – [06 00 F3 32 00 00 00 00] – [..ó2....]

**More details**:

- The entire script is located in lang.bin.
- The source code for the current script dumper/inserter is included in the link below.

**Sample files**:
https://drive.google.com/open?id=0Bzi52yTfVXCQM1dpZ1I5LWg4YXM
(includes lang.bin, as well as the current script editor and it’s source code)

**Comment by onepiecefreak3** [comment]
The Encoding from DarkNemesis rly is good. The plugin now supports loading. I will commit the plugin after Saving was added.

**Comment by onepiecefreak3** [comment]
Commited Load/Save for lang.bin.
Issue closed.

**Comment by IcySon55** [comment]
Identify is not robust enough to call this one finished.

**Comment by onepiecefreak3** [comment]
Identification revised.
Closed again.
