### ISSUE TITLE
[Karameru Plugin Request] Super Robot Wars UX

### ISSUE THREAD

**Issue by Deathmaw** [IcySon55/Kuriimu#237]
Console: 3DS
Format extension(s): .bin
Original game name: Super Robot Wars (Taisen) UX

First 8 byte of file(s):
Even though all files are .bin the 8 bytes in each file is different

More details?:
Unsure what each .bin file contains, "arcBtlMsgDat.bin" might just be text where as "arcBtlGrpDat.bin" seems to contain darc files.

Most I've found out is http://zenhax.com/viewtopic.php?f=9&t=3630

Sample files (if possible):
https://mega.nz/#!VtoXTZ5A!Cly0FUjwH6H9jQHDXOwXS2PCUhLXH20qfIhMC-B7PMM

**Comment by Deathmaw** [comment]
Must have just tried the wrong files arcBtlMsgDat, arcCmnGrpDat, arcSysExtDat, arcTacGrpDat open in Karameru while the others don't.

I assume the .bin files that get extracted from arcBtlMsgDat would be Text? But they don't open in Kuriimu though Robot Wars in there is stated to be for "Z".

**Comment by onepiecefreak3** [comment]
Load revised and added Save.
Issue closed.
