### ISSUE TITLE
GK2 graphics/archives

### ISSUE THREAD

**Issue by onepiecefreak3** [IcySon55/Kuriimu#246]
Console: DS
Format extension(s): various
Original game name: Gyakuten Kenji 2

Just a fun project for me. No more details needed.

**Comment by henke37** [comment]
The graphics formats are stock Twilight SDK and shared with many other games. Pokemon, Zelda, Mario, it's what Nintendo use themselves.

**Comment by onepiecefreak3** [comment]
Status:
GK2 Archive 1 Load
NRCG/NCLR/NSCR Load

**Comment by onepiecefreak3** [comment]
Both archives load- and savable.
Graphics will be delayed to do some other stuff.

**Comment by onepiecefreak3** [comment]
Partially solved in Kuriimu2 by supporting some of the framework formats. This will not be pursued further. Issue closed.
