### ISSUE TITLE
[Kukkii Plugin Request] Puyo Puyo Tetris mz_name

### ISSUE THREAD

**Issue by DarkSynopsis** [IcySon55/Kuriimu#247]
Console: 3DS
Format extension(s): .comp
Original game name: Puyo Puyo Tetris

First 8 byte of file(s):
COMP - [00 20 00 00 04 02 00 01] - [. ......]

More details?:
I believe COMP is just a generic compression Puyo games use, I have attached the decompressed files, they contain character names "000" should be "りんご" I believe the file is an image which is why I've put this down as Kukkii.

Sample files (if possible):
https://mega.nz/#!Z5RxWSYa!dncQk255PuDFjUR_Dm290iNrRvzY2aw_ktyjGLsWvUg

**Comment by onepiecefreak3** [comment]
Added Load/Save for these images in the newest commit.
Issue closed.
