### ISSUE TITLE
[Karameru] MTARC Saving Error

### ISSUE THREAD

**Issue by Deathmaw** [IcySon55/Kuriimu#250]
Console: 3DS
Format extension(s): .arc
Original game name: Monster Hunter Stories

First 8 byte of file(s):
.arc - [41 52 43 00 11 00 56 01] - [ARC...V.]

More details?:
Replacing a file and trying to save results in an error.

Sample files (if possible):
https://mega.nz/#!49AnyTgS!TqjIBHTZxWpJjLcJzwGmMkvVdEGH23vQnhf_V3Id_wA

**Comment by onepiecefreak3** [comment]
The Load and Save code of MTArc was revised and a bug with the file entry update at sve was fixed.
Therefore this issue is solved.
