### ISSUE TITLE
Certain games looks like a glitchy mess on Rhythm Heaven Megamix

### ISSUE THREAD

**Issue by Armodillomatt12** [IcySon55/Kuriimu#255]
The dazzles looks like the static tv from the ring, tangotronic 3000 looks like it had "some fun" with missingno, and sumo bros, idek.
Spaceball is the same as always, glitchy as hell.

**Comment by onepiecefreak3** [comment]
Well, sample files would be appreciated.
Maybe also screenshots from ingame to let us see this mess.

**Comment by Armodillomatt12** [comment]
https://cdn.discordapp.com/attachments/344559559882309634/345081239658823681/image.png

**Comment by onepiecefreak3** [comment]
Ok, you rly have to put more detail into it.
Which games beside the one mentioned? Which files for example (Filename in the RomFS)?
More screenshots!

Please use the issue template from our gbatemp thread(the one for requests, works also for bugs).

**Comment by ericjwg** [comment]
sample contains two version ctpk.
old: used ctpk plugin before recent revision.
new: used new revision.

[ctpk.zip](https://github.com/IcySon55/Kuriimu/files/1222975/ctpk.zip)

new ctpk doesn't load properly in game. black screen instead.

**Comment by IcySon55** [comment]
@ericjwg Please edit your comment and delete the ctpk that you attached. We cannot accept copywritten files in our comments. Please link to the file offsite as instructed by the template not and the 'new issue' disclaimer. (I do not have the power to delete the file for you.)

**Comment by ericjwg** [comment]
ok. comment deleted

**Comment by IcySon55** [comment]
@Armodillomatt12 Please update your request using the template shown in the Kuriimu OP: https://gbatemp.net/threads/release-kuriimu-a-general-purpose-game-translation-toolkit-for-authors-of-fan-translations.452375/

@ericjwg No need to delete your comment, you could just edit out the file attachment.

**Comment by onepiecefreak3** [comment]
The hash list was aligned wrong. Was resolved in the newest commit.
Issue closed.
