### ISSUE TITLE
Level 5 .FA error

### ISSUE THREAD

**Issue by GowSupremo** [IcySon55/Kuriimu#263]
Console: 3DS
Format extension(s): .fa
Original game name:
-Inazuma Eleven 1-2-3 the legend of mark evans (3DS)

First 8 byte of file(s):
.fa - [<42 31 32 33 48 00 00>] - [<B123H>] 

More details?:
The error occur with save the .fa edited and to replace files. This error did not happen in kuriimu 1.0.5
![sin titulo](https://user-images.githubusercontent.com/17249334/29419375-46bfb7ca-836f-11e7-9602-5ebe76b71895.png)

Sample files (if possible):
https://mega.nz/#!YxF10D7D!07C0FePeG4PMKfCVZrDawc18Pyv1nit5uo3yTfpMDIg

**Comment by onepiecefreak3** [comment]
This issue is solved in Kuriimu2. Refer to Kuriimu2 for future bug reports regarding this format.
