### ISSUE TITLE
[Kukkii Plugin Request] Highschool DxD (CTX)

### ISSUE THREAD

**Issue by Deathmaw** [IcySon55/Kuriimu#267]
Console: 3DS
Format extension(s): .ctx .enc
Original game name: Highschool DxD

First 8 byte of file(s):
CTX - [43 54 58 20 31 30 20 00] - [CTX 10 .]
ENC - [0B 00 00 00 1C 00 00 00] - [........]

More details?:
CTX files appear to be images, I notice Kukkii can open "ctxb" no clue if this format is similar though, also the .enc files included seem to be CTX files as well, I believe most of the had the same first 8 bytes though "efc00.enc" is different to what is above.

Sample files (if possible):
https://mega.nz/#!o5QnjLia!Xf1vb1KcCCemj6pHIvc1xv8QWRWxlUTcAea1tW0GrR0

**Comment by onepiecefreak3** [comment]
Added Save/Load in the newest commit.
Issue solved.
