### ISSUE TITLE
Highschool DxD enc archive

### ISSUE THREAD

**Issue by Deathmaw** [IcySon55/Kuriimu#268]
Console: 3DS
Format extension(s): .enc
Original game name: Highschool DxD

First 8 byte of file(s):
ENC - [1B 03 00 00 5A 00 00 80] - [....Z...]

More details?:
I'm look for all the game's text and I believe its found in this "event.enc" file, taking a quick look in a HEX Editor it looks like it might be an archive file since it has references to .txt and .ctx files that aren't found anywhere in the romfs folder, could be a shot in the dark though.

Would love to find out where the game is hiding all its text.

Sample files (if possible):
The file has the "event.enc" file along with the "event" folder which has a few files, one being "eventFileListTbl.dat" which I thought might be useful
https://mega.nz/#!IlI03RTA!7uL9gasH45TXbrAAclLDcJL61CRqPU2s_A7dRBKRf8k

**Comment by onepiecefreak3** [comment]
Independently to this issue, but the there is a folder text with a file TextData.bin in the game. Couldn't the text be written there?

**Comment by onepiecefreak3** [comment]
Added ENC Load, but the files are compressed. It's some sort of LZ compression it seems and I'm not that good in reversing them.
So Save and de-/compress will be coming later.

**Comment by Deathmaw** [comment]
There is indeed a TextData.bin but its like 3KBs doesn't seem like it would hold the story text, maybe the main menu?

https://mega.nz/#!ZwQjGCgL!SYJSCXZpHk2F5VuaR92X_CT_0VhCW-BU6rk4Z07Ke04

is the file if needed.

**Comment by onepiecefreak3** [comment]
If you need support for text, pls create a new issue.

**Comment by Deathmaw** [comment]
Will do.

**Comment by onepiecefreak3** [comment]
Happy news! After 2 years of experiences, the compression is finally broken. Compression and decompression was added to Kuriimu2's Kompression library and can be used in other projects. When K2 gets all plugins ported from K1, this issue can finally be closed.

**Comment by onepiecefreak3** [comment]
The ENC archive was ported to K2 and this issue can officially be closed.
