### ISSUE TITLE
Touch detective 2½

### ISSUE THREAD

**Issue by henke37** [IcySon55/Kuriimu#276]
Console: Nintendo Ds
Format extension(s): .bin
Original game name: Touch detective 2½

First 8 byte of file(s):
EE 16 00 00 DD 2D 00 00 

More details:
https://app.assembla.com/spaces/sdat4as/subversion/source/HEAD/Nitro/TouchDetective/MasterArchive.as

**Comment by onepiecefreak3** [comment]
Load and Save added with newest commit.
Issue closed.
