### ISSUE TITLE
Unchained Blades EXXiV Text

### ISSUE THREAD

**Issue by Sythril360** [IcySon55/Kuriimu#278]
Console: 3DS
Format extension(s): .dat / .kbd
Type: text
Original game name: Unchained Blades EXXiV

First 8 byte of file(s):
.dat
.kdb

More details:
First 8 Bytes are different depending on the file, they all just seem to be UTF-8? would like to edit them with ease in Kuriimu.

More info can be found on the PSP side.
https://gbatemp.net/threads/currently-translating-unchained-blades-exxiv.394877/page-10#post-6605979
Believe that would be the most helpful post.

Sample files (if possible):
https://mega.nz/#!F95xhC6T!BbXWKRHfvgd0jKtiFI0zdQmoRVkBFzZtgzXTk-EqTK8

**Comment by onepiecefreak3** [comment]
KBD should be load-/savable.
As I could see in the gbatemp thread you couldn't edit the size of text to be higher than original? If that info is up-to-date then hooray, you might be able to vary the length of your texts with this plugin as you like.
But since this format is a really dynamic script type it could need your testing in changed text sizes (smaller and bigger).

**Comment by onepiecefreak3** [comment]
Next step the .dat texts which aren't as hard but quite as tricky to structure.

**Comment by Sythril360** [comment]
Thanks for the quick plugin! haven't tried to make text size higher but seems to be importing fine.

**Comment by onepiecefreak3** [comment]
Well importing does yes. But ingame it has to ackknowledge the new textsize and shouldn't crash.
Thy for trying.

**Comment by onepiecefreak3** [comment]
I rly would like to work further on this. Could you maybe try longer textSizes?

**Comment by onepiecefreak3** [comment]
Well, I will just close the issue, since the plugin threw out byte perfect files.
If there are errors pls create a new plugin.
Closed.

**Comment by Sythril360** [comment]
@onepiecefreak3 Sorry for the late reply, I just tried a few entries with longer text and seemed to work.
