### ISSUE TITLE
Add import file function in .fa extension

### ISSUE THREAD

**Issue by GowSupremo** [IcySon55/Kuriimu#280]
Console: 3ds
Format extension(s): .fa
Type: .fa archive format
Original game name: 
Inazuma Eleven Series
Yokai Watch Series
First 8 byte of file(s):
.fa - [41 52 43 30 48 00 00 00] - [ARC0H]

More details:
I need function to crate a game+update in 1 file

Sample files (if possible):
https://mega.nz/#!I0dzlRJI!-gGuzzr12AO7OZw3KHKpCnxh2_B8zf8TOyrQbXOxAOA

**Comment by onepiecefreak3** [comment]
Kuriimu2 has the ability to delete and add files from/to an ARC0 .fa file. Refer to Kuriimu2 for future feature requests regarding this file format. Issue closed.
