### ISSUE TITLE
[Karameru] Kenka Banchou 6 - Soul and Blood (ZDP)

### ISSUE THREAD

**Issue by Deathmaw** [IcySon55/Kuriimu#282]
Console: 3DS
Format extension(s): .zdp
Type: archive
Original game name: Kenka Banchou 6 - Soul and Blood

First 8 byte of file(s):
zdp - [64 61 74 61 70 61 63 6B] - [datapack]

More details:
.zdp files seem to be some form of archive, looking at the bottom of each with a HEX editor some contain .arc, .bch, .ctpk and others like .zds which can be found in the "text.zdp".

Sample files (if possible):
https://mega.nz/#!VgY2yR5a!E2HrVD33us8PMzTWHTB_ZfHfaU8015E26xYI0Xd1to8

**Comment by onepiecefreak3** [comment]
Added ZDP Load/Save with the newset commit.
Issue closed.
