### ISSUE TITLE
.TEX Graphics issues (Metalmax3)

### ISSUE THREAD

**Issue by MetalFan1988** [IcySon55/Kuriimu#284]
Console: NDS
Format extension(s): >.TEX
Type: [image]
Original game name: Metal Max 3

First 8 byte of file(s):
.TEX - [43484E4B00000000] - [CHNK]

More details:
In the Newly launched "Kurrimu 1.08" have appeared problems of compatibility with some files that opened before in version 1.07.
Also in some of them to colors are not displayed correctly. Example ICON08_03.TEX.

Sample files (if possible):
These not open now.
BT_CR.TEX
BT_GR.TEX
BT_YE.TEX

**Comment by onepiecefreak3** [comment]
Format isn't even finished yet. Bugs are therefore normal and will be handled after understanding the format enough.
