### ISSUE TITLE
[Kuriimu] Tongari Boushi to Mahō no Machi .tarc support

### ISSUE THREAD

**Issue by ImCarlosGG** [IcySon55/Kuriimu#285]
Console: 3DS
Format extension(s): .tarc
Type: text
Original game name: Tongari Boushi to Mahō no Machi
First 8 byte of file(s):
.tarc - 54 42 41 46 79 01 00 00 - TBAFy

More details:
Most of the files of this games are in .tarc format.

Sample files (if possible):

The file I used:
https://mega.nz/#!xhomxbTA!uc3oawuBKifh1zO0BOLW00HOYGDoI2qScCAEkBGp_5s

**Comment by onepiecefreak3** [comment]
Ehhh..... I can't find text. You're right this is an archive, but... I can't find text.
I will write an archive plugin, then you have to researh yourself further.

**Comment by onepiecefreak3** [comment]
I included a plugin to load and save tarc in Karameru.
Issue therefore closed.
