### ISSUE TITLE
The Snack World error on opening some .cfg.bin files

### ISSUE THREAD

**Issue by m0nm0npalam0n** [IcySon55/Kuriimu#286]
Console: 3DS
Format extension(s): .cfg.bin
Original game name: The Snack World: Trejarers

First 8 byte of file(s):
item_text_ja.cfg.bin - [4e 07 20 20 f0 4e 01 20 a2] - [N  ðN ¢ ]

More details:
Can't open some .cfg.bin files. encountering below error on Kuriimu
[http://imgur.com/a/gO3tT](http://imgur.com/a/gO3tT)

Sample files (if possible):
[https://drive.google.com/file/d/0B1kFLMgtAYMheFNTUHZsTC1RNlE/view?usp=drivesdk](https://drive.google.com/file/d/0B1kFLMgtAYMheFNTUHZsTC1RNlE/view?usp=drivesdk)

**Comment by onepiecefreak3** [comment]
Ignoring of higher typemasks is now properly fixed and handled. cfg.bin provided now opens properly and saves byte-perfect in original state.
Issue closed.
