### ISSUE TITLE
[Kuriimu] MH .lmd plurin request

### ISSUE THREAD

**Issue by GowSupremo** [IcySon55/Kuriimu#287]
Console: 3ds
Format extension(s): .lmd
Type: Text archive
Original game name: 
Monster hunter series
Monster Hunter Stories

First 8 byte of file(s):
.lmd - [6C 6D 64 00 0F 01 00 00] - [lmd]

More details:
I believe the lmd format is a slightly modified gmd file

Sample files (if possible):
EUR Demo
https://mega.nz/#!Ft0T2LRa!nk-KsUCeLu78-IVS8Ebnq6IznKUcPRPOmjgFjllxXQ0
JAP Game
https://mega.nz/#!B8cCjIbA!r5GWNvuj27VWpDZSBuqVhdtBshMTAbvAHK2I2Z8r9rE

**Comment by onepiecefreak3** [comment]
Added LMD Load/Save; in newest commit.
Issue closed.
