### ISSUE TITLE
Inazuma Eleven cfg.bin.nat

### ISSUE THREAD

**Issue by DarthManto** [IcySon55/Kuriimu#288]
Console: 3DS
Format extension(s): cfg.bin.nat
Type: text
Original game name: Inazuma Eleven Go Galaxy 

First 8 byte of file(s):
Multiple files with the same issue

More details:
I think these files hold data for things such as player names and other things like that and cannot access it using Kuriimu.

Sample files (if possible):
https://mega.nz/#F!YLo1zZZC!8nCQdtL5-6I5z__V_A09wQ

**Comment by onepiecefreak3** [comment]
You're right. These files you linked doesn't contain text at all and only seems like config data.
