### ISSUE TITLE
Professor Layton and the Miracle Mask

### ISSUE THREAD

**Issue by djmatheusito** [IcySon55/Kuriimu#289]
Console: 3DS
Format extension(s): .fa
Type: archive
Original game name: Professor Layton and the Miracle Mask

First 8 byte of file(s):
.fa - 58 46 53 41 24 00 00 00 - XFSA$

More details:
If you make use of option "save" of Karameru, it will throw a exception calling "The process cannot access the file because it is being used by another process."
https://i.imgur.com/4650RMF.jpg

If you use the option "save as...", this will generate a new .fa archive but the size is smaller than the original archive and the game doesn't work with this archive.
http://i.imgur.com/RoXbnP4.png

Sample files (if possible):
https://mega.nz/#!cp5EBaoR!T9TYT7XtY1668iQn6veBUr2TycJj5PC1qBJlzgaZ1Xk

**Comment by onepiecefreak3** [comment]
Changed input of plugins to a filestream which solved the problem in the newest commit.
Issue solved.
