### ISSUE TITLE
.62440501 support (LMD again)

### ISSUE THREAD

**Issue by GowSupremo** [IcySon55/Kuriimu#290]
Console: 3DS
Format extension(s): .62440501
Type: text
Original game name: 
Monster hunter games in specific monster hunter stories

First 8 byte of file(s):
.62440501 - [6C 6D 64 00 0F 01 00 00] - [lmd]
.ARC - [41 52 43 00 11 00 56 01] - [ARCV]

More details:
The .62440501 is in .arc i added 1 .arc of reference.
The ..62440501 is a variant from .lmd, i try rename to .lmd and the kuriimu pluging runing and found, but i when rename to .62440501 the file edited in the game and the game init 3ds loading screen and return to home menu.

Sample files (if possible):
LMD .62440501:
https://mega.nz/#!o4VDDQRR!es8JLNDtXNAO3MX7QC_q-JDYFO0E5mpbPL-aPKTBtXA
ARC of reference
https://mega.nz/#!pgdE2YSJ!wALf6kplrZITkutn0oOIzh8plmcLbd-vU4eUSTv5MdI

**Comment by onepiecefreak3** [comment]
Ok, even if that is the most confusing description, I can vaguely grab the essence behind it.

**Comment by onepiecefreak3** [comment]
It's exactly lmd just with another extension. The plugin can load it like a normal lmd and saves it byte perfect without change.
The crash seems to occur because some values have to be changed in order for edited text to be ackknowledged.
I added the new extension to the plugin and committed it.

**Comment by onepiecefreak3** [comment]
Can you give me an edited file, which seem to lead to a crash?

**Comment by GowSupremo** [comment]
Yes, but lmd or arc?

**Comment by GowSupremo** [comment]
ARC
https://mega.nz/#!ghEBQYgQ!C2F5ESwrTgKCzIpVQGP3nza_WSx4XIZlSnkxG0GPDrQ
Files edited with arc
https://mega.nz/#!shsHADoT!xV0gcl655onSZuf2A2ZvySXyU2TLzEK0euBgXn3OWzc

**Comment by onepiecefreak3** [comment]
We changed the alignment of files in the arc a bit, so it gets byte perfect with everything original.
Could you open the original archive, inject ONE edited file (which before leaded to errors), save and try it again.

**Comment by GowSupremo** [comment]
Yes, found, the game now not crash

**Comment by GowSupremo** [comment]
Now the lmd have a error; if you save edited .62440501 into the .arc and re extrack the file; the file is clean 0KB when before is a 10KB aprox

**Comment by onepiecefreak3** [comment]
The size was mapped incorrectly. In the newest commit you can add files and they will have the correct size.
The .62440501 extension also was just a hash for ".lmd" extension in MT archives. So in the future the extension .62440501 will be shown as ".lmd".
Could you retry if the game crashes after redoing the steps?

**Comment by GowSupremo** [comment]
Yes

**Comment by GowSupremo** [comment]
Found thanks.


![bot_0000](https://user-images.githubusercontent.com/17249334/29745574-dc0acb20-8abe-11e7-9168-7955613803f2.png)
![top_0000](https://user-images.githubusercontent.com/17249334/29745573-dc0a7d6e-8abe-11e7-960f-0a7c1e2b905b.png)

**Comment by onepiecefreak3** [comment]
Nice. Issue closed with that.
