### ISSUE TITLE
Kid Icarus: Uprising .zrc support

### ISSUE THREAD

**Issue by Dark124** [IcySon55/Kuriimu#292]
Console: 3DS
Format extension(s): .zrc
Type: [archive]
Original game name: Kid Icarus: Uprising

First 8 byte of .zrc):
<.zrc> - [11 A4 BE 0D 00 64 61 72N/A] - [N/A]

More details:
<I've tried to open this since it's basically darc, but it will not open. but efe can open it, anyway this archive is know to have cgfx, .snd,(csar) .arc, .json, .bin and maybe more>

Sample files (if possible):
<https://cdn.discordapp.com/attachments/216682963553878018/350569987934519298/m108.zrc>

**Comment by FlameBeam** [comment]
it's LZ11 compress.After decompress, it's darc file. U can decompress it in Karameru/Tools/3DS/LZ11. (Can also decompress/recompress with wwcxtool).

**Comment by onepiecefreak3** [comment]
Hey, don't we want to let people use our tools? ;)

**Comment by onepiecefreak3** [comment]
Also the link doesn't work anymore and it seems that it then is rly just compressed.
Thx for creating an issue. Closed.

**Comment by FlameBeam** [comment]
Of course. And I hope your tools will be better :D
