### ISSUE TITLE
Bugs with an edited .fa archive - Professor Layton And Miracle Mask

### ISSUE THREAD

**Issue by djmatheusito** [IcySon55/Kuriimu#297]
Console: 3DS
Format extension(s): .fa
Type: archive
Original game name: Professor Layton and the Miracle Mask

First 8 byte of file(s):
.fa - 58 46 53 41 24 00 00 00 - XFSA$

More details:
If you replace any file in the .fa archive and then save it and use with the game, the title screen image won't be shown and the button "new game" doesn't will work.

Sample files (if possible):
https://mega.nz/#!cp5EBaoR!T9TYT7XtY1668iQn6veBUr2TycJj5PC1qBJlzgaZ1Xk

**Comment by onepiecefreak3** [comment]
The port to Kuriimu2 and the refactoring of the plugins are thoroughly tested by now and the described bugs cannot be reproduced. This issue is therefore solved with Kuriimu2. Refer to Kuriimu2 for future bug reports regarding this file format.
