### ISSUE TITLE
Archive plugin for New Love Plus Plus

### ISSUE THREAD

**Issue by IcySon55** [IcySon55/Kuriimu#300]
Console: 3DS
Format extension(s): .bin (img.bin)
Type: archive
Original game name: New Love Plus Plus

First 8 byte of file(s):
.bin - [0A0000004F000000]

More details:
It's a huge archive with a strange structure.

Existing unpacker (no repack): https://github.com/gdkchan/NLPUnpacker/blob/master/NLPUnpacker/Program.cs
Another unpacker: https://github.com/kiwiz/nlpp-tools

**Comment by onepiecefreak3** [comment]
NLP base archive and PACK archive should be load- and savable.
I will close the issue then.
