### ISSUE TITLE
Archive plugin for Nintendo 3DS .narc files.

### ISSUE THREAD

**Issue by ElyosOfTheAbyss** [IcySon55/Kuriimu#303]
Console: Nintendo 3DS
Format extension(s): .narc
Type: archive
Original game name: multiple Nintendo 3DS games (Mario 3D Land, Mario Sports Superstars, etc.)

First 8 byte of file(s):
.narc - (4E 41 52 43 FE FF 00 00) - (NARCþÿ..)

More details:
Might be similar to the DS .NARC, just not the exact same.

Sample files (if possible):
https://drive.google.com/open?id=0B6eIpZj0cZQ9ckJ4RE1WWjFTbnM

**Comment by onepiecefreak3** [comment]
All sample files are supported.
Issue closed for now.
