### ISSUE TITLE
[Kukkii Bug] .Xi not shown in the game correctly

### ISSUE THREAD

**Issue by GowSupremo** [IcySon55/Kuriimu#306]
Issue: bug report
Console: 3DS
Format extension(s): xi, xa
Type: image
Game Name: Yokai Watch 3 Sukiyaki

First 8 byte of file(s):
xi - [49 4D 47 43 30 30 00 00] - [IMGC00]
xa - [58 50 43 4B 79 70 05 00] - [bXPCKyp]

More details:
When editing the image the following image is displayed:
![sin titulo](https://user-images.githubusercontent.com/17249334/29844076-5860f3a6-8d0e-11e7-8460-06bc99d2a67a.png)
It may be a compression issue but in Kukkii show normal
![000 xi](https://user-images.githubusercontent.com/17249334/29844363-4fd1f4b4-8d0f-11e7-8a40-32bbe8fad51d.png)

Sample files (if possible):
https://mega.nz/#!wwVwjTYA!cibhaMjIgYup8XyFm6ZAPeS-FY8Y1Z0Y4BHk0BMTyCQ

**Comment by onepiecefreak3** [comment]
I committed a little change to XI. Could you retry everything? After the change the edited picture you linked was also distorted, which means that my changes actually made the process more... true?
Whatever, try again changing the original to your edited one and reinsert. That should work now.
I will wait with closing the issue until tests are done.

**Comment by GowSupremo** [comment]
Okey let's try

**Comment by GowSupremo** [comment]
![sin titulo](https://user-images.githubusercontent.com/17249334/29874582-861fc6f8-8d97-11e7-882c-4ba0c6a32d1e.png)
Issue ready to close

**Comment by onepiecefreak3** [comment]
Perfect
