### ISSUE TITLE
[XPCK] Bug to remplace a .xi in .xa

### ISSUE THREAD

**Issue by GowSupremo** [IcySon55/Kuriimu#307]
Issue: bug report
Console: 3DS
Format extension(s): .xa
Type: archive
Game Name: Yokai watch 3

First 8 byte of file(s):
.xa - [58 50 43 4B 5A 91 05 00] - [XPCKZ‘]

More details:
I get a bug to remplace a .xi edited in .xa to time to save edited
![sin titulo](https://user-images.githubusercontent.com/17249334/29932812-a5ee2568-8e75-11e7-9770-ff272013ab08.png)

Sample files (if possible):
https://mega.nz/#!UtUHWCRA!BIi72ovIz8NzuL6qh0jhJdGpYwuYo63y72BVnvh1P0Y
https://mega.nz/#!owEXlI5S!TfUWWgEHO0C51Mfo9DtAYAQeJDrJ_aTIU-Ycuo6Qi2g

**Comment by onepiecefreak3** [comment]
Ok, the image you provided is completely broken with the newest commit of the XI plugin. Please redo it.

**Comment by onepiecefreak3** [comment]
Also the XPCK problem was solved. Wrong fileCount fixed and committed.
Issue closed.
