### ISSUE TITLE
Error on opening XI files

### ISSUE THREAD

**Issue by m0nm0npalam0n** [IcySon55/Kuriimu#308]
Issue: Error on opening XI files
Console: 3DS
Format extension(s): .xi
Type: image
Game Name: The Snack World Trejarers

First 8 byte of file(s):
<.xi> - [49 4d 47 43 30 30 20 20] - [IMGC00   ]

More details:
Error on opening .xi files
[Image](http://imgur.com/EGE1Wzo)

Sample files (if possible):
[File](https://drive.google.com/file/d/0B1kFLMgtAYMhZklaTTMzQk45WFE/view?usp=drivesdk)

**Comment by onepiecefreak3** [comment]
Ok, I think I solved it. I have to adjust the Save function, but I would like to have more sample files that aren't working.

**Comment by m0nm0npalam0n** [comment]
here are more sample files. :D

[File1](https://drive.google.com/file/d/0B1kFLMgtAYMhVEVzWkZMWWVjUnM/view?usp=drivesdk)
[File2](https://drive.google.com/file/d/0B1kFLMgtAYMhVTdySWtOSkN1SW8/view?usp=drivesdk)
[File3](https://drive.google.com/file/d/0B1kFLMgtAYMhTmFfVTJzc29CdUU/view?usp=drivesdk)

**Comment by onepiecefreak3** [comment]
Images open now and save correctly.
Issue closed.
