### ISSUE TITLE
Jake Hunter: Ghost of the Dusk (LZB)

### ISSUE THREAD

**Issue by Deathmaw** [IcySon55/Kuriimu#311]
Issue: Plugin Request
Console: 3DS
Format extension(s): lzb
Type: Image
Game Name: Jake Hunter: Ghost of the Dusk

First 8 byte of file(s):
lzb (Compressed) - [11 10 00 04 00 70 69 63] - [.....pic]
lzb (Uncompressed) - [70 69 63 61 52 67 34 80] - [picaRg4.]

More details:
Game has lots of .lzb files, I assume they are images, LZ11 Compressed.

Sample files (if possible):
Includes Compressed and Uncompressed versions of the files.
https://mega.nz/#!ckhEiAbD!1trhMK61zRphiOxkaKPWfXI8s7vNAx41Eevtx3NA7-g

**Comment by onepiecefreak3** [comment]
Added Load and Save for this format in the newest commit.
Issue closed.
