### ISSUE TITLE
DGS OBB archive

### ISSUE THREAD

**Issue by wabberz** [IcySon55/Kuriimu#312]
**Issue:** Exotic Android OBB archive (usually run-off-the-mill ZIP, not this one)
**Console:** Android
**Format extension(s):** *.obb
**Type:** archive
**Game Name:** DGS Android port

**First 8 byte of file(s):** 0x2E4F424201000000 | .OBB...

**More details:**
Files seem to be unobfuscated / uncompressed, I couldn't find filenames / paths in the header or footer though. I suspect the filetree is very similar to the one on 3DS

**Sample files (if possible):**
you have access to them already ;)

**Comment by onepiecefreak3** [comment]
OBB archive Load and Save. No filenames included since only hashes are saved.
Issue closed.
