### ISSUE TITLE
Professor Layton vs Phoenix Wright XQ32

### ISSUE THREAD

**Issue by ghostfeesh** [IcySon55/Kuriimu#313]
Issue: Plugin Request
Console: 3DS
Format extension(s): .xq
Type: Possibly text? Unknown.
Game Name: Professor Layton vs Phoenix Wright

First 8 byte of file(s): 
XQ32 - 58 51 33 32 03 00 08 00 - XQ32....

More details:
Very unsure as to what this is. Seems like a text file at first glance.

Sample files (if possible):
https://my.mixtape.moe/ocfsaf.7z

**Comment by onepiecefreak3** [comment]
It's a binary script file, which doesn't seem to contain text but commands for the game and engine. Parts of some xq files are also compressed with Level 5 compression.
Therefore we're not able to do anything. If you can somehow prove me wrong please reopen this issue later.
