### ISSUE TITLE
Non-working CTPKs in NSMB2 that used to work?

### ISSUE THREAD

**Issue by mariomadproductions** [IcySon55/Kuriimu#314]
Issue: bug report
Console: Nintendo 3DS
Format extension(s): ctpk
Type: archive
Game Name: New Super Mario Bros. 2

First 8 byte of file(s):
ctpk - 60 F5 60 F5 60 F5 60 F5 - `õ`õ`õ`õ

More details:
Doesn't load two ctpk files from NSMB2 (USA) and maybe other versions of the game.  Pretty sure they used to, but they don't seem to anymore.

Sample files (if possible):
https://drive.google.com/file/d/0B_yBl-184usmLWZoRklwYnpWSDA/view?usp=sharing

**Comment by onepiecefreak3** [comment]
To be honest ctpk is an image. So try using it with Kukkii. The ctpk plugin for Karameru will be removed in the future.

**Comment by onepiecefreak3** [comment]
This ctpk also looks like it's raw. Support for opening raw image ctpk's was dropped. In Kukkii we now have a raw image converter which you should use to open, edit and save these raw images in the future.
There will be no plugin for them specifically anymore

**Comment by mariomadproductions** [comment]
Thanks. They work in the raw image editor.
