### ISSUE TITLE
New error on opening some .xi files

### ISSUE THREAD

**Issue by m0nm0npalam0n** [IcySon55/Kuriimu#315]
Issue: Error on opening some .xi files 
Console: 3DS
Format extension(s): .xi
Type: image
Game Name: The Snack World Trejarers

First 8 byte of file(s):
<nfc_image01.xi> - [49 4d 47 43 30 30 20 20] - [IMGC00   ]

More details:
Sorry, I was not able to check these files before but its like a new error
[Image](https://imgur.com/63dV6D0)

Sample files (if possible):
[Files](https://drive.google.com/file/d/0B1kFLMgtAYMhREtXOGNEVFIxZzQ/view?usp=drivesdk)

**Comment by onepiecefreak3** [comment]
In the newest commit older block table version weren't ackknowledged correctly.
Fixed in newest commit.
