### ISSUE TITLE
Drakengard 2 dpk file

### ISSUE THREAD

**Issue by ultramario1998** [IcySon55/Kuriimu#316]
Issue: plugin request
Console: PS2
Format extension(s): .BIN
Type: archive
Game Name: Drag-on Dragoon 2 (Drakengard 2)

First 8 byte of file(s):
.BIN - 64 70 6B 00 20 00 00 00 01 - dpk. ....

More details:
From the (quite bad) ps2 game Drakengard 2. Found a few BMS scripts for dpk-packed files, none seemed to result in anything.

Sample files (if possible):
https://drive.google.com/open?id=0B7kSCshLx7JndkhmaTA0ak5fOXM

**Comment by onepiecefreak3** [comment]
I don't know what these 4 int values in every fileEntry mean, but Load and Save without touching them is possible now. Ingame tests would be appreciated after some files are replaced with edited ones.
