### ISSUE TITLE
[Xi]-[IMGC00] Bug report Black screen

### ISSUE THREAD

**Issue by GowSupremo** [IcySon55/Kuriimu#317]
Issue: bug report
Console: 3DS
Format extension(s): .xi
Type: image
Game Name: Yo-Kai watch 3

First 8 byte of file(s):
.xi - [49 4D 47 43 30 30 00 00] - [IMGC00]

More details:
And the problem of the other issue, the one of the compression xi; the image .xi edited not show in game(black screen)
Image to try insert to xi (black screen):
![000 xi](https://user-images.githubusercontent.com/17249334/30024869-0e60641e-9176-11e7-9278-fe61965f02aa.png)
![bot_0001](https://user-images.githubusercontent.com/17249334/30037247-58836f44-91b9-11e7-89c5-818a8ea3df37.png)

 the original show images:
![sin titulo1](https://user-images.githubusercontent.com/17249334/30037225-245ffac0-91b9-11e7-99d5-19587f34363c.png)
![sin titulo](https://user-images.githubusercontent.com/17249334/30037226-24619556-91b9-11e7-852b-75441cb5ad64.png)

Sample files (if possible):
.XI bug show in Kukkii
https://mega.nz/#!loNQmT5B!FK4E7jxGo3FQ7leC3Corx15j765QUZR1TPSJ1_qKIjo
.XI edited not show in game(black screen)
https://mega.nz/#!0kFCjTzZ!EZe51jAKLCFXitWHNNMPOxoVRrCjqZUhlTh08GGbyac

Updated clean files(original clean files):
https://mega.nz/#!px8j1RTZ!fd1Wz7ZIb3ApkxhqyjGOE6XaQS_DnDU3cL1O8gAFzlQ

**Comment by onepiecefreak3** [comment]
So I just fixed a padding bug in XPCK which could have a connection with images not loaded ingame.
Please begin again with a fresh copy of the game and redo your stuff.

**Comment by onepiecefreak3** [comment]
After porting those plugins to Kuriimu2 they were thoroughly tested since. Several bugs regarding black screens, wrong padding, or missing mip maps even, were solved over the course of the testing time. Such bugs cannot be reproduced anymore.
Refer to Kuriimu2 for future bug reports regarding this file format.
