### ISSUE TITLE
Karameru - Error opening IRSLT files 

### ISSUE THREAD

**Issue by Sakaki15** [IcySon55/Kuriimu#320]
Issue: [Feature request]
Console: Nintendo 3DS
Format extension(s): IRSLT
Type: [archive]
Game Name: Azure Striker Gunvolt - Striker Pack

First 8 byte of file(s):
<extension> - [bytes in hex] - [bytes in ASCII]
<IRSLT> - [A7 00 00 00 09 04 00 00 00 00 00 00 9F 1F 00 00] - [3 kB]
More details:
When I open these files using Karameru  I get an error message:

"Nullable object must have a value"

Could there be a way to make opening of these files and extraction possible with Karameru? 

Sample files (if possible):
<https://drive.google.com/drive/folders/0BzPTj5lm0oCOVTlYX1lnZ2l2a00?usp=sharing>
(Screenshots of the error message included in the Drive folder)

**Comment by onepiecefreak3** [comment]
No, this archive isn't supported by us. We have no supported format with this extension.
Only another plugins Identify function could have interpreted it wrong. Which plugin was used is written in the head of the error message as well.

**Comment by onepiecefreak3** [comment]
Please edit your issue with a full picture of the error message and rewrite it as a format request. Also delete the "DELETE ME" part for obvious reasons.

**Comment by Sakaki15** [comment]
I found a way to solve this issue, thank you. I shall close it since it's solved.
