### ISSUE TITLE
Azure Striker Gunvolt: VAP Files

### ISSUE THREAD

**Issue by Sakaki15** [IcySon55/Kuriimu#321]
Issue: [plugin request]
Console: Nintendo 3DS
Format extension(s): .VAP
Type: [archive]
Game Name: Azure Striker Gunvolt

First 8 byte of file(s):
<.VAP> - [01 00 00 00 08 00 00 00] - []

More details:
- [x] VAP
- [x] IOBJ/PTGT

I found a method to decompress IRARC and IRLST files. These contain a bunch of .VAP files.

Looking at them with the HEX editor, I find the common header "IOBJ" and "PTGT" in several of them which make me think they might be containers for these graphical resources (2nd sprites).

Could there be a way to access /extract the information inside?

I send two samples: one which has these headers (1b) and another which doesn't (0a6).

Sample files (if possible):
https://drive.google.com/open?id=0BzPTj5lm0oCOVTlYX1lnZ2l2a00

**Comment by onepiecefreak3** [comment]
Not too complicated.
I would like to have some files where the PTGT header is written somewhere in file also.
Then I will also just do an image plugin for IOBJ and PTGT (if that is an image).

**Comment by Sakaki15** [comment]
Thank you very much.

I added 5 samples each from each decompressed folder: all have the IOBJ and PTGT headers written on them.

Drive folder:
https://drive.google.com/open?id=0BzPTj5lm0oCOVTlYX1lnZ2l2a00

I hope this is of help.

**Comment by onepiecefreak3** [comment]
Added VAP Load and Save in newest commit.

**Comment by onepiecefreak3** [comment]
I need more IOBJ's.

**Comment by Sakaki15** [comment]
Roger.

I added 15 more files to the drive folder. If needed I will add more. 

Folder: 
https://drive.google.com/open?id=0BzPTj5lm0oCOVTlYX1lnZ2l2a00

**Comment by onepiecefreak3** [comment]
Redone the format identifier.
Load and Save of IOBJ/PTGT should be done.
I therefore close the issue.
