### ISSUE TITLE
Save issue.

### ISSUE THREAD

**Issue by Damin72** [IcySon55/Kuriimu#322]
Issue: Bug Report

Format extension(s): CTPK
Type: IMAGE
Game Name: Fire Emblem Awakening

First 8 byte of file(s):
<CTPK> - [43 54 50 4B 01 00 02 00] - [CTPK....]

More details:
Cant save edited file. When i try do this - programm give me this error.
https://imgur.com/SeCAYm6

File: https://drive.google.com/file/d/0B9vr_WZsN50DWk9td01ZcDNNTVk/view?usp=sharing

**Comment by onepiecefreak3** [comment]
Good that the error message is russian...

**Comment by onepiecefreak3** [comment]
Also the error can't be reproduced.

**Comment by Damin72** [comment]
**onepiecefreak3**, i can translate "Save flow not available for write".

**Comment by onepiecefreak3** [comment]
Ok, the error couldn't be reproduced by me. Is the ctpk open somewhere else? And are you on the newest release?

**Comment by Damin72** [comment]
**onepiecefreak3**, newest release, yes, and no, only unpack with FEAT.

**Comment by onepiecefreak3** [comment]
What is FEAT?

**Comment by Damin72** [comment]
Fire Emblem Archive Tool

**Comment by onepiecefreak3** [comment]
Well, like I said I couldn't reproduce the error. The error means that the file isn't available to be opened and saved again, because it's opened in some other applications for example.
It's not a problem with Kukkii.

**Comment by Damin72** [comment]
onepiecefreak3, hm... It's really strange.

**Comment by onepiecefreak3** [comment]
Well since it's not a direct error with Kukkii, I'll close this issue.
