### ISSUE TITLE
Dragon Quest XI - PACK support

### ISSUE THREAD

**Issue by Z6n4** [IcySon55/Kuriimu#323]
Issue: additional .PACK archive variant
Console: 3DS 
Format extension(s): .pack
Type: archive
Game Name: Dragon Quest XI 

First 8 byte of file(s):
.pack - 50 41 43 4B 28 15 00 - PACK(

More details:
.PACK seems to be a variant of SARC from what I read, but know little of the format.
It houses more game files, with the word TRAP repeated a lot through out.

Sample files (if possible):
https://cdn.discordapp.com/attachments/302924691524288513/340895373910343691/a_000.pack
https://cdn.discordapp.com/attachments/302924691524288513/357495628932317184/a_000_cs_000_script.pack
https://cdn.discordapp.com/attachments/302924691524288513/357495641821282305/a_000_cs_000_tcs.pack
https://cdn.discordapp.com/attachments/302924691524288513/357495544450514946/fieldcmn.pack
https://cdn.discordapp.com/attachments/302924691524288513/357495582689984512/gamecmn.pack

**Comment by onepiecefreak3** [comment]
Need more pack files to work the plugin out better.
Basic Load finsihed. Based on this small file I also write a basic Save.

**Comment by onepiecefreak3** [comment]
Basic Save finished. Still more files needed.

**Comment by belnades** [comment]
Hi!

I'm looking to create a menu patch for DQXI 3DS. I can translate, but I can't program so any help is appreciated. There are still issues opening .PACK files in Karameru, so I've included a selection of the ones that don't open. 

There are 9 files here:
https://cdn.discordapp.com/attachments/518345447631224833/518364891829239841/packs.rar

On the off chance that this is at all useful, I'm including it: http://forum.xentax.com/viewtopic.php?f=10&t=16625

**Comment by omarrrio** [comment]
Hello @belnades , i am currently working on this file type, i completely figured it out, please do contact me either in discord: YuseiFD#7425 or by e-mail: olivero930223@gmail.com
This goes for @Z6n4 aswell, thank you very much.

**Comment by Z6n4** [comment]
Closed this issue as it is irrelevant

**Comment by onepiecefreak3** [comment]
Just to leave my footprint here as well, after that long.
Kuriimu2 now supports a wider variety of PACK files in DQXI.
However PACA files (also have the extension .pack) should have the same specification, but they seem to have another layer of something over them. Therefore they are not supported as of writing this comment, and probably won't be (if someone doesn't pick it up)
