### ISSUE TITLE
Azure Striker Gunvolt- DAT Files

### ISSUE THREAD

**Issue by Sakaki15** [IcySon55/Kuriimu#325]
Issue: [plugin request]
Console: Nintendo 3DS
Format extension(s): .DAT
Type: [archive]
Game Name: Azure Striker Gunvolt

First 8 byte of file(s):
<.DAT> - [18 00 00 00] - []

More details:
Extracting from the game's IRARC files, apart from the previously reported .VAP files, I found another bunch of .DAT files, several of which also contain IOBJ inside and may be a container for IOBJ file similar to the .VAP files.

If possible, could I ask for a new plugin so that Karameru can open and extract these files as well? Thank you very much. 

All examples contain IOBJ.

Sample files (if possible):
<https://drive.google.com/drive/u/0/folders/0BzPTj5lm0oCOVTlYX1lnZ2l2a00>

**Comment by onepiecefreak3** [comment]
This is added in the newest dev build of Kuriimu2 and its upcoming Release 1.2.1. This is a manual plugin, which means this format cannot be automatically detected. If asked for a plugin, choose the "DAT" plugin under "plugin_inti_creates.dll" to open those DAT files.
Refer to the Kuriimu2 github to request further file formats or bug fixes on this format. Issue closed.
