### ISSUE TITLE
Nintendo Yaz0

### ISSUE THREAD

**Issue by Rus3545** [IcySon55/Kuriimu#326]
Issue: [bug report]
Console: N64, 3DS, WiiU
Format extension(s): yaz, szs
Type: [archive]
Game Name: Series Zelda

First 8 byte of file(s):
<extension> - [59617A3000003300] - [Yaz0]

More details:
Correct decompression and compression (order byte file size), increase the compression ratio if possible.

Sample files (if possible):
https://www.sendspace.com/file/6p7usd

**Comment by onepiecefreak3** [comment]
In Yaz0, Yay0 and MIO0 you can now chhose between Liitle Endian or Big Endian storage of for example file size bytes.
Also Nintendo.py was now used for better compression ratio, but compression time increased a lot.
