### ISSUE TITLE
[Karameru] DQ Builders (.psarc)

### ISSUE THREAD

**Issue by GowSupremo** [IcySon55/Kuriimu#327]
Issue: plugin request
Console: PS3
Format extension(s): .psarc
Type: archive
Game Name: Dragon Quest Builders

First 8 byte of file(s):
.psarc - [50 53 41 52 00 01 00 03] - [PSAR]

More details:
It is possible that this compressed in ZLIB

Sample files (if possible):
https://mega.nz/#!httk0JSC!KRJuEgRAV5sZa3qeIhaVNxSTnsnOzcxm5IVA6YvrcAo

**Comment by GowSupremo** [comment]
Information and documentation on:
http://www.psdevwiki.com/ps3/PlayStation_archive_(PSARC)

**Comment by amadeusnorn** [comment]
more examples for .psarc, already decrypted: 
https://drive.google.com/open?id=1OPOmnElKoL2ELzpQ55Ovq2-K8eY2hwXu

**Comment by IcySon55** [comment]
Hey @GowSupremo, work on the PSARC plugin for the files you provided is 50% complete. Extraction is possible. Save is coming next. Currently you have to build the app yourself to get the plugin.

**Comment by GowSupremo** [comment]
Thx, with this plugin, almost all play station games can be opened.

**Comment by IcySon55** [comment]
We're still missing support for encrypted blocks but that'll come later.

**Comment by IcySon55** [comment]
~~We're still missing support for encrypted blocks but that'll come later.~~

Nevermind, the files in question aren't encrypted with a known encryption and can be ignored for the time being. Save is coming next.

**Comment by IcySon55** [comment]
Done. The PSARC plugin is now ready to use for ZLib compressed PSARC files. LZMA is not yet implemented.

The plugin is available in the latest beta that you can download o our Discord server.
