### ISSUE TITLE
Dragon Quest 3 .dat files

### ISSUE THREAD

**Issue by ultramario1998** [IcySon55/Kuriimu#330]
Issue: plugin request
Console: 3DS
Format extension(s): .dat
Type: archive
Game Name: Dragon Quest 3 (Eshop ver)

First 8 byte of file(s):
.dat - 4EF629747E6928444E - N.)t~i(DN

More details:
While the extension itself is .dat, the file header doesn't seem to have any extension-related information; it's different between files.

Sample files (if possible):
https://drive.google.com/open?id=0B7kSCshLx7JnOG1YRm82ZGJOYk0

**Comment by onepiecefreak3** [comment]
This is implemented in the newest dev build of Kuriimu2 and its upcoming Release 1.2.1.
A quick overview of the file format:
1. A list of strings, preceeded by the list count.
2. A list of file sizes, preceeded by the list count.
3. The file data itself.

Each dat file is encrypted by XOR. The key to de-/encrypt those files is 0x4E692975. The plugin automatically de-/encrypts the file as necessary.

The added plugin can load and save all changes. It is a manual plugin, which means it can not identify the file automatically. Choose the plugin "DQ3 DAT" under "plugin_square_enix.dll" to load a file from this game.
If there are further requests or bug reports, please refer to Kuriimu2 in the future.
