### ISSUE TITLE
Support for .bctex mipmaps

### ISSUE THREAD

**Issue by M-1-RLG** [IcySon55/Kuriimu#334]
Issue: [feature request]
Console: 3DS
Format extension(s): .bctex
Type: [image]
Game Name: Various 3ds games

First 8 byte of file(s):
[Hex bytes 43 47 46 58 FF FE 14 00 00]

Sample files (if possible):
< https://cdn.discordapp.com/attachments/291648244587429888/359187575627448320/cubecreator_markermap.bctex https://cdn.discordapp.com/attachments/291648244587429888/359187580534652928/cubecreator_bordermap.bctex >

**Comment by onepiecefreak3** [comment]
Ok, 2 things:
What IS your feature request?
Ehat do you think is "Game Name" for? You have to write a specific game.

**Comment by onepiecefreak3** [comment]
Also mipMap support added.
Issue closed.
