### ISSUE TITLE
SARC Containers

### ISSUE THREAD

**Issue by Rus3545** [IcySon55/Kuriimu#338]
Issue: [bug report ]
Console: 3DS, WiiU
Format extension(s): any
Type: [archive]
Game Name: Zelda series, Project Zero

First 8 byte of file(s):
szs - [534152430014FEFF] - [SARC]
any - [534152431400FFFE] - [SARC]

More details:
Please fix work with 3DS files. I believe that the containers should be re-assembled original files without any differents. Perhaps this is any alignments. Names of the files, look at the pictures named *_different.jpg.
Many files are packed with Yaz0 and without the solution https://github.com/IcySon55/Kuriimu/issues/326 Kuriimu can not open them to check this. Also WiiU SARC's contains lots more stuff WiiU bflim's for https://github.com/IcySon55/Kuriimu/issues/329
Add WiiU support, if possible.

Sample files (if possible):
https://www.sendspace.com/file/0wfynu

**Comment by ericjwg** [comment]
used this tool for wiiu.
http://wiki.tockdom.com/wiki/Wexos's_Toolbox

**Comment by Rus3545** [comment]
Thank you. Competition. )))
It's great.
Although Yaz0 is not implemented in the best way (apparently based on Wiimms_SZS_Tools), but at least works unlike the implementation (LordNed_WArchive-Tools) used in Kuriimu. SARC_WiiU & 3DS and bflim_WiiU are beautiful, I need to test this in more detail. Thanks again.

At the moment, the best implementation of MIO, Yaz, and Yay: https://pastebin.com/GUHMwpjT
P.S. The storage time for most files in the file storage has expired ...

**Comment by onepiecefreak3** [comment]
Could you reupload them?
I will implement the better compressions now

**Comment by Rus3545** [comment]
I could not edit the issue. ... and did not understand why. But SARC's files reuploaded: https://www.sendspace.com/file/nvy9za

**Comment by onepiecefreak3** [comment]
And with the closure of both tagged issues we can now come down to this main issue.

**Comment by onepiecefreak3** [comment]
Back to this issue to implement SARC in Kuriimu2.
Kuriimu2 should take better care of this format and its different file type alignments. Fingers crossed.

**Comment by onepiecefreak3** [comment]
The SARC plugin was added to the newest dev build and upcomgin Release 1.2.1 of Kuriimu2.
It can automatically detect normal and Yaz0 compressed SARC's, open, and edit them.
All issues mentioned in this issue regarding alignments were fixed with the port to Kuriimu2.
Therefore this issue is closed.
