### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DarthManto** [IcySon55/Kuriimu#341]
Issue: Bug Request
Console: 3DS
Format extension(s): .xi or .xb
Type: image
Game Name: Inazuma Eleven GO: Galaxy Supernova

First 8 byte of file(s):
multiple files

More details:

I'm able to extract the files and replace the files within the .xb file but as soon as i replace it within the games files it corrupts the game files. some of the files work such as vka0001 but then others corrupt for example vka0011.

Sample files (if possible):

https://mega.nz/#!hXhm1KAC!uNbTpZtwhKSr-ueyQURXm3AZAofuXsu1qQZAdcR6kcM ---- Original files

https://mega.nz/#!9KpRCRwK!amvcgBQigsbHTnCQIINprxM4KoH4B9qYVqbpDdM5nrg ---- Modified Files

**Comment by onepiecefreak3** [comment]
Those issues were resolved along with excessive testing by translation groups for this game.
Issue closed.
