### ISSUE TITLE
VIW Archive Plugin

### ISSUE THREAD

**Issue by joesteve1914** [IcySon55/Kuriimu#342]
Issue: Bug report
Console: NDS
Format extension(s): .viw/.inf
Type: archive
Game Name: Ripened Tingle's Balloon Trip of Love

More details:
When executing a batch extract in Karameru, this message appears - https://s26.postimg.org/dylogdkdl/Capture.jpg
It extracts some files (for example it goes up to 0CE0.bin in resLibAnm2) but then that message appears.

**Comment by joesteve1914** [comment]
Well I just realized I was trying to open an archive that I had already edited before. So I tried batch extract on resLibAnm2 from the original unmodified rom, and it gave me a different error-
https://s26.postimg.org/m6s7f41nt/capture1.jpg

**Comment by IcySon55** [comment]
I've modified the batch execution to skip files that cause erros.
