### ISSUE TITLE
Inazuma pck issue

### ISSUE THREAD

**Issue by DarthManto** [IcySon55/Kuriimu#343]
Issue: bug report
Console: 3ds
Format extension(s): .pck
Type: archive i think
Game Name: Inazuma Eleven galaxy

First 8 byte of file(s):
.pck - 61 76 33 01 00 58 50 43 4B 17 50 05 00 00 4A 00 - [av3..XPCK.P...J.]
More details:

It re-compresses but doesn't work in my game.

Sample files (if possible):

https://mega.nz/#!oWAT1RLZ!Amw-Hec_mPYrO8HHfXqM4Qk1wTtQO5BsvfXxGiL85Pk

**Comment by onepiecefreak3** [comment]
Along with issue #341 this is not reproducable as well, and probably already fixed due to excessive testing by the translation groups working on this game. Refer to the Kuriimu2 github if errors or bugs persist with those formats.
