### ISSUE TITLE
Level-5: Layton's Mystery Journey .obb

### ISSUE THREAD

**Issue by DecodeTalker** [IcySon55/Kuriimu#347]
Issue: plugin request
Console: Android
Format extension(s): .obb
Type: archive
Game Name: Layton's Mystery Journey

First 8 byte of file(s):
.obb - [48 50 31 30 F2 17 00 00] - [HP10ò...]

Sample files (if possible):
https://mega.nz/#!A6wFVRiK!mN1WdsPd1Q-ZzSk4End29gHvsVKt2GzXWY8pa5Oj_us

**Comment by onepiecefreak3** [comment]
This is already supported in Kuriimu2's newest dev build and upcoming Release 1.2.1.
Issue closed.
