### ISSUE TITLE
Most of the text files from M&L Superstar Saga is not able to open 

### ISSUE THREAD

**Issue by Spmario233** [IcySon55/Kuriimu#350]
Issue: [bug report]
Console: 3DS
Format extension(s): msbt
Type: [text]
Game Name: Mario & Luigi Superstar Saga

First 8 byte of file(s):
<extension> - [4d7367537464426e] - [MsgStdBn]

More details:
<details>Some of the textfiles is able to edit on the old MSBT Editor Reloaded V 0.9.8(About 7%,include files from FMsg.dat and BMsg.dat),but the open-able files is even less in Kuriimu

Sample files (if possible):
<links> https://mega.nz/#!mQcX0SZC!uvOFTZ7mLme_Wdy-OQnHen-v6UpuTcPdGFc9j0C4fw0

**Comment by ericjwg** [comment]
same issue as
https://github.com/IcySon55/Kuriimu/issues/336
