### ISSUE TITLE
Danganronpa - File compressor - PSVITA

### ISSUE THREAD

**Issue by Liquid-S** [IcySon55/Kuriimu#351]
Issue: Plugin request
Console: PSVITA
Format extension(s): Compressed files doesn't have a specific extension when extracted.
Type: Images
Game Name: Danganronpa 1 - Danganronpa 2 - Danganronpa: Another Episode

First 8 byte of file(s):
Extension: Compressed files doesn't have a specific extension when extracted.
Bytes in hex: FC AA 55 A7 50 00 08 00 D1
Bytes in ASCII: üªU§P...Ñ

More details:
We are able to extract files and convert them from GXT-SHTX-SHTXFS to PNG and viceversa, however we need a way to re-compress the files. The games can handle a few decompressed images, but they will crash if you try to insert more images.

We use Scarlet to decompress and convert images to PNG. https://github.com/xdanieldzd/Scarlet/blob/master/Scarlet.IO.CompressionFormats/SpikeDRVita.cs
The author already told us that Scarlet is made only to extract things, not to repack them.

To convert images from PNG to their original format we use some other tools that we cannot mention here.

We are working on a fan-translation, everything is ready (text and images), we just need a compressor for the images and fonts.

Sample files (if possible):
https://www.mediafire.com/file/xpvqre1gyo7bqqv/ExampleDR1FontComp-Dec.7z
![screenshot 2017-10-11 14 06 51](https://user-images.githubusercontent.com/22280453/31440344-df1758b6-ae8f-11e7-9656-28f0e779dcc2.png)

**Comment by Liquid-S** [comment]
It seems to work for now, however the compression isn't good as the original as you said.

Here you have some extra samples: http://www.mediafire.com/file/ytzc5fd67stl04j/DR1_PSVITA_title_bg.7z (it contains original compressed files and files compressed with kuriimu)

**Comment by onepiecefreak3** [comment]
The compression is fully supported in Kuriimu2 and in better compression ratio as well. There is currently one sample where compression takes ages, because of a less optimized approach in our match finder, but this is being worked on parallely.
The image formats SHTX is supported by Kuriimu2. Therefore this issue gets closed.
