### ISSUE TITLE
Kukki/Karameru error

### ISSUE THREAD

**Issue by DarthManto** [IcySon55/Kuriimu#352]
Issue: Bug
Console: 3DS
Format extension(s): .xi or .xb
Type: image
Game Name: Inazuma Eleven GO: Galaxy Supernova

First 8 byte of file(s):
multiple files

More details:

Doesn't show up in Kukki when i try to open the files while in Karameru. Due to this it won't let me mass import images. I can however open up the files one by one and they'll work.

**Comment by IcySon55** [comment]
Use the batch functions instead of right click > Kukkii.
Replacing the image through right click will NOT replace it the image in Karameru.

**Comment by DarthManto** [comment]
Fixed with newest release.
