### ISSUE TITLE
Plugin request: bflyt

### ISSUE THREAD

**Issue by mariomadproductions** [IcySon55/Kuriimu#356]
Issue: plugin request
Console: Wii U
Format extension(s): bflyt
Type: image
Game Name: [Multiple]

First 8 byte of file(s):
bflyt - 46 4C 59 54 FE FF 00 14 - FLYTþÿ..

More details:
Wii U equivalent of bclyt. May just be big-endian version of bclyt.
There is a program called BenzinU that supports converting bflyt into XML.

Sample files (if possible):
https://drive.google.com/file/d/0B_yBl-184usmVnFxSGtsc1I3YmM/view?usp=sharing
https://drive.google.com/file/d/0B_yBl-184usmNkNLYU5aZ3FGX3c/view?usp=sharing

**Comment by IcySon55** [comment]
BFLYT is not an image format. It's a screen layout format, and is actually pretty complicated.

We currently have partial support for BCLYT as an image plugin just so that we can visualize it.

**Comment by mariomadproductions** [comment]
Yeah, I was just trying to fit it in with the example categories.

**Comment by ericjwg** [comment]
for wiiu: http://wiki.tockdom.com/wiki/Wexos's_Toolbox

**Comment by onepiecefreak3** [comment]
Cause of its complexity and our app being unable to properly show layouts yet, I will close this issue as invalid.
