### ISSUE TITLE
Dual Destinies - It can't read these files properly

### ISSUE THREAD

**Issue by linkenski** [IcySon55/Kuriimu#357]
Issue: Unable to read vanilla GMDs
Console: 3DS
Format extension(s): .GMD
Type: Text
Game Name: Phoenix Wright: Ace Attorney - Dual Destinies

First 8 byte of file(s):
.GMD - 47 4D 44 00 (like this?)

More details:
It shows the sequences (or segments, whatever) properly on the left side. It's the text itself that loads abnormally

Screenshots:
[Screenshot of opening _sce00_c002_0001_eng.gmd](https://i.imgur.com/pODuSJM.png)
[Screenshot of opening _sce00_c001_0000_eng.gmd](https://i.imgur.com/TeKF4wu.png)

Sample files (if possible):
https://drive.google.com/open?id=0B5QB_hz8w0EMV0ctSW1BeGNPS3M (this one gave error)
https://drive.google.com/open?id=0B5QB_hz8w0EMLW1aeGJ0c1M4dFE (this one opens)
[Text_gmd.dll as requested](https://drive.google.com/open?id=0B5QB_hz8w0EMNnU5T0FjM1hTZTg)

**Comment by onepiecefreak3** [comment]
This is the newest GMD plugin currently available:
https://mega.nz/#!Q14XxY5B!F4Fx4KAq-yuMKBQxDcYqUBtCp9bVHszahkA91dlacAU

Don't forget to unblock the DLL, because Windows is stupid.
