### ISSUE TITLE
Dual Destinies - Certain GMDs open with error

### ISSUE THREAD

**Issue by linkenski** [IcySon55/Kuriimu#358]
Issue: Bug report
Console: 3DS
Format extension(s): .GMD
Type: Text
Game Name: Phoenix Wright: Ace Attorney - Dual Destinies

First 8 byte of file(s):
GMD - [47 4D 44 00] - [bytes in ASCII]

More details:
Most GMDs open but it seems many of the smaller ones don't.

Sample files (if possible):
https://drive.google.com/open?id=0B5QB_hz8w0EMRVN4X0RzM2JEMFk
[Screenshot of trying to open this file](https://i.imgur.com/dU9P9lI.png)

**Comment by onepiecefreak3** [comment]
GMD's openable in newest commit. Maybe you should think about compiling this repo yourself or wait for a new release

**Comment by linkenski** [comment]
When I'm able to open GMDs in 1.0.10 (albeit with gibberish) it still only loads some. My other manual GMD unpacker not associated with Kuriimu (which works) also can't open these particular files.
