### ISSUE TITLE
Fix Request: Batch Exported Picture Names

### ISSUE THREAD

**Issue by SteveDoido** [IcySon55/Kuriimu#360]
![image](https://user-images.githubusercontent.com/25571367/32305041-2713e0e6-bf5a-11e7-8a09-ab72dc1566f8.png)
When Kuuki batch extracs a folder, the file names happen to be different to what they need to be for batch importing. For that to work, the files need to be in the same folder and have the same name, just with a different extension. For example: "0001.bch" and "0001.png" in the same folder. Instead, the tool  creates "0001.bch.00.png", which although in the same folder, isn't recognized for batch importing.

My suggestion is to have an output name that can be instantly read back by the utility, so I could edit some pictures and put them back in quickly, for example.

**Comment by IcySon55** [comment]
Those names are supposed to be read back by Kukkii's batch import, unless a bug snuck in. Nope, I just checked and Kukkii's abtch import is definitely looking for **filename.ext.index.png** during import.

**Comment by SteveDoido** [comment]
Hum...
![image](https://user-images.githubusercontent.com/25571367/32324865-e79b2d70-bfb3-11e7-80db-57313e4f01b5.png)
Not working for me.

**Comment by SteveDoido** [comment]
[bch.zip](https://github.com/IcySon55/Kuriimu/files/1437611/bch.zip)

Try batch extracting and importing these.

**Comment by IcySon55** [comment]
Which version are you using?

**Comment by IcySon55** [comment]
@SteveDoido Please download the latest release and test this again. If there is no problem anymore, please close the issue.

**Comment by onepiecefreak3** [comment]
What a coincidence I wanted to try this batch problem exactly now.

**Comment by onepiecefreak3** [comment]
Both, save in place and batch export/import on bch's are possible with the newest release.
Closing issue.
