### ISSUE TITLE
Incorrect interpretation of .ssa file for Osawari Tantei 3

### ISSUE THREAD

**Issue by miniluigi008** [IcySon55/Kuriimu#361]
Issue: Bug Report
Console: 3DS (all)
Format extension(s): .ssa
Type: text
Game Name: Osawari Tantei: Ozawa Rina Rising 3 Nameko ha Banana Yume wo Miru ka? translated "Touch Detective Rising 3: Does Funghi Dream of Bananas?"

First 8 byte of file(s):
ssa
.'..........è...
10 27 00 00 0A 00 00 00 00 00 00 00 E8 03 00 00

More details:
The game has a script folder which contains what I assume are direct commands to manipulate the characters in the game's story. In the first ssa file of the script, it points to actor ssa files which I assumed to contain translatable text but it shows up as a bunch of null tags with some odd characters here and there. Upon further examination there appear to be commands such as IMGX, IMGY, FLPVT which seem pretty self explanatory (image x, image y, flip vertical, etc.) but since I didn't design this game I have no idea what these files do. If I find a more readable text file that is translatable I will add a comment to this issue. It would be nice to have these manipulable if the game's text turns out to be in files like this.

I would provide sample files but I'm not sure how much is allowed per se.

![Link to image of interpreted text](
https://media.discordapp.net/attachments/216682963553878018/377553830339936268/image.png?width=601&height=208)

**Comment by onepiecefreak3** [comment]
You can upload as much as you like. Just pay attention that you don't attach them directly in the issue. You should use a file hosting service like mega.co.nz, google drive or whatever floats your boat.

**Comment by miniluigi008** [comment]
Alright. I'm going to link to one folder which will contain the three files for each of the issues in the topmost directory and then other related folders for further examination.

**Comment by miniluigi008** [comment]
https://www.4shared.com/folder/SLoEkAZg/_online.html
whoa howd that get there

**Comment by onepiecefreak3** [comment]
These files seem more like a XML-like structure and doesn't have anything to do with text per-se.

**Comment by onepiecefreak3** [comment]
I close this issue since we can't rly support it now. And being a layout it's not possible for us to do anything.
