### ISSUE TITLE
Cannot open .txp

### ISSUE THREAD

**Issue by miniluigi008** [IcySon55/Kuriimu#362]
Issue: plugin request
Console: 3DS (all)
Format extension(s): txp
Type: could be text or image, either way it is decrypted
Game Name: Osawari Tantei 3 (Touch Detective 3)

First 8 byte of file(s):
txp - 11 80 80 00 00 43 54 50 4B 01 00 01 00 0A 80 00 - .€€..CTPK.....€.

More details:
Not sure what these files are but they are in the game alongside the ssa actor files.
Upon further examination they might be images, since the majority of files in the image folders are txp.

**Comment by onepiecefreak3** [comment]
It is compressed. Neither de- or encrypted.
The compression is LZ11. You can use our Tool to decompress it yourself. After that it's a simple CTPK that should open normally.
Tools > Compression > Nintendo > Decompress > General

Please report if it works after that.

**Comment by miniluigi008** [comment]
It says the magic number in the GZIP header is not correct.

**Comment by IcySon55** [comment]
Tools > Compression > Decompress > Nintendo > General

**Comment by onepiecefreak3** [comment]
@IcySon55 No.  General doesn't take care of LZ77. LZ77 isn't part of the standard Nintendo compression header.
Since we stated twice how to decompress it now I state this issue as closed.
