### ISSUE TITLE
Unable to open vcd files

### ISSUE THREAD

**Issue by miniluigi008** [IcySon55/Kuriimu#363]
Issue: plugin request
Console: 3DS (all)
Format extension(s): vcd
Type: looks to be text
Game Name: Osawari Tantei 3 (Touch Detective 3)

I'll give a snippet here since that might be more useful.

vcd

``93 00 00 00 40 00 00 00 00 00 00 00 00 00 00 00 70 29 00 00 DC 08 00 00 6D 6D 65 6E 75 30 30 31 2E 73 73 61 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 32 00 00 F0 0B 00 00 6D 6D 65 6E 75 30 30 32 2E 73 73 61 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40 3E 00 00 94 0A 00 00 6D 6D 65 6E 75 30 30 33 2E 73 73 61 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 E0 48 00 00 84 0E 00 00 6D 6D 65 6E 75 30 30 34 2E 73 73 61 00 00 00 00``

``“...@...........p)..Ü...mmenu001.ssa....................................................P2..ð...mmenu002.ssa....................................................@>..”...mmenu003.ssa....................................................àH..„...mmenu004.ssa....``

More details:
Oddly the file is named "MainMenuSsa" so it appears to be a large directory for the other files.

**Comment by miniluigi008** [comment]
Windows said vcd but when opened in the hex editor it says .dat which is probably the official extension.

**Comment by onepiecefreak3** [comment]
It looks more like an archive.

**Comment by onepiecefreak3** [comment]
I still don't get how your PC "thinks" this file is a vcd. It doesn't have this extension at all not has it any header magic or similar, so it couldn't identify it at all.
Your PC is weird.

**Comment by onepiecefreak3** [comment]
Also it would have been more useful to give the file itself as a sample, like the issue template suggested instead of giving a snippet. However I got the game already.

**Comment by onepiecefreak3** [comment]
The archive is supported in the newest commit. Issue closed.
