### ISSUE TITLE
Unable to save CGFX files

### ISSUE THREAD

**Issue by Spmario233** [IcySon55/Kuriimu#364]
Issue: [bug report]
Console: Nintendo 3DS
Format extension(s): CGFX
Type: [image]
Game Name: Mario & Luigi Superstar Saga + Bowser's Minions

First 8 byte of file(s):
<extension> - [43 47 46 58 FF FE 14 00 00 00 00 05 00 99 02 00] - [CGFXÿþ.......™..]

More details:
<details>Unable to save CGFX files

Sample files (if possible):
<links>

**Comment by onepiecefreak3** [comment]
In the newest commit CGFX was made able to save normally in-place and somewhere else.
