### ISSUE TITLE
PL vs Ace Attorney (LEVEL5 .fa editing issue)

### ISSUE THREAD

**Issue by Damin72** [IcySon55/Kuriimu#365]
Issue: [Bug report]
Console: 3DS
Format extension(s): fa
Type: [Archive and Image]
Game Name: Professor Layton vs Ace Attorney

First 8 byte of file(s):
<fa> - [58 46 53 41 24 00 00 00 70]
More details:
When i trying replace texture 000.xi in file title_b00.xa in folder ui/uk/, save vs1.fa, then put this file on console, game doesn't work (Trying with LayeredFS on Luma 3DS). I don't know why this happen. 0_o No errors in programm, no errors in game (Just black screen)

Sample files (if possible): This edited texture 000.xi in png.
https://drive.google.com/open?id=17HNsN_j1tcaxzQdEuPobba0lNxELS10C

**Comment by onepiecefreak3** [comment]
Well, I think it's more a problem with the archive or the image format.
So just the png won't do...
If the fa is too big, then please just link the xi image (original and edited). Thx

**Comment by Damin72** [comment]
https://drive.google.com/open?id=1QyrqYIwRfBEExkDQO3cZfuQZczj2DHHB
Upload archive

**Comment by onepiecefreak3** [comment]
After some checks the archive gets saved byte-perfect in its original state. Replacing the image works without error (like for you as you said).
So I don't see any reason why the game could crash.

**Comment by onepiecefreak3** [comment]
I revised the plugin again and found some bugs which are solved now. After some testing I could get the game load up with the edited .fa and your edited image. Therefore this issue is fixed with the newest commit.
