### ISSUE TITLE
Sonic Forces .cnvrs-text

### ISSUE THREAD

**Issue by ActualMandM** [IcySon55/Kuriimu#369]
Issue: plugin request
Console: PC 
Format extension(s): .cnvrs-text
Type: text
Game Name: Sonic Forces

First 8 byte of file(s):
.cnvrs-text - 42 49 4E 41 32 31 30 4C - BINA210L

More details:
The text is in plain Unicode/UTF-16 (English), easy text edits is possible. There is a .codetbl file that comes along with the .cnvrs-text file but I doubt it's anything important.

Sample files (if possible):
https://drive.google.com/open?id=1Dr2VXYEEuk23VXUYkB8NgI6klPPuapuT

**Comment by asm95** [comment]
A good place to start is to check how HedgeLib reads `.cnvrs-text`. Check out here: [Radfordhound/HedgeLib/HedgeTools/HedgeCnvrsEditor/](https://github.com/Radfordhound/HedgeLib/tree/master/HedgeTools/HedgeCnvrsEditor)

**Comment by slashiee** [comment]
the proper file would be https://github.Radfordhound/HedgeLib/blob/master/HedgeLib/Misc/ForcesText.cs

**Comment by ActualMandM** [comment]
Transferred over to Kuriimu2 repo
