### ISSUE TITLE
Plugin Heroes of Mana .dat

### ISSUE THREAD

**Issue by Bleachya** [IcySon55/Kuriimu#371]
Issue: plugin request
Console: NDS
Format extension(s): .dat
Type: archive
Game Name: Heroes of Mana

First 8 byte of file(s):
<extension> - [bytes in hex] - [bytes in ASCII]
.dat - 41 4E 41 47 58 00 00 00 - ANAGX...

More details:

This file is a big archive containing text and maybe more. The text is situated roughly at the middle of the file and the characters of the text are 2 bytes long. Pointers seems to be situated after the text.

Sample files (if possible):
https://mega.nz/#!IrADjTIC!VK2wluPIdOQ88pZJ2Oi3KRUlEw7ZQUxLcmtYacYctAE

**Comment by onepiecefreak3** [comment]
Seems to be a multi layer archive. Like expected from a DS game seemingly dependant.
That could be a bit harsh to properly program. Could take a while.

**Comment by onepiecefreak3** [comment]
The best option I can see here is to make a separate mapping file, having stored the offsets and sizes of the files themselves. And if a size changes you have to recursively change every offset.
The structure doesn't have any indicator of having an offset or filestream.
But that is rly heavy work for this big file. That's rly a problem.

**Comment by onepiecefreak3** [comment]
But the game has to know the fileSize also, so it could also rely on information from the binary of the game. Ugh, I hate these filetypes.

**Comment by Bleachya** [comment]
Could it be that the table for the archive is stored here? I'm taking a wild guess, I don't know how tables stored in other files works for this kind of thing but I figured this might be it as the name seems to be explanatory--but then again it doesn't mean anything.

Format extensions: .sar and .sar.mat

First 8 bytes in hex; in ASCII:
Archive.sar - 73 61 72 20 E9 03 02 00 - sar é...
Archive.sar.mat - 18 00 00 00 90 3D 00 00 - .....=..

https://mega.nz/#!wqZCBbaK!6zoFlKhKZnmE9j_ar65cBMuYrlTshdv0CyZF6ouTRGs
https://mega.nz/#!UrhmkDLb!OA_Zqqc6BEZAIcDfXLHkWwvhK1dcE6O32Sn8FgRL9XA

**Comment by onepiecefreak3** [comment]
The extension suggests a sound archive. But then the other archive literally named sound... wouldn't make sense. I will try to find out if that file is helpful.

Also there isn't a standard of such tables. They're custom in most cases and where only needed on older consoles (like the DS in this case).

**Comment by onepiecefreak3** [comment]
I also finished a basic scanner now for this skana.dat archive. It gives back a tree of file offsets. So we at least now know where the files are stored.

**Comment by onepiecefreak3** [comment]
Archives.sar is an own archive type (a better signed one with that) but it doesn't map skana.dat. But Archive.sar has to be a plugin itself also. I will create an issue for that and drop skana.dat until this plugin is finished.

**Comment by onepiecefreak3** [comment]
This issue will be closed without a resolution. We're unable to provide any more research into this. We hope you found a solution or will find one with a reverse engineer more suited for this.
