### ISSUE TITLE
Chase cold case investigations .mes plugin request

### ISSUE THREAD

**Issue by CTPache** [IcySon55/Kuriimu#374]
Issue: [plugin request]
Console: 3ds
Format extension(s): .mes
Type: [text]
Game Name: chase cold case investigations

First 8 byte of file(s):
.mes - [47 53 41 4D 40 00 00 00] - [GSAM@...]

More details:
I have a program that makes the file into a txt and viceversa. each line in the txt is a dialoge box ingame.
each line follows the same structure:
SC02_AK000*Mr. Nanase, sir... Please do some<q>work...
SC02 is for the scene.
AK is the character who is speaking:
"AK": "Koto Amekura"
"NS": "Shounosuke Nanase"
"HG": "Genji Hisada"
"HS": "Suzu Hisada"
"KS": "Shunkichi Kouga"
"MT": "Tatsu Minami"
"SY":  "Yuuto Suemura"
"DUMMY_": No name
"UN": "?????"
the 000 is the time the character is speaking (000 for the first time, 001 for the second time...)
The output is after the '*'.

There are also 3 control codes:
<q> changes the output to the next line.
<PAGE> not sure what it does, but it shouldn't mind for making the plugin. Just leave it there (?).
<COLOR (RED, WHITE OR BLUE)> pretty self-explanatory, it changes the color of the text. in the game there are only those 3 colors. I don't know it could be used with other colors.
Sample files:
https://drive.google.com/file/d/1MtRtfOzGMtYmA1_Rj6aigWb1svyl1XJ9/view?usp=sharing

**Comment by onepiecefreak3** [comment]
I like how you didn't include sample files.

**Comment by onepiecefreak3** [comment]
Load for mes files is added. Save will follow up.
Just a hint. Even if parts of the file aren't directly connected to the text and the linked tool already does the job, if you want to know what the file consists of exactly you can look into the code.

It consists of 5 sections:
- Header with magic and section offsets
- a textEntry section, where each entry is 0x20 big consisting of offset and length for name and text of the entry. Name is ASCII and text UTF16 encoded
- a scenarioEntry section, with a count and offset into a later section, every entry is 0x8 big
- name and text section, what the name suggests it consist of the encoded names and texts
- a scenario section, it consists of offsets to textEntry section. It capsules the single texts/textEntries into scenarios

**Comment by onepiecefreak3** [comment]
Save added. Also for the single mes provided byte perfection was achieved.
I close this issue therefore.
