### ISSUE TITLE
.pac for ccci plugin request

### ISSUE THREAD

**Issue by CTPache** [IcySon55/Kuriimu#375]
Issue: [plugin request]
Console: 3ds
Format extension(s): .pac
Type: [archive]
Game Name: Chase cold case investigations

First 8 byte of file(s):
<.pac> - [44 47 4B 50 00 00 02 00] - [DGKP....]

More details:
It stores more files inside. Again, have the tool to open it and to rebuild it, but no source, sorry :/

Sample files and tools:
https://drive.google.com/open?id=1u7dJqdGTMXevZNHiE19T_7vN6hONSlz5

**Comment by onepiecefreak3** [comment]
Added Load and Save in newest commit.
