### ISSUE TITLE
Professor Layton and the Unwound Future .cimg and .limg

### ISSUE THREAD

**Issue by ghostfeesh** [IcySon55/Kuriimu#377]
Issue: plugin request
Console: NDS
Format extension(s): .cimg, .limg
Type: image
Game Name: Professor Layton and the Unwound Future

First 8 byte of file(s):
.cimg - 4C 49 4D 47 30 00 00 00 - LIMG0...
.limg - 4C 49 4D 47 30 00 00 00 - LIMG0...

More details:
.limg was extracted from LPC2 .cani
lz77 maybe

Sample files (if possible):
https://my.mixtape.moe/oqkosw.7z

**Comment by onepiecefreak3** [comment]
The image is by default compressed with LZ10.

**Comment by onepiecefreak3** [comment]
Since both image formats have the same magic, I assume they also have the same structure.
I will open a new issue regarding the LPC2 archive format. After that's finished, I can test more limg and even have more format support. But with that and the newest commits this issue can be closed.
