### ISSUE TITLE
Attack on Titan - Escape from Certain Death

### ISSUE THREAD

**Issue by Moonstriker** [IcySon55/Kuriimu#378]
Issue: Plugin Request
Console: 3DS
Format extension(s): .bin
Type: Text
Game Name: Shingeki no Kyojin: Shichi Kara no Dasshutsu

First 8 byte of file(s):
Hex: [20 20 00 00 00 00 00 00]

More details:
This is a request for a plugin for the various text files located in the game. 

Sample files (if possible):

**Comment by onepiecefreak3** [comment]
A plugin to load and save those various text files is already commited and was tested.
