### ISSUE TITLE
NDS A5I3 Translucent Texture

### ISSUE THREAD

**Issue by MetalFan1988** [IcySon55/Kuriimu#380]
Issue: [feature request] BPP A513 Texture Support
Console: NDS
Format extension(s): -
Type: [image]
Game Name: Metal Max 3

More details:
The game uses for some of its .TEX the format of Bpp A513. Please guys Add support for that.
All the info in: http://problemkaputt.de/gbatek.htm#ds3dtextureformats
**Format 6: A5I3 Translucent Texture (5bit Alpha, 3bit Color Index)**

Sample files (if possible):
ICON05.TEX
ICON108.TEX
https://mega.nz/#!YxQyyZRQ!SdC_dhSroIptkM8-BXs_GSW8G0BfLZVgb4uE8ocp88E

**Comment by onepiecefreak3** [comment]
Added a first version of the Imagefunctions to AlphaIndex.
It isn't guaranteed to work yet. Tests are following.

**Comment by onepiecefreak3** [comment]
Tests were successful on the provided images. Therefore closing the issue.
