### ISSUE TITLE
OutOfRangeException on Atlus Archive HPI_HPB for Etrian Odyssey Untold

### ISSUE THREAD

**Issue by XenesisXenon** [IcySon55/Kuriimu#382]
Issue: [bug report]
Console: 3DS
Format extension(s): HPI & HPB
Type: [archive]
Game Name: Etrian Odyssey Untold 00040000000EC700 (CTR-P-BSKE) (U)

First 8 byte of file(s):
MORI1R.HPI - 48 50 49 48 00 00 00 00 - HPIH 
MORI1R.HPB - 41 43 4D 50 34 05 00 00 - ACMP

More details:
App produces an System.ArgumentOutOfRangeException when opening Etrian Untold's HPB/HPI MORI1R Atlus Archive. Plugin works correctly for the Etrian Untold 2 and Etrian 5 versions of the Atlus Archive.

<img src="https://cdn.discordapp.com/attachments/389308092870819840/389308123820720129/Untitled.png"></img>

**Comment by onepiecefreak3** [comment]
Another check for the fileSize was added in the newest commit, which solved the outofrange exception.
