### ISSUE TITLE
Chibi-Robo (Game Cube) Extractor/Text Editor

### ISSUE THREAD

**Issue by SteveDoido** [IcySon55/Kuriimu#383]
Issue: plugin request
Console: GameCube
Format extension(s): .bin
Type: archive, text editor
Game Name: Chibi-Robo

First 8 byte of file(s):
bin - 55 AA 38 2D 00 00 00 20 - Uª8-... 

More details:
![image](https://user-images.githubusercontent.com/25571367/34074560-002c209e-e299-11e7-8cd6-3b75d77bd5a0.png)
The qp.bin file contains pretty much the entire game, including the text.
Would like to be able to translate it, so extracting it would be sweet.

Sample files (if possible):
https://mega.nz/#!P8F2UKjA!Uf6zWYjSsL6a5TH9tklOsrtqohNf_XTuwlJimb-Uy5w

**Comment by onepiecefreak3** [comment]
The qp.bin is a U8 archive. It is fully supported by Kuriimu2 Release 1.2.0. Issue closed.
