### ISSUE TITLE
.XI RGB565

### ISSUE THREAD

**Issue by Emalisha** [IcySon55/Kuriimu#385]
Issue: bug report
Console: 
Format extension(s): .xi
Type: image
Game Name: Inazuma Eleven Go Galaxy

Sample files (if possible):
https://cdn.discordapp.com/attachments/269221102029504512/395004233382100993/001.xi.png

**Comment by onepiecefreak3** [comment]
After looking through every other possible image encoding and again comparing all data, I'm rly sure that his image is completely normal like it is shown.
The table is normal, the image blocks were set correctly, and every other 16 bit image encoding threw out even more nonsense than RGB565.

**Comment by onepiecefreak3** [comment]
After some more discussion I will close this issue, cause the basic misunderstanding lies in the game engines mechanics and is therefore not related to this plugin or image encoding.
