### ISSUE TITLE
[Kuriimu] .cfg issue

### ISSUE THREAD

**Issue by AlePlumber** [IcySon55/Kuriimu#386]
Issue: bug report 
Console: 3ds
Format extension(s): .cfg
Type: text
Game Name: Inazuma Eleven GO: Galaxy

First 8 byte of file(s):

More details:
editing a file, save and when file is imported in the .fa and the game use this file i dont see any text but if after i extract the file from the edited .fa i see the file with the same data of before to import :( 
and i need it to translate the game...

Sample files (if possible):
https://drive.google.com/open?id=1JPBKoj87CF74YNFbLPmlPpfOeZCScEgg

**Comment by onepiecefreak3** [comment]
That could be a question of how you injected the text file back.
You see the apps don't work quite together. If you edited the .cfg you have to save them somewhere on your pc (maybe the Desktop) and manually reinject this cfg in the fa.
You can't open the .cfg from the opened archive in Karameru, save it and expect it to be in the archive then. That's NOT how it works. I will look into the files either way, but I think that might the problem of understanding here.

**Comment by onepiecefreak3** [comment]
I confirmed that the save routine for this fily type works byte perfect. So might really just don't have reinjected the file correctly.
I will leave this issue open for another 2-3 days.
Just comment here if you have other questions or just write that it worked now and I will close it asap.
