### ISSUE TITLE
Unable to save 3DS Virtual Console banner

### ISSUE THREAD

**Issue by AyanamiRei1** [IcySon55/Kuriimu#388]
Issue: bug report
Console: Nintendo 3DS
Format extension(s): .cgfx
Type: image
Game Name: Virtual Console

First 8 byte of file(s):
.cgfx - [43 47 46 58 FF FE 14 00 00] - [CGFXÿþ...]

More details:
I wanted to see if Kukkii could save the GBC Virtual Console banner but this is the error I get even if I don't edit anything.
![ryzjvbs](https://user-images.githubusercontent.com/25233407/34476068-eddb02d0-ef85-11e7-9734-9133d938cffc.png)

Sample files (if possible):
https://drive.google.com/open?id=1W79_7_rKTruonxZ0yZK7hH0Cc08C_QzC

**Comment by Spmario233** [comment]
You can use Kuriimu 1.0.9.

**Comment by AyanamiRei1** [comment]
I need the ability to edit all 3 cart images Kuriimu 1.0.9 doesn't have that.

**Comment by onepiecefreak3** [comment]
In the newest commit this behaviour is now revised and solved.
Mipmap support, in-place-saving and the size check was revised also. You can either build the newest version yourself with VS or wait for a new release (don't ask me when it comes out)
