### ISSUE TITLE
[Bug report] Glitched XI pictures

### ISSUE THREAD

**Issue by HucetJ** [IcySon55/Kuriimu#389]
Issue: [bug report]
Console: Nintendo 3DS
Format extension(s): .xi
Type: image
Game Name: 
Yo-kai Watch Busters 1
Yo-kai Watch 3

Software used: Kuriimu v1.0.10 and previous releases.

More details:
Please find a lot of .xi files giving a glitch result when exporting to .png. A very very few of them work. The files in the .zip file represent 5% of the total pictures both games have to offer. The remaining 95% are fine.

Sample files:
[https://drive.google.com/file/d/1MKujbbNW4m_jkGJD0W2v6xGuw_yf-PgD/view?usp=sharing](url)

Thank you.

**Comment by onepiecefreak3** [comment]
The image mode 0x1b was mapped to A4 out of speculations, we had yet to confirm. It is actually ETC1 which was now changed in the newest commit. Compile the plugin/program yourself or wait for the next release (don't ask me when)
