### ISSUE TITLE
.gds files in Professor Layton and the Curious Village

### ISSUE THREAD

**Issue by Timmerito** [IcySon55/Kuriimu#391]
Issue: Plugin request
Console: Nintendo DS
Format extension(s): .gds
Type: text
Game Name: Professor Layton and the Curious Village

First 8 byte of file(s):
gds - AC 1D 00 00 00 00 DC 00 - ¬.....Ü

More details:
It has a bunch of text with some Ü's and dots. All the script files with text are in the rar file, the one with the info from above is qscript.gds

Sample files (if possible):
https://mega.nz/#!RYg1lJwS!ll5obGIPeTYgBOx9_qsMIiPSu_C0n72sh0-zQa4ek98

**Comment by onepiecefreak3** [comment]
Save/Load for GDS added in newest commit.
Issue closed.
