### ISSUE TITLE
batch export/import bug

### ISSUE THREAD

**Issue by AlePlumber** [IcySon55/Kuriimu#393]
Issue: Bug report
Console: 3DS
Format extension(s): .xi
Type: image
Game Name: Inazuma Eleven Go Galaxy: Supernova/Big Bang

First 8 byte of file(s):

More details:
doing a batch import i have some errors, here you have the error log of kukki:

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\wkp0026_ja.xi
System.IO.EndOfStreamException: No se puede leer más allá del final de la secuencia.
   en System.IO.__Error.EndOfFile()
   en System.IO.BinaryReader.ReadByte()
   en image_level5.imgc.IMGC.Order(MemoryStream tableStream, MemoryStream texStream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\whd0008_ja.xi
System.ArgumentOutOfRangeException: Se necesita un número no negativo.
Nombre del parámetro: count
   en System.IO.BinaryReader.ReadBytes(Int32 count)
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\vka0039_ja.xi
System.NotSupportedException: Unknown compression method 6
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\000000_ja.xi
System.NotSupportedException: Unknown compression method -4
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\wic1004_ja.xi
System.IO.EndOfStreamException: No se puede leer más allá del final de la secuencia.
   en System.IO.__Error.EndOfFile()
   en System.IO.BinaryReader.ReadByte()
   en image_level5.imgc.IMGC.Order(MemoryStream tableStream, MemoryStream texStream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\wsp0043_ja.xi
System.IO.EndOfStreamException: No se puede leer más allá del final de la secuencia.
   en System.IO.__Error.EndOfFile()
   en System.IO.BinaryReader.ReadByte()
   en image_level5.imgc.IMGC.Order(MemoryStream tableStream, MemoryStream texStream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\wsp0042_ja.xi
System.Exception: Stream too short!
   en Kontract.Compression.LZ10.Decompress(Stream instream, Int32 decompressedSize)
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\wkp0061_ja.xi
System.Exception: Stream too short!
   en Kontract.Compression.LZ10.Decompress(Stream instream, Int32 decompressedSize)
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\whs0049_ja.xi
System.NotSupportedException: Unknown compression method -1
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\whs0016_ja.xi
System.Exception: Stream too short!
   en Kontract.Compression.LZ10.Decompress(Stream instream, Int32 decompressedSize)
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\whs0009_ja.xi
System.NotSupportedException: Unknown compression method 6
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\whs0002_ja.xi
System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en Kontract.Compression.Huffman.Decompress(Stream input, Int32 num_bits, Int64 decompressedLength, ByteOrder byteOrder)
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\whp0051_ja.xi
System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en Kontract.Compression.Huffman.Decompress(Stream input, Int32 num_bits, Int64 decompressedLength, ByteOrder byteOrder)
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\whp0046_ja.xi
System.IO.EndOfStreamException: No se puede leer más allá del final de la secuencia.
   en System.IO.__Error.EndOfFile()
   en System.IO.BinaryReader.ReadByte()
   en image_level5.imgc.IMGC.Order(MemoryStream tableStream, MemoryStream texStream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\wkp0059_ja.xi
System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en Kontract.Compression.Huffman.Decompress(Stream input, Int32 num_bits, Int64 decompressedLength, ByteOrder byteOrder)
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\wht0012_ja.xi
System.IO.EndOfStreamException: No se puede leer más allá del final de la secuencia.
   en System.IO.__Error.EndOfFile()
   en System.IO.BinaryReader.ReadByte()
   en Kontract.Compression.RLE.Decompress(Stream instream, Int64 decompressedLength)
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

C:\Users\Ale_z_plumber\Desktop\mini rpueba\skill_mini_xb\whk9999_ja.xi
System.Exception: Stream too short!
   en Kontract.Compression.LZ10.Decompress(Stream instream, Int32 decompressedSize)
   en Kontract.Compression.Level5.Decompress(Stream stream)
   en image_level5.imgc.IMGC..ctor(Stream input)
   en image_level5.imgc.ImgcAdapter.Load(String filename)
   en Kukkii.Converter.BatchExportPNGTask(String file, Int32& count, Int32& exported, ConcurrentBag`1& errors)

Sample files (if possible):
https://drive.google.com/file/d/12RvG6Ju-cNUNRmKKZhpNNShEA1f8BLa9/view?usp=sharing

**Comment by onepiecefreak3** [comment]
The static variables in all image plugins were fixed as far as possible, therefore making the batch process safe-to-use again and eliminated the errors.
