### ISSUE TITLE
.PCK error

### ISSUE THREAD

**Issue by DarthManto** [IcySon55/Kuriimu#394]
Issue: [bug report]
Console: 3DS
Format extension(s): .pck
Type: [archive]
Game Name: Inazuma Eleven Go Galaxy: Supernova

More details:
When I try to decompress this file it refuses to open it and just makes Karameru stop responding. I've had 3 others test this and the same thing happens to them.

Sample files (if possible):
https://mega.nz/#!VTxQVQ7Z!6reBLYH5KRyUQ4iGTZcbeJiIN7V0hBiJYtlBcxkBJlk

**Comment by DarthManto** [comment]
First 8 byte of file(s):
58 50 43 4B 17 50 05 00 4A - XPCK↨P♣.J

**Comment by onepiecefreak3** [comment]
The PCK plugin Identify function thought these archives were normal PCK's. But internally they were XPCK's. Therefore the PCK Identification was made more stable and the named archives are now loadable is usual.
Therefore issue closed.
