### ISSUE TITLE
Kirby Triple Deluxe (3DS) Text Editor [Plugin Request]

### ISSUE THREAD

**Issue by SteveDoido** [IcySon55/Kuriimu#395]
Issue: plugin request
Console: 3DS
Format extension(s): msbt
Type: text
Game Name: Kirby Triple Deluxe

First 8 byte of file(s):
msbt - 4D 73 67 53 74 64 42 6E - MsgStdBn

More details:
The text for Kirby Triple Deluxe has some interesting commands for text size, placement, and so on.
In order to make a translation, it's invaluable to have those properly understood.

Sample files (if possible):
https://mega.nz/#!6gUlWIrR!vNCAZ3xuFM0Co0xsi96y9BlFnTny2MIyiwWNOO9tEWA

**Comment by onepiecefreak3** [comment]
A game plugin is written now which interprets most binary code as somekind of control code in <>.
The game plugin features coloring text with the control code <Color 0xFFFFFFFF>, where 0xFFFFFFFF is the hexadecimal representation of the RGBA color code.
-> https://www.hexcolortool.com

It also deffers between these colors, icons and other control codes, whatever they could mean. 3 icons could already be named.

Now it's up to you, to name these control codes yourself further. I hereby close this issue.
