### ISSUE TITLE
Karameru - Saving Archive not successful

### ISSUE THREAD

**Issue by Insighter2k** [IcySon55/Kuriimu#397]
Issue: BUG REPORT
Console: 3DS
Format extension(s): .FA
Type: archive
Game Name:  Inazuma Eleven - Any Game - Here: GO Light

First 8 bytes of the file(s):
.FA - 4152433048 - ARC0H

More details:
![image](https://user-images.githubusercontent.com/28791491/35217320-0b7cbb18-ff6b-11e7-8810-285d7ed2d384.png)

After changing files and pushing the save button, the error occurs and the changes won't be saved.
Damaged since 1.06.

Sample files (if possible):
1 GB, too big.

**Comment by onepiecefreak3** [comment]
This issue is not reproducable in Kuriimu2's ARC0 plugin. Issue closed.
