### ISSUE TITLE
Metal Max 4 Pack container

### ISSUE THREAD

**Issue by MetalFan1988** [IcySon55/Kuriimu#398]
Issue: [plugin request]
Console: N3DS
Format extension(s): It has no extension. 
Type: [image | archive]
Game Name: Metal Max 4

First 8 bytes of the file(s):
<No> - [DF1A000086700100] - [ß]

More details:
The name of the file is just pack without extension. It seems to be a container for different types of formats. For example the example pack  is full of CGFX files that are compressed with LZ11. Around 6800 of them. 
I have managed to extract some manually and I can see them in Kukkii but they are too many to work with in that way. You could please review it and give support to this packer format.

Sample files (if possible):
http://rgho.st/8V8YGmb4X

**Comment by onepiecefreak3** [comment]
Support for this format was added in the newest dev build and upcoming Release 1.2.1 of Kuriimu2.
This is a manual plugin, this means you have to select the plugin to load this file format. Select "PACK" under "plugin_cattle_call.dll" to load this format.
Unrelated to the format: In addition to this plugin I also added support for compressed F3XT. Those do not have to be decompressed beforehand anymore and get handled automatically by the F3XT plugin from now on.
