### ISSUE TITLE
.json parser for kid icarus

### ISSUE THREAD

**Issue by M-1-RLG** [IcySon55/Kuriimu#399]
onepiecefreak said to put this here as a reminder.

Issue: request
Console: 3DS
Format extension(s): .json
Type: text
Game Name: Kid Icarus: Uprising

First 8 bytes of the file(s):
.json - 50 53 4C 42 01 00 00 00 - PSLB....

More details:
Need a parser so I can see weapons data better, such as homing attack, and power and such.

https://cdn.discordapp.com/attachments/405305196307152897/405305221011603456/00.json 
https://cdn.discordapp.com/attachments/405305196307152897/405305225159901184/03.json

**Comment by onepiecefreak3** [comment]
A parser is mostly finished. Only a bit of human-readability is missing and nested arrays don't have yet a name.

**Comment by onepiecefreak3** [comment]
https://github.com/onepiecefreak3/Kid-Icarus-JSON-Parser/releases/tag/1.0
Here you have it.
Please be aware it doesn't import the json back into the game's format. It's currently solely for looking into the data as a human-readable JSON.

**Comment by onepiecefreak3** [comment]
@M-1-RLG 
https://github.com/onepiecefreak3/Kid-Icarus-JSON-Parser/releases/tag/1.1
This version now adds import possibility.
Would be nice if you could test it ingame, so I know if what my tool imports is valid data for the game.
I will close this sissue in a few days if you don't respond then.

**Comment by onepiecefreak3** [comment]
https://github.com/onepiecefreak3/Kid-Icarus-JSON-Parser/releases/tag/1.2
This release allows 1:1 import now. It isn't comptible with earlier exported JSON's so don't use them anymore and export them anew.
Now that 1:1 Import is possible without changes, this issue can be closed.
