### ISSUE TITLE
Mario Maker 3DS bin files

### ISSUE THREAD

**Issue by AyanamiRei1** [IcySon55/Kuriimu#404]
Issue: {feature request]
Console: Nintendo 3DS
Format extension(s): .bin
Type: [Archive}
Game Name: Super Mario Maker for Nintendo 3DS

First 8 bytes of the file(s):
.bin - [9C 15 00 00 5C 00 10 00 00] - [œ...\....]

More details:
Mario Maker 3DS has a bunch of bin files that contain CTPK's currently Karameru cannot open them. These bin files contain all the enemy models that the game loads if they were extracted Kukkii can open the CTPK's

Sample files (if possible):
https://drive.google.com/open?id=1GbMCBJinHDbhnjEyrX5lBhwC1M58zZyb

Note this isn't the only one there are over 40 of these bin files and they all contain CTPK's

**Comment by IcySon55** [comment]
All done!
