### ISSUE TITLE
Ace Attorney DD/SOJ Android tex files

### ISSUE THREAD

**Issue by CTPache** [IcySon55/Kuriimu#405]
Issue: plugin request
Console: Android
Format extension(s): .tex
Type: image
Game Name: Ace Attorney Dual Destinies/Spirit of Justice 

First 8 bytes of the file(s):
.tex [54 45 58 20 09 00 01 20] [TEX 	  ]

More details:
The 3ds version of the format works but this one doesn't.

Sample files (if possible):
https://drive.google.com/open?id=12h62Dd17GNepqG3OyXyTElBAGg4A-JBR

**Comment by onepiecefreak3** [comment]
This bug is not reproducable in the port of the MTEX plugin in Kuriimu2. The plugin already exists in Release 1.2.0 of Kuriimu2.
Issue closed.
