### ISSUE TITLE
Cant insert files into .FA with beta release

### ISSUE THREAD

**Issue by supersonic29** [IcySon55/Kuriimu#406]
Issue: bug report
Console: Karameru v1.0.11-1338f49
Format extension(s): .FA / .XI / .XS
Type: archive
Game Name: Professor Layton vs Ace Attorney

First 8 bytes of the file(s):
I'll be honest, this is greek to me.  Happy to turn over any files though.

More details:
If I replace files inside the .FA extracted from the game, I get the error at the following link.  Tested with an edited version of the file stored at vs1.fa/img/evt_010040.xi

Sample files (if possible):
https://imgur.com/a/1Tjrt

**Comment by onepiecefreak3** [comment]
Need the original and edited xi.

**Comment by supersonic29** [comment]
https://drive.google.com/open?id=19z76YlY0fQxSfXHEppX61x0nlXtiKcga
https://drive.google.com/open?id=1y9jrtdUN-M14JT4DPHiY0vzHb6GwdOYr

(Edited one only has a different filename for this upload, was the same as the other when I replaced)

**Comment by onepiecefreak3** [comment]
Solved with newest commit.
