### ISSUE TITLE
plugin request Dragon Ball Heroes 

### ISSUE THREAD

**Issue by agemo999** [IcySon55/Kuriimu#409]
Issue: plugin request
Console:  3DS
Format extension(s): bin  
Type: archive]
Game Name: 

First 8 bytes of the file(s):
<extension> -33 44 53 2D 4C 5A 0D 0A 11 53 71 05 00 42 43 53- 3DS-LZ...Sq..BCS
More details:
these are the filearc of the game, I am able to extract them using quickbms and this script
http://www51.zippyshare.com/v/2ALYuvp9/file.html 
but I am unable to repack them, If a plugin could be made, afaik it uses lz77wii compression

Sample files (if possible):
http://www51.zippyshare.com/v/cMXzIcUj/file.html

**Comment by onepiecefreak3** [comment]
Why didn't you mention a game. Do that please before we work on the issue.

**Comment by agemo999** [comment]
Sorry it's for ultimate mission x of dragon ball heroes

**Comment by IcySon55** [comment]
@onepiecefreak3 I've started on this already, the plugin will be ready pretty soon.

**Comment by onepiecefreak3** [comment]
This is fully supported in Kuriimu2's newest dev build and Release 1.2.0.
Issue closed.
