### ISSUE TITLE
Level-5 .fa Last Specter

### ISSUE THREAD

**Issue by Poyokorin** [IcySon55/Kuriimu#411]
Issue: [plugin request]
Console: NDS
Format extension(s): .fa
Type: [archive]
Game Name: Professor Layton and the Last Specter

First 8 bytes of the file(s):
.fa - 47 46 53 41 28 00 00 00 - GFSA(...

More details:
NDS version of .fa, different from XFSA of 3DS

Sample files (if possible):
https://my.mixtape.moe/smkrwc.zip

**Comment by Timmerito** [comment]
I second this! But your link to the sample file doesn't work so i think that you need to reupload that.

**Comment by onepiecefreak3** [comment]
This is supported in Kuriimu2's newest dev build and Release 1.2.0. Please refer to Kuriimu2 if there are any errors, that you encounter. Issue closed.
