### ISSUE TITLE
Extracting textures

### ISSUE THREAD

**Issue by MaximusX800** [IcySon55/Kuriimu#412]
Issue: Unable to properly extract texture files
Console: Android OS
Format extension(s):  .tex
Type: image
Game Name: Monster Hunter Stories [Android]

First 8 bytes of the file(s):
TEX - 54 45 58 20 09 00 01 20 - [TEX ... ]

More details:
N/A

Sample files (if possible):
https://drive.google.com/file/d/177tAi9-qi69H6u69i9KMRcPqdS4Unlk8/view?usp=sharing

**Comment by onepiecefreak3** [comment]
Issue cannot be reproduced with the MTTex plugin Kuriimu2. Please refer to its github for further bug reports on this format.
Issue closed.
