### ISSUE TITLE
Issues with compressed Mobile MT Framework TEXs

### ISSUE THREAD

**Issue by an-error42** [IcySon55/Kuriimu#416]
Issue: Bug report
Console: Android (Mobile)
Format extension(s): `.tex`
Type: Image
Game Name: The Great Ace Attorney (Dai Gyakuten Saiban | 大逆転裁判)

Kukkii produces non-meaningful images while trying to decompress textures that are ETC1 or PVRTC compressed.
I'll walkthrough each one. Please note that the issue is how Kukkii handles raw data and not the container.

## ETC1

Trying to decompress an ETC1-compressed texture will result in a garbled mess.

### Example
The texture of the cabin here.

* Raw data: [Mega Link](https://mega.nz/#!6ZIzwbTY!39QGpbN-bX-O2bML2QIbWfYta41zyKARv3RSXIcaBOA).
* Decompressed with PVRTexTool as ETC1: [PVRTexTool Result](https://s31.postimg.org/j1n9v40ej/raw_cabin.ETC1.PVRTEXTOOL.png).
* Decompressed with Kukkii as ETC1: [Kukkii Result](https://s31.postimg.org/my0lr40tn/raw_cabin.ETC1.KUKKIIL.png).

Trying to decompress a 3DS texture that's ETC1 compressed now **makes Kukkii produces correct result but garbage with PVRTexTool.**

* Decompressed with PVRTexTool as ETC1: [PVRTexTool Result](https://s31.postimg.org/lyaavaqrv/item0_03_00_0_BM_NOMIP.ETC1.PVRTEXTOOL.png).
* Decompressed with Kukkii as ETC1: [Kukkii Result](https://s31.postimg.org/i1wyzbl7v/item0_03_00_0_BM_NOMIP.ETC1.KUKKII.png).

## PVRTC

Same as ETC1 case, Kukkii also fails to decompress the image and produces garbled mess instead.

### Example

The texture of the shoutouts (all of them).

* Raw data: [Mega Link](https://mega.nz/#!OZYEkDSA!A4Ronkazjq2AYHV6-f2b1EfxyI5FhrbkV4lL3B9x7Jw).
* Decompressed with PVRTexTool as PVRTC: [PVRTexTool Result](https://s31.postimg.org/v4sliddy3/246_-_0x183ba2bb.PVRTC.PVRTEXTOOL.png).
* Decompressed with Kukkii as PVRTC: [Kukkii Result](https://s31.postimg.org/5m095hzkr/246_-_0x183ba2bb.PVRTC.KUKKII.png).

Interestingly, treating this as DXT4 with PVRTexTool will produce [the following image](https://s31.postimg.org/hnvmzptej/246_-_0x183ba2bb.DXT4.PVRTEXTOOL.png).

**Comment by IcySon55** [comment]
As I recall, our PVRTC support was never completed and @onepiecefreak3 was working on it before but will be busy for a while. Thanks for the bug report and samples.

**Comment by adibsurani** [comment]
The ETC1 issue is known. Our ETC1 encoder/decoder assumes the 3DS variant of ETC1, that is, 8 bytes are read as LE (the [official specs] say BE). Also the 3DS version has a different swizzle to the official specs.

The recommended fix is to modify our ETC1 class to be standard-compliant, then have a 3DSETC1 wrapper around it. This wrapper will merely change the order of input bytes and output pixels; the internal encoder and decoder will all remain the same.

**Comment by onepiecefreak3** [comment]
Problem with PVRTC and ETC1 solved, and all given files are openable now. Issue closed.
