### ISSUE TITLE
Monster Hunter XX (SW) TEX Files

### ISSUE THREAD

**Issue by Deathmaw** [IcySon55/Kuriimu#417]
Issue: Plugin Request
Console: Switch
Format extension(s): .tex
Type: Image
Game Name: Monster Hunter XX

First 8 bytes of the file(s):
.tex - [54 45 58 00 A0 80 00 20] - [TEX.... ]

More details:
Don't really have much to add, just be nice to see support.

Sample files (if possible):
https://mega.nz/#!Yxw0zJyK!CA7p5sb2Hqv3sLi2emHZHZ8ZmM3cghnrHw6uG4pvI6M

**Comment by piratesephiroth** [comment]
yeah it seems their format is slightly different from the ones on the 3DS.
The Scarlet tool can't convert it either and says it's "Capcom TEX Format 0x17".

**Comment by onepiecefreak3** [comment]
The provided images are supported now. There are more image formats not yet supported, since we don't know their format value. If you encounter such formats open a new issue providing the problematic files.
