### ISSUE TITLE
Danganronpa V3 (srd Files)

### ISSUE THREAD

**Issue by EmuPlays** [IcySon55/Kuriimu#418]
Issue: plugin request
Console: PC
Format extension(s): .srd
Type: compressed images in a single file
Game Name:  Danganronpa V3: Killing Harmony

First 8 bytes of the file(s):
.srd - 24 43 46 48 00 00 00 00 00 - $CFH.....

Sample files (if possible):
srd File: https://drive.google.com/open?id=1-Vnsb4SyQA_k83l7ZERtPnWkL_Dj0wJm
Unpacked srd: https://drive.google.com/open?id=1_uPOB1E21FpCYcOMx1VtF771DZ8XESTb
(SPC File: https://drive.google.com/open?id=1R4kxNdK8PVZkh04qjfZHECrC_1rKyP-J)
(Unpacked SPC: https://drive.google.com/open?id=1ddkUucKx4csE0UNi0K-RF9R-U8x90RVj)

**Comment by onepiecefreak3** [comment]
The newest dev build and upcoming Release 1.2.1 of Kuriimu2 can open and edit SPC archives. With this done, I will continue my work on SRD texture archives now.

**Comment by onepiecefreak3** [comment]
The newest dev build and upcoming Release 1.2.1 of Kuriimu2 can open and edit SRD image resources.
It should be able to automatically detect the file format no matter if you drag the .srd or .srdv file on Kuriimu2.

With this, the issue can be closed. For future bug reports or requests on those formats, refer to the Kuriimu2 github.

**Comment by Nagitoo21** [comment]
@onepiecefreak3 hi bro I didnt see srd or srdv function on kurimu2 also it doesnt detect automaticly my srdv files.Are you sure about that realy added at 1.2.1 or you guys cencelled it? If i am doing something wrong can you cominucate with me on discord its important for meand i am still nab ty.... HououinKoyma#4004
