### ISSUE TITLE
Font editor

### ISSUE THREAD

**Issue by AlePlumber** [IcySon55/Kuriimu#419]
Issue: [plugin request | bug report | feature request]
Console: 3ds
Format extension(s): .fnt
Type: text
Game Name: all

More details:
When you have free time, can you create a font editor to add to the game more symbols like á é í ó ú ¿ ¡
scepecially for japaneese games.  (or give kuriimu the necessary plugins to do it)

**Comment by onepiecefreak3** [comment]
https://github.com/onepiecefreak3/XFontEditor/releases
This should make you able to edit most stuff in the font and put it back to the game.
