### ISSUE TITLE
GioGio's Bizarre Adventure [plugin request] tm2/pzz

### ISSUE THREAD

**Issue by num421337** [IcySon55/Kuriimu#421]
[plugin request]
Console: PS2
Format extension(s): .PZZ .TM2
Type: image/archive
Game Name: GioGio's Bizarre Adventure

First 8 bytes of the file(s):
<.pzz> - [0C 00 00 00 03 00 00 80 03] - 
<.tm2> - [54 49 4D 32 04 01 01 00 03 ] - [TIM2  ]

Sample files (if possible):
https://mega.nz/#F!0NphVIoY!TQ-y_b_1U3Zww2OOJFdFpw   mostly .pzz's but there are tim2 files inside them as noted by multiple TIM2 sections in each of the provided .pzz files. I took one section of the TIM2 code and saved it as a tm2 file to look at. I asked a few people who dealt with TIM2 files before and they said it is most likely that they are compressed in some way. I assume inside the .pzz files.

**Comment by num421337** [comment]
Some of the files contain uncompressed, useable tim2 files that were able to be opened and edited using Game Graphics Studio - specifically these files https://mega.nz/#F!9JwRmQhC!IOfERcHb8SsX6vDc_x_NkQ

**Comment by onepiecefreak3** [comment]
As with issue #355 this will no longer be done by us, due to existing scripts for all the mentioned file formats. We may deal with TIM2 at a later point however.
