### ISSUE TITLE
PCK Archive Plugin

### ISSUE THREAD

**Issue by AlternativeZero** [IcySon55/Kuriimu#424]
Issue: plugin request
Console: PlayStation Vita
Format extension(s): .pck
Type: archive
Game Name: Dungeon Travelers 2

First 8 bytes of the file(s):
.pck - 46 69 6C 65 6E 61 6D 65 - Filename

More details:
This isn't a new format but I couldn't find any tools to extract and repack this particular version of it as it contains images instead of music files alongside from what I understand a different structure compared to the other ones out there. 

Sample files (if possible):
https://drive.google.com/open?id=1rOrJIpO3GlvRxoqHl5PpIWZVdrHFEQLl

**Comment by onepiecefreak3** [comment]
This is the same format as in duplicate issue #429 for game "Utawarerumono: Mask of Deception". The sample from issue #429 can be used here as well for further research.

**Comment by onepiecefreak3** [comment]
Both mentioned games were (co-)developed by Sting Entertainment.
A plugin that can open this archive format was added to the newest dev build and upcoming Release 1.2.1 of Kuriimu2.
The format can be automatically identified and opened.
