### ISSUE TITLE
TEX Image Plugin

### ISSUE THREAD

**Issue by AlternativeZero** [IcySon55/Kuriimu#425]
Issue: plugin request
Console: PlayStation Vita
Format extension(s): .tex
Type: image
Game Name: Dungeon Travelers 2

First 8 bytes of the file(s):
.tex - 54 65 78 74 75 72 65 20 - Texture 

More details:
It's the image files used in DT2 on the Vita and PSP which no available editors can open.

Sample files (if possible):
https://drive.google.com/open?id=1qth-GTFMMoDao9HSfEkiWfDL1co6AmSx

**Comment by onepiecefreak3** [comment]
This plugin employs different ways to store images. Texture's can contain standard PNG, or raw image data compressed with a variation of LZ77. The plugin can currently load PNG-type Textures, but it currently cannot decompress the LZ77 variant, becaue it needs to be reverse-engineered first.

**Comment by onepiecefreak3** [comment]
The newest dev build and upcoming Release 1.2.1 of Kuriimu2 can now fully support this format.
It can be automatically detected, so you can just drag'n'drop the file or open it via File > Open.
For any future feature requests or bug reports regarding this format, please refer to the Kutiimu2 github.
