### ISSUE TITLE
SDAT Archive Plugin

### ISSUE THREAD

**Issue by AlternativeZero** [IcySon55/Kuriimu#429]
Issue: plugin request
Console: PlayStation Vita
Format extension(s): .sdat
Type: archive
Game Name: Utawarerumono: Mask of Deception

First 8 bytes of the file(s):
.sdat - 46 69 6C 65 6E 61 6D 65 - Filename

More details:
It's the archive used throughout Utawarerumono: Mask of Deception and Utawarerumono: Mask of Truth for various things from images to in-game models.

Sample files (if possible):
https://drive.google.com/open?id=1Rd4Ej2AP8JNPl1giEDtHEvo0-81TMXR1

**Comment by onepiecefreak3** [comment]
This seems to be similar to issue #424 judging by the first 8 bytes and content. I will refer to the game information in this issue there, mark this as duplicate, and close it.

**Comment by onepiecefreak3** [comment]
This format was (co-)developed by Sting Entertainment. It seems that Sting Entertainment was the developer for the engine/designer of the file formats. They are only mentioned as foot notes in this games developement, but were the main developer of Dungeon Travelers 2, which uses the same file formats.
Therefore plugins that can support this format are found under "plugin_sting_entertainment.dll". The formats are autmatically identified however.
