### ISSUE TITLE
G1T image plugin support

### ISSUE THREAD

**Issue by juliosueiras** [IcySon55/Kuriimu#433]
Issue: G1T Image support
Console: Vita
Format extension(s): g1t
Type: image
Game Name: 
Atelier series

First 8 bytes of the file(s):
.g1t - 47 54 31 47 30 36 30 30 - GT1G0600

More details:
bms code to convert g1t to dds: https://pastebin.com/3g1GVtpg

Sample files (if possible):

**Comment by juliosueiras** [comment]
Sample File:
https://nofile.io/f/BnGfjHbGW5d/MainFont_HD544_vita_0.g1t

**Comment by onepiecefreak3** [comment]
Save/Load for G1T added in latest commit. Open another issue with maybe unsupported formats (which will exist) and this time provide more sample files with a larger variaty.

**Comment by by-freon** [comment]
Hello.
You have managed to find out the form of dds texture in a file
MainFont_HD544_vita_0.g1t?

**Comment by onepiecefreak3** [comment]
I'm surprised you expect someone to answer to a closed issue.
If you need to ask how to use this tool, this tool may not be for you.
