### ISSUE TITLE
.fa dont open

### ISSUE THREAD

**Issue by AlePlumber** [IcySon55/Kuriimu#434]
Issue: [plugin request | bug report | feature request]
Console: 
Format extension(s): 
Type: archive
Game Name:  Inazuma Eleven 3 Bomb Blast

First 8 bytes of the file(s):
.fa

More details:
trying to open the only .fa files from this game karameru crash with this error:
System.IndexOutRangeException: 
en archive_level5.B123.B123.GetFileNames(Byte  name part)
en archive_level5.B123.B123..ctor(Stream input)
en archive_level5.B123.B123.FaManager.Load(String filename)
en Karameru.Manager.OpenFile(StringFilename)

**Comment by onepiecefreak3** [comment]
Fixed in newest commit.
