### ISSUE TITLE
ECD (LZECD) decompression bug

### ISSUE THREAD

**Issue by auramagi** [IcySon55/Kuriimu#438]
Issue: bug report
Console: 3DS
Format extension(s): ecd, srtux
Type: archive
Game Name: 3DS1736 - Kanken Training 2 (Japan)

First 8 bytes of the file(s):
45 43 44 01 00 00 00 08 - ECD\x01\x00\x00\x00\x08

More details:
ECD compressed file inside SRTUX archive.
Existing implementation works incorrectly after 1024 bytes of compressed data, because when decompressing it copies from offset points starting from the beginning of decompressed data.
The correct version is to make 0-filled 1024-byte buffer to copy from, and fill it with decompressed bytes at (position mod 1024). Thus, copying bytes from this buffer at (offset mod 1024) results in valid data.
I can't code in c#, but i've made a small python script that correctly decompresses the file.
https://gist.github.com/auramagi/c194c97143f6b68b069c29cae5f31d8c

Compressed ECD sample file:
https://drive.google.com/file/d/1gCJTJmTa0buOYLM3mkHS-qgEo9sjJ5_M/view?usp=sharing

**Comment by onepiecefreak3** [comment]
Fixed in the ported version in Kuriimu2, additionally to having reverse engineered the game executable to get every last detail out of this compression scheme. It led to some major changes to the buffering.
