### ISSUE TITLE
CVM File Compression/ROFS Encryption (PS2)

### ISSUE THREAD

**Issue by SteveDoido** [IcySon55/Kuriimu#439]
Issue: plugin request
Console: PS2
Format extension(s): CVM
Type: archive
Game Name: Sakura Wars 5 (among others)

First 8 bytes of the file(s):
.cvm - 43 56 4D 48 00 00 00 00 - CVMH....

More details:
Some PS2 games (in this case, Sakura Wars 5) use the CVM file format to store the games files.
It is fully encrypted, and a few games actually did get their passwords uncovered (list below).
Russian: http://www.emu-land.net/forum/index.php?topic=76737.0
Portuguese: http://www.romhacking.net.br/index.php?topic=367.0

Files:
Disc Stuff: http://www.mediafire.com/file/qh8lrg8t7c0jqc1/STF.7z
Layer 1: http://www.mediafire.com/file/nwvgzc2nwxstvtr/LAYER0.7z
Layer 2: http://www.mediafire.com/file/ziiwhpcasslh91z/LAYER1.7z

**Comment by onepiecefreak3** [comment]
The original xentax forum post is way more helpful than russian or portugeuse: https://forum.xentax.com/viewtopic.php?f=21&t=2776&hilit

It seems that the ROFS format is a format by CRI Middleware (criware for short) and allows encryption by an algorithm with a given string password. This password is unique to the game/developer.

Excerpt from the xentax forum post: The password can usually be found in the binary next to the CVM filename, or strings like "VOL", "ROFS" or "ADXF_AddRofsVol".
So the possibility exists that the password is easily accessible by looking into the executable at the mentioned positions.

The linked xentax forum post also contains a link to a tool that can decrypt the file, given the correct password. Reversing the tool should give easier access to the algorithm used to decrypt. Even easier if the tools source code is known.

**Comment by onepiecefreak3** [comment]
Also the password for this game was already uncovered, as seen in the links provided by OP. The password for Sakura Wars V is "itinenmotanai". The provided tool in the xentax forum post can do said decryption already. Therefore this issue has a lower priority until stated otherwise.

**Comment by onepiecefreak3** [comment]
Decryption and encryption of the archive is properly supported now. The upcoming CVM plugin is also able to detect the password used for a given CVM, IF the password is already in the plugins password lookup.
This means, that if the password for a game was not uncovered yet (basically, wasn't in the lists provided by the links in OP) the plugin will not be able to decrypt and open the CVM. A request can be made to uncover a missing password on the Kuriimu2 github after the plugin was finished.

Currently, the CVM plugin can properly load directories and files, and only the save procedure is missing.

**Comment by onepiecefreak3** [comment]
Saving is now possible as well. I play tested the newly saved CVM from K2, and I could get into the game without any problems along the way. This finished work on this plugin. The CVM plugin is available in the newest dev build and upcoming Release 1.2.1 of Kuriimu2.

**Comment by Blackknight2000** [comment]
Hello onepiecefreak3 - I am really new to all this romhacking - I am trying to translate the game  Topic: Choujikuu Yousai Macross - Super Dimension Fortress Macross for the PS2 but the files are compressed as CVM files - I have been looking for help through the wed and this thread seems promising. I am hoping you might be able to help me figure out how to open these files. 

![Saq1JrR](https://user-images.githubusercontent.com/100182839/155065694-8d18f49c-ae2d-4f9b-b2b9-bd29d10d583f.png)

**Comment by onepiecefreak3** [comment]
This issue is closed. You're lucky I found your comment.
As you might read, CVM support was added to Kuriimu2, the successor of this program, Kuriimu.
Refer to it and its builds to try and open a CVM.

I can't and won't help you further here. If you have more questions about it, join our discord or open an issue for Kuriimu2.
