### ISSUE TITLE
Preview .xf(like .xi) wrong.

### ISSUE THREAD

**Issue by benladen** [IcySon55/Kuriimu#44]
Kukkii can preview .xf file, but it is wrong with multi layer. Could your team fix it?Thx.
file uploaded https://mega.nz/#!fYMhkB6R!Q3TThDFHgixX9WmZ_XmUpfBd98yLPRQkbTUa6V3xQmg

**Comment by adibsurani** [comment]
There is nothing wrong with the preview or the xf file. The image appears exactly as intended.
