### ISSUE TITLE
3DZ_LZ plugin bug(Dragon Ball Heroes Ultimate Mission X)

### ISSUE THREAD

**Issue by agemo999** [IcySon55/Kuriimu#440]
Issue: bug report
Console: Nintendo 3DS
Format extension(s): .bin with 3DZ_LZ packing
Type: archive
Game Name: 
Dragon Ball Heroes Ultimate Mission X
First 8 bytes of the file(s):
bin - 33 44 53 2D 4C 5A 0D 0A -3DS-LZ

More details:
I have 5 files with this compression and it gives an error of illegal characters in path, this is the only one that gives this error, the orther 3DZ-LZ packed files were recognized by karameru

Sample files (if possible):

https://mega.nz/#!tlVRiSYA!t-_xBjfdrllmPc4AjZV-7WHU1cGEqIxvrPVi3yHwQDI

**Comment by IcySon55** [comment]
Fixed in latest commit. 10e5f39c616606a83e8a14ddbc3e41d8f654b78d
