### ISSUE TITLE
.fa files are not being saved 1:1

### ISSUE THREAD

**Issue by argoneuscze** [IcySon55/Kuriimu#443]
Issue: [bug report]
Console: 3DS
Format extension(s): .fa (Level 5 archive)
Type: [archive]
Game Name: PLvsAA

First 8 bytes of the file(s):
.fa - 58 46 53 41 24 00 00 00 - XFSA$...

More details:
After opening a clean 399 MB .fa archive with Karameru and immediately saving, the resulting .fa only has 396 MB and some models are visibly missing from the game (or just fail to load).

Sample files (if possible):
Not sure I can just link those here.

**Comment by onepiecefreak3** [comment]
With the newest commit it does now.
