### ISSUE TITLE
Monster Hunter XX (SW) TEX Files #2

### ISSUE THREAD

**Issue by Deathmaw** [IcySon55/Kuriimu#454]
Issue: Plugin Request
Console: Switch
Format extension(s): .tex
Type: Image
Game Name: Monster Hunter XX

First 8 bytes of the file(s):
.tex - [54 45 58 00 A0 80 00 20] - [TEX.... ]

More details:
In the previous issue (https://github.com/IcySon55/Kuriimu/issues/417) you mentioned making a new issue if some of the formats didn't work, here are some sample files that didn't.

Sample files (if possible):
https://mega.nz/#!spBnlZzD!MZrOgCBYI-a0CfQC6zijUJUcw-0742tQ_qF9qPlGVEQ

**Comment by onepiecefreak3** [comment]
All the files should be handled with the newest commit;
