### ISSUE TITLE
[Plugin Request] Exstetra .rtex Image Files

### ISSUE THREAD

**Issue by TervalentSpy** [IcySon55/Kuriimu#458]
Issue: Plugin Request
Console: 3DS
Format extension:  .rtex
Type: Image
Game Name: Exstetra

First 8 bytes of the file(s):
.rtex - [52 54 45 58 00 00 00 00 90] - [RTEX.....]

More details:
Here are the textures of the game.

Sample files:
[Rtex sample files](http://www.mediafire.com/file/aefoc2mkc97cotv/Sample%20files%20rtex.rar)

**Comment by onepiecefreak3** [comment]
A plugin for this format already exists in the newest dev build and upcoming Release 1.2.1 of Kuriimu2.
The format will be identified automatically. Your samples also showed that the plugin that existed until now missed the image format 31. If you encounter other files that should tell you that a format is missing or other bug reports, please refer to Kuriimu2.
Issue closed.
