### ISSUE TITLE
SHTX Image Formats

### ISSUE THREAD

**Issue by AlphaXeno** [IcySon55/Kuriimu#462]
Issue: Plugin Request
Console: Wii
Format extension(s): SHTX, SHTXFS, SHTXFF
Type: Image
Game Name: Inazuma Eleven Strikers

First 8 bytes of the file(s):
6 bytes TAGS (SHTXFS, SHTXFF eccetera) - 4 bytes image height and width (at least for shtxfs)

More details:
<details>

Sample files (if possible):
https://mega.nz/#!WLhT1SIK!3mu8nYFr9aYokyU6Ais1HkM4ik4Mm0EOSpRDhi0gojQ

There are already scripts from BlackDragonHunt and UnderMyBrella.
https://gist.github.com/UnderMybrella/ae3c0b906978aa067fd1baa003a72463
https://github.com/yukinogatari/Danganronpa-Tools/blob/master/dr12ae/shtx_conv.py

EDIT: The scarlet converter uses the format RGBA to convert from shtx to png and viceversa, but in the SHTXFS the palettes are written in the order BGRA.

**Comment by onepiecefreak3** [comment]
The SHTX format was implemented in Kuriimu2.
This issue will therefore be closed.
