### ISSUE TITLE
.bln Archives

### ISSUE THREAD

**Issue by AlphaXeno** [IcySon55/Kuriimu#463]
Issue: Plugin Request
Console: Wii
Format extension(s):  .bln
Type: Archive
Game Name: Inazuma Eleven Strikers (all versions)

First 8 bytes of the file(s):
<extension> - [bytes in hex] - [bytes in ASCII]

More details:
MCB0.BLN
The game uses 2 archives. The mcb0.bln and the mcb1.bln. Mcb0 is a table that contains pointer and size of the files/archives contained in mcb1.bln. Every entry of the table is 0xC bytes long and structured like the following:
0x4 (File ID); 0x4 (Offset (referred to mcb1)); 0x4 (Size of the file/archive).
At the end of the Mcb0 there are 14 bytes apparently not referred to the mcb1.

MCB1.BLN
Each archive extracted with the information from mcb0 contains game's files, compressed with the Spike Chunsoft most of the times. There is some kind of header before every file 0xC bytes long structured like the following:
0x4 (Kind of ID, common for most of the file); 0x4 (File ID), 0x4 (Size of the archive + 00 bytes padding - the size is always a multiple of 4000 (for example 4000, 8000, c000, 10000 eccetera);

Sample files (if possible):
MCB0.bln - https://mega.nz/#!ibwH1SbC!sE1k-7cNGaGE69qCAuEBwtHWR75PiZh-HGhVzHCkIZk
MCB1.bln Example - https://imgur.com/a/RrKSsql

**Comment by FilippoCarini** [comment]
Man, have you solved? I'm stuck here too...

**Comment by hero442** [comment]
> Man, have you solved? I'm stuck here too...

You solved? I also have the same problem, do you have Discord to understand what the problem is?

**Comment by FilippoCarini** [comment]
> > Man, have you solved? I'm stuck here too...
> 
> You solved? I also have the same problem, do you have Discord to understand what the problem is?

Yeah, I have discord, tell me your nickname and I'll add you :)

**Comment by hero442** [comment]
> > > Man, have you solved? I'm stuck here too...
> > 
> > 
> > You solved? I also have the same problem, do you have Discord to understand what the problem is?
> 
> Yeah, I have discord, tell me your nickname and I'll add you :)

s a r u#9232

**Comment by onepiecefreak3** [comment]
This is implemented in Kuriimu2. The game imposes restrictions to how the plugin can perform and only allows files smaller equal to the original to be reinjected.
This issue will be closed.
