### ISSUE TITLE
Infinite Title Screen Loading After .fa Export

### ISSUE THREAD

**Issue by Kirastar** [IcySon55/Kuriimu#466]
Issue: [bug report]
Console: 3DS
Format extension(s): .xi, .xa, .fa
Type: [image | archive]
Game Name: The Snack World

First 8 bytes of the file(s):
<extension> - [bytes in hex] - [bytes in ASCII]

More details:
After only editing the image/.xi files in bag_top_d00.xa, exporting a new archive_a.fa file, and repacking the game, everything loaded up fine and the new images displayed as expected. Many more .xi files were replaced, all within .xa archives in the "data" subdirectory of archive_a.fa. No other files were touched; after exporting another new archive_a.fa and repacking the game, it hangs on an infinite load after the opening cutscene and eventually boots back to the cutscene to continue the cycle. Performing a batch export to PNG with Kukkii on all .xi within data returns three errors for "talk_d00_xa\000.xi", "\fp_snaport_u00_xa\001.xi", "fp_help_u00_xa\001.xi", but none of these files or their .xa were ever touched.

Sample files (if possible):
All most recent menu .xa: https://mega.nz/#!HGIwhILJ!QsWqBMa6qfC3vZkphiRwc8vAPm6OELdGH7A1SlHKoE0
Original talk/snaport/help .xa: https://mega.nz/#!3fhXRCrI!B2-doBbCPj6pCs5gBXadIBP8yj8Uheva9-PQbFBi4rw

**Comment by onepiecefreak3** [comment]
Files saved 1:1 and the main archive .fa of the game could also be recreated several times with the game working. You can open this issue again, if you can provide the archive that may corrupt the game.
The errors you encountered with the images are solved in the newest commits.
