### ISSUE TITLE
CMP Import PNG Issue

### ISSUE THREAD

**Issue by AlternativeZero** [IcySon55/Kuriimu#467]
Issue: bug report
Console: Nintendo 3DS
Format extension(s): .cmp
Type: image
Game Name: Shin Megami Tensei Strange Journey Redux

First 8 bytes of the file(s):
.cmp - 11 80 10 00 00 53 54 45 - .€...STE

More details:
I was able to successfully decompress the .cmp file but when I replace the image with an edited one in that decompressed .cmp file it doesn't save properly and has a green outline surrounding it, what makes strange to me is the imported image came from another .cmp that was in unused files in the same game.

Sample files (if possible):
https://drive.google.com/open?id=1F_XLT_nIIm_N1v55dhq8yaJ3K5GrP0kH

**Comment by onepiecefreak3** [comment]
@AlternativeZero I can't download the file since it's not public. Make it public so others can see it too.

**Comment by AlternativeZero** [comment]
Sorry about that, hopefully it's fixed now.

**Comment by onepiecefreak3** [comment]
No issue. It was the reinjected image that somehow mixed light green color in the colordata of the alpha part. ETC1A4 uses 4x4 pixel blocks and doesn't care if the pixel has alpha set or not. It will still use all 16 colors and interpolate them, leading to a greenish outline in a blockwise fashion on the character.
That is normal behaviour and intended by the specification, so the image needs to be adjusted.
