### ISSUE TITLE
.xi file bug introduced by one of the latest commits

### ISSUE THREAD

**Issue by Volcah** [IcySon55/Kuriimu#470]
Issue: bug report
Console: Nintendo 3DS and maybe others idk
Format extension(s): .xi
Type: image
Game Name: Inazuma Eleven GO 2

First 8 bytes of the file(s):
49 4D 47 43 30 30 00 00

More details:

In the commit "Fixed 2 XI formats" ( https://github.com/IcySon55/Kuriimu/commit/8e1e399fbfbd6a088dc49e0d1aeadf4949821701 ) a bug was introduced:
Specifically in " File.WriteAllBytes(@"C:\Users\Kirito\Desktop\tex.bin", tex); "

**Comment by onepiecefreak3** [comment]
Sorry, for the inconvinience. Debug line is removed in newest commit.
