### ISSUE TITLE
Plugin Request) PAPA Flag File

### ISSUE THREAD

**Issue by mirusu400** [IcySon55/Kuriimu#471]
Issue: plugin request
Console: Nintendo 3DS
Format extension(s): Nothing
Type: Text or Archive
Game Name: Harvest Moon A New Beginning

First 8 bytes of the file(s):
none - 50 41 50 41 00 00 00 00 - PAPA....

More details:
This is used in Harvest Moon A New beginning(牧場物語はじまりの大地)
And this file is extracted from xbb file(by karameru)

this has no extension, but it has PAPA Flag(0x00)
maybe one programmer analyze this file but im bad at C# so i cant do anything...
this is his github https://github.com/andibadra/HarvestMoon-3DS---XBB-PP-Archive

Also, I dont' know exactly this file is Text file or Archive File, because it has Text but many other stuffs..

Sample files (if possible):
https://drive.google.com/file/d/11EzNVznxRKKTZSw8j_HQGsdXGqNYU972/view?usp=sharing
 
Msg.xbb is original Archive File, and other is example file of PAPA Flag Files which extracted from Msg.xbb file

This is extracted from JPN File, And Encoding is Unicode Little-Endian. Also there was so many ASCII texts.. but i don't know what it is.

Thank you.

**Comment by onepiecefreak3** [comment]
PAPA is a text format and a pretty easy one. It will later be usable by Kuriimu to look into the text.

**Comment by onepiecefreak3** [comment]
Load/Save added in newest commit;

**Comment by mirusu400** [comment]
Thanks a lot !!!
