### ISSUE TITLE
Suggestion: Setting that makes Kuriimu not ask you to backup msbt

### ISSUE THREAD

**Issue by mariomadproductions** [IcySon55/Kuriimu#473]
Issue: feature request
Console: [multiple]
Format extension(s): msbt
Type: text
Game Name: [multiple]

More details:
Every time I open an msbt it asks if I want to back it up. Could there be an option to disable this pop-up?

**Comment by IcySon55** [comment]
If you don't backup the file, you can't display the original text. It will go away if you back it up.

This is on purpose because Kuriimu is geared towards fan translation teams.

**Comment by mariomadproductions** [comment]
This is a useful feature if you are worried about losing text changes, but it can be annoying in other circumstances. Could the feature I described be added?

**Comment by mariomadproductions** [comment]
I'm not really sure what you are saying. But a setting that'd disable automatic backups would be useful, so I can view MSBTs without dismissing the pop-up every time.

**Comment by onepiecefreak3** [comment]
The structural problems described here will not be present in the Text API of Kuriimu2. We will take note of this circumstance when we introduce it there.
Since Kuriimu1 is otherwise discontinued, this issue will be closed.
