### ISSUE TITLE
Kirby Star Allies (de)compression

### ISSUE THREAD

**Issue by eleonore122** [IcySon55/Kuriimu#475]
Issue: feature request
Console: Switch
Format extension(s): .arc.cmp/.bfres.cmp
Type: image
Game Name: Kirby Star Allies

First 8 bytes of the file(s):
<.arc.cmp> - [A0 4A 99 00 04 22 4D 18] - [J"M]
<.bfres.cmp> - [20 D2 16 02 04 22 4D 18] - [Ò"M]

More details:
<i tried all of the compression types that kuriimu currently supports with no success. the .arc.cmp files seem to have SARC headers, but that's about all i know about them since i'm not super knowledgeable about this stuff.>

Sample files (if possible):
<http://www.mediafire.com/file/scc3z8kfs7tvffl/Title.arc.cmp>
<http://www.mediafire.com/file/747cat54qrnpc5c/Field.bfres.cmp>

**Comment by onepiecefreak3** [comment]
Fixed in newest commit. LZ4 now works as expected from the LZ4 original. For the files in Nintendo games specifically there is a new menu point under Compression for "Preceding size" in LZ4, which has to be used.
