### ISSUE TITLE
g1t doesn't save correctly

### ISSUE THREAD

**Issue by Darkmet98** [IcySon55/Kuriimu#477]
Issue: bug report
Console: PC
Format extension(s): g1t
Type:image
Game Name: Nights Of Azure

First 8 bytes of the file(s):
.g1t - 47 54 31 47 30 36 30 30 - GT1G0600

More details: (Continues from here #476 )
I exported a image from the title screen and doesn't show correctly
![imagen](https://user-images.githubusercontent.com/13910563/42159990-faff7b86-7df5-11e8-8024-d3860478f04c.png)
The images are DDS compressed with dxt5 without the header
I change the header generated from kurii for the original and the game works but the letters doesn't show
![imagen](https://user-images.githubusercontent.com/13910563/42160088-41b0c850-7df6-11e8-8d87-82d0cf33967c.png)
The modified image is here
![c_title g1t 01](https://user-images.githubusercontent.com/13910563/42160111-56aba9b4-7df6-11e8-8a23-493bc910ec76.png)
And the modified files
https://drive.google.com/file/d/1uim1hAdo3eLagg9tBH0n9C6TaExfx6Pi/view?usp=sharing

**Comment by onepiecefreak3** [comment]
Fixed saving for multi image G1T's.
Try again and close the issue if it was fixed.

**Comment by Darkmet98** [comment]
Works great!
![imagen](https://user-images.githubusercontent.com/13910563/42161268-89f7f8be-7dfa-11e8-8ad4-d20c15abf7a5.png)
![imagen](https://user-images.githubusercontent.com/13910563/42161273-919c2a54-7dfa-11e8-858d-e652a77bd8c7.png)

Thanks! :D

**Comment by onepiecefreak3** [comment]
Perfect
