### ISSUE TITLE
Cia Decryption issue

### ISSUE THREAD

**Issue by MetalFan1988** [IcySon55/Kuriimu#478]
Issue: [bug report]
Console: N3DS
Format extension(s): .cia
Type: [archive]
Game Name: Dragon Quest VII Fragments of the Forgotten Past (USA) (RF).cia

First 8 bytes of the file(s):
<extension> - [bytes in hex] - [bytes in ASCII]

More details:
Guys, I have the following error when trying to decrypt this cia. (I drop a capture screen) Could you please give it a look. Thanks in advance for your help
![captura de pantalla 1](https://user-images.githubusercontent.com/29298680/42237070-5a538e48-7ec2-11e8-9a2f-2e564ef03f3e.png)

Sample files (if possible):
<links>

**Comment by onepiecefreak3** [comment]
The cia decryption algorithm was completely refactored. Takes way less memory and maybe even time.
Retry the decryption again with the newest commit.
