### ISSUE TITLE
STEX Imported Color Issue

### ISSUE THREAD

**Issue by AlternativeZero** [IcySon55/Kuriimu#480]
Issue: bug report
Console: Nintendo 3DS
Format extension(s): .stex
Type: image
Game Name: Shin Megami Tensei (Various) 

First 8 bytes of the file(s):
.stex - 53 54 45 58 00 00 00 00 - STEX....

More details:
Not sure what the issue is but the imported edited image seems to have it's color altered from the .png that was used turning green in this instance to brown, hopefully this can be looked at and fixed as it's a similar issue I had when I reported it with .cmp #467,

Sample files (if possible):
https://drive.google.com/open?id=1koB6mYsSA0HvvPju9gzloxIu4GNgbsiH

**Comment by Megaflan** [comment]
I couldn't reproduce the issue with neither latest public release and latest commit.
If you can bring more details about the issue, the files that have the problem and some photos, we'll look further.
For now, just try with the latest release, maybe that will fix your problem.

**Comment by AlternativeZero** [comment]
I'm currently using the latest release and the files included contains the .png I used and the .stex I'm trying to modify, all that happens is the color changes from olive green to brown but it isn't conistent with it only changing a portion of the image but not all of it.

Here is the edited one I made and what happens when I imported it, I just exported it as an example but this is what I'm seeing.
![edited](https://user-images.githubusercontent.com/32092294/42279341-d230c02e-7fe0-11e8-9a30-0509d0e8fb53.png)
![import](https://user-images.githubusercontent.com/32092294/42279342-d274d8ae-7fe0-11e8-9280-6cb41c7ed5ac.png)

**Comment by onepiecefreak3** [comment]
No issue. The image just doesn't get dithered and gets downsampled from a range of RGB888 to RGB565.
That leads to more visible changes and "corruptions". That is intended behaviour based on the image format. A possibility to change the format was added nonetheless.
