### ISSUE TITLE
g1t images are distorted

### ISSUE THREAD

**Issue by Accelerator11** [IcySon55/Kuriimu#482]
Issue: bug report
Console: PS Vita
Format extension(s): g1t
Type: image
Game Name: Atelier Lydie & Suelle

First 8 bytes of the file(s):
.g1t - 47 54 31 47 30 36 30 30 - GT1G0600

More details:
I compile and use the g1t latest commit. When i open g1t from PS Vita images are distorted.
![capture](https://user-images.githubusercontent.com/38535208/42323094-82454f4c-8091-11e8-9279-0537e2968a7e.PNG)
Sample files (if possible):
https://drive.google.com/drive/folders/1Q1imSikvl9WN5oL16-PK-KcaPc-enVd8

**Comment by onepiecefreak3** [comment]
G1t are used on several systems and we can't know ftom which system they come from. Images from Vita are "swizzled". That means they need special treatment specialized for the platform to not look distorted.
To make it it work for vita images you need to rename the file that "vita" is written in it. Then the plugin knows how to "deswizzle" the g1t.
In your example you can rename the file to "a19_title_vita.g1t" and it should work.

**Comment by onepiecefreak3** [comment]
If it works pls close the issue. Ask right away if you have further questions on the swizzle or renaming.

**Comment by Accelerator11** [comment]
It works. Thanks
