### ISSUE TITLE
[Bug] MT Tex - KeyNotFoundException

### ISSUE THREAD

**Issue by mhdasding** [IcySon55/Kuriimu#483]
Issue: bug report
Console: Switch
Format extension(s): .tex
Type: image | archive
Game Name: Monster Hunter XX (Switch)

First 8 bytes of the file(s):
.tex - 54 45 58 00 A0 80 00 20 - TEX

More details:

loading the attached sample file produces the following error:
``` ---------------------------
MTTEX - MT Framework Texture Adapter
---------------------------
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

   at System.ThrowHelper.ThrowKeyNotFoundException()

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at image_mt.MTTEX..ctor(Stream input)

   at image_mt.MTTexAdapter.Load(String filename)

   at Kukkii.Converter.OpenFile(String filename)
---------------------------
OK
---------------------------
```

the file should be in DXT1 format. it is NOT a normal map despite it's name it actually stores specular/diffuse lighting and should output someting like this:
https://imgur.com/a/xWOY6zX
except for the left and right side split into seperate color channels
the file specifies 4 bit per pixel and format id 0x19 so it should be DXT1.
so maybe there's some other kind of bug and the codec and everything is correct.

Sample files (if possible):
https://mega.nz/#!as02xYLA!zjsMJUJgSMj1xMz6fHBGJbpedmvDjJfA8kFzAptLCbo

**Comment by onepiecefreak3** [comment]
The codec is probably correct. We just choose the format to use from a dictionary. The dictionary doesn't entry 0x19 yet. A quick fix.

**Comment by onepiecefreak3** [comment]
Added in newest commit;

**Comment by evil-trainer** [comment]
So, I've been having the same issue with the same file format in another Capcom game: Resident Evil 0 for Nintendo Switch. Is it possible that the commit above fixes the issue only with the Monster Hunter game?
