### ISSUE TITLE
MT Framework support (ARC) for Switch

### ISSUE THREAD

**Issue by Joonie86** [IcySon55/Kuriimu#484]
Issue: bug report/feature request (Switch support)
Console: Switch
Format extension(s): ARC
Type:  archive
Game Name: Resident Evil Revelations

First 8 bytes of the file(s):
ARC - [415243000900B20269645F6268725C30]  - [ARC...².id_bhr\0]

More details:
Opening ARC from Resident Evil Revelations throws this error
https://imgur.com/5P3kMUf

Sample files (if possible):
https://mega.nz/#!bRpmhSQB!aNqQzA8ry3XjVOgohkJSx_7snCYgLZuQBOiqpivC7dU

**Comment by onepiecefreak3** [comment]
Load/Save is added with newest commit;
