### ISSUE TITLE
MT Framework support (ARC) for Switch (Karameru)

### ISSUE THREAD

**Issue by Joonie86** [IcySon55/Kuriimu#486]
Issue: bug report
Console: Switch
Format extension(s): ARC
Type: archive
Game Name: Resident Evil Revelations

First 8 bytes of the file(s):
ARC - [415243000900B20269645F6268725C30] - [ARC...².id_bhr\0]

More details:
Saving ARC from Resident Evil Revelations throws this error
![image](https://user-images.githubusercontent.com/8692743/42674028-014cceb4-8623-11e8-9b2c-d3e04baddfe7.png)

Sample files (if possible):
https://mega.nz/#!bRpmhSQB!aNqQzA8ry3XjVOgohkJSx_7snCYgLZuQBOiqpivC7dU (ARC)
https://mega.nz/#!Cc50HaoJ!80B4IibsrONX7g3TosNhLZY_prPL2FEM04GgoURdEuU (Modified files inside ARC)

**Comment by onepiecefreak3** [comment]
Fixed in newest commit;
