### ISSUE TITLE
[Karameru] .BIN archive Soul Hackers

### ISSUE THREAD

**Issue by Megaflan** [IcySon55/Kuriimu#487]
Issue: Plugin request
Console: 3DS
Format extension(s): .BIN
Type: archive
Game Name: Shin Megami Tensei: Devil Summonner: Soul Hackers 

First 8 bytes of the file(s): [00 01 45 56 5F 54 45 53 54] [  EV_TEST]

More details:
From 0x0 to 0x118F: File names, there's some sort of flags and unknown data there.
From 0x1800 onwards: Pointer + Text chunks, these correspond to .EVE files, already RE'd

Sample files (if possible):
http://ge.tt/6nuEZZq2

> With love, Flanny <3

**Comment by onepiecefreak3** [comment]
After some code RE, the file consists of an entry table with 2 bytes BE Global ID, 0x10 bytes filename and 2 bytes BE unknown data. Beginning at 0x1800 and aligned to 0x400 are the files. A table with offset and size of each of those files is in the code.bin. Using the elf version of it, the file table for EVENT.BIN starts at 0x0039C620. Cause of the instability and unidentifiable loose structure no plugin will be written. But an external tool with this information is possible and easy.
