### ISSUE TITLE
MTTex Mipmap Downsampling

### ISSUE THREAD

**Issue by kyle788** [IcySon55/Kuriimu#490]
Issue: feature request
Console: 3DS/Switch
Format extension(s): MTTex
Type: image
Game Name: Monster Hunter XX 

First 8 bytes of the file(s):
54 45 58 00 A6 00 1B 20

More details:
It would be great that if importing an image at mipmap 0, it would downsample to all other mipmap levels. Currently right now you need to manually resize the image for each level and import it at each level manually.

Sample files (if possible):
https://mega.nz/#!aWhFyKDI!s0DKWPoXl1fB9I9TzyocPpM0H9QnQoBgV-3vj49VQ8s

**Comment by IcySon55** [comment]
Implemented MTTEX downsampling in the latest commit.
