### ISSUE TITLE
Suggestion: Command line mode

### ISSUE THREAD

**Issue by mariomadproductions** [IcySon55/Kuriimu#491]
For things like image conversion, archive extraction.

**Comment by onepiecefreak3** [comment]
It's a planned feature for Kuriimu2, since it will be completely independant from the GUI. It will not be done in Kuriimu 1, which is currently in the wild.

**Comment by onepiecefreak3** [comment]
Kuriimu2 now has a command line tool for better integration with other tools. There currently is no documentation on how to use it, but it's set up to take a virtually infinite stream of arguments to perform actions on files.
It's also meant to be usable by normal users directly on the command line, not just for consumption in other tools.
If you have requests regarding the command line of Kuriimu2 or bug reports, please refer to its github.
Issue closed.
