### ISSUE TITLE
Suggestion: Kukki should use normal file selector window for Batch Export/Import

### ISSUE THREAD

**Issue by mariomadproductions** [IcySon55/Kuriimu#493]
Use a "normal file selector window" rather than a "simple tree view file selector window" for Kukki's Batch Export/Import option, to allow easier navigation.

**Comment by onepiecefreak3** [comment]
Kuriimu2 makes only use of either the file selection or directory selection dialogs in all its forms.
This also means that mentioned tree view (which I also find is really nasty to use) should not be a concern anymore.
If you still find usage of this dialog somewhere in Kuriimu2, where it might disturb the user experience, please refer to the Kuriimu2 github for such reports.
