### ISSUE TITLE
Help openening .tex files

### ISSUE THREAD

**Issue by Varon9** [IcySon55/Kuriimu#501]
Issue: plugin request
Console: PlayStation Vita/PlayStation 3
Format extension(s): .tex
Type: image
Game Name: Lone Survivor Director's Cut

First 8 bytes of the file(s): 49 4D 47 30 00 00 10 00
bytes in hex

More details:
Textures. i can open it with tile molester but i need something like photoshop to translate it, so i need some way to export/import the image to this format

Sample files (if possible):
https://mega.nz/#!5jR3XYbS!crTylqjn8uanmxFU9dW0r5p-z5OBdaVNPrRdzEj3XOo

**Comment by onepiecefreak3** [comment]
The newest dev build and upcoming Release 1.2.1 of Kuriimu2 has full support for this format. For further feature requests or bug reports regarding this format, please refer to Kuriimu2.
This plugin can automatically detect the format and load it.
