### ISSUE TITLE
[Plugin Request] Sony ADPCM Encoder/Decoder Request (Various Games)[PS Family]

### ISSUE THREAD

**Issue by SteveDoido** [IcySon55/Kuriimu#507]
Issue: plugin request
Console: Sony platforms
Format extension(s): n/a
Type: sound
Game Name:  n/a

First 8 bytes of the file(s):
Type 1: .bin - 00 00 00 00 00 00 00 00 - ........
Type 2: .bin - 43 00 00 00 00 00 00 00 - C.......

More details:
Due to circumstance, the files may or may not start with an empty row of bytes.
A version with this row manually added to files that didn't was included for reference's sake.
Its existence is NOT a reliable detection method. 

Sample files (if possible):
https://mega.nz/#!Lls2DKwS!u_V5HPzIwMOwNSy9D3yV6YjlVDsIqPHi2XXJerYKvco

**Comment by onepiecefreak3** [comment]
Both tools do not support any sound formats. We also have no current design for an API in that direction. You may have more luck using VGMtoolbox or related tools with massive sound support.
Due to this, I close the issue.
