### ISSUE TITLE
Mario Golf World Tour (.cbch)

### ISSUE THREAD

**Issue by ChaoticFusion40** [IcySon55/Kuriimu#511]
Issue: Plugin Request
Console: 3DS
Format extension(s): .cbch
Type: Models/Textures
Game Name: Mario Golf: World Tour

First 8 bytes of the file(s):
BCH - 60 94 4F 05 00 42 43 48 00 - [`”O�BCH]

More details:
<This Uses LZ60, But I Tried Many Compression Algorithms, But Failed>

[mario.zip](https://github.com/IcySon55/Kuriimu/files/2363814/mario.zip)

**Comment by onepiecefreak3** [comment]
The file is compressed with a new compression algorithm, tagged 0x60 and introduced on switch. It's structure is currently unknown (at least to us). We will look at it later.

**Comment by ChaoticFusion40** [comment]
Actually, This Was Introduced In Mario Tennis Open For 3DS

**Comment by onepiecefreak3** [comment]
Oh rly? I didn't know that this compression could be used on other platforms. That's new I only every encountered it regularly on switch games.

**Comment by ChaoticFusion40** [comment]
no need for this
