### ISSUE TITLE
Highschool DXD CTX support broken since v1.0.11

### ISSUE THREAD

**Issue by Ziiella** [IcySon55/Kuriimu#519]
Issue: **bug report**
Console: **3DS**
Format extension(s): **CTX**
Type: **image** 
Game Name: **Highschool DxD**

First 8 bytes of the file(s):
CTX - [43 54 58 20 31 30 20 00] - [CTX 10 .]

More details:
Ever since v1.0.11, when you "Improved CTX image plugin compatibility.", support for the format has been broken giving this error: https://cdn.discordapp.com/attachments/256507310313177090/491599543771856917/unknown.png

Sample files (if possible):
https://mega.nz/#!o5QnjLia!Xf1vb1KcCCemj6pHIvc1xv8QWRWxlUTcAea1tW0GrR0

**Comment by onepiecefreak3** [comment]
A small oversight in the last refactoring. Problem fixed in newest commit.
