### ISSUE TITLE
I can't see bclyt !

### ISSUE THREAD

**Issue by leafthelast** [IcySon55/Kuriimu#520]
Issue: bug report
Console: nintendo 3ds
Format extension(s): bclyt
Type: [text | image | archive]
Game Name: super robot daisen UX

First 8 bytes of the file(s): 43 4C 59 54 CLYT
<extension> - [bytes in hex] - [bytes in ASCII]

More details:
I put ".bclim file" and ".bclyt file" in the same folder and opened bclyt with kukkii.
The bclyt file looks cracked in kukkii. But at EFE it looked good.
It seems like an error, can I fix it?

Sample files (if possible):
<links>

DELETE ME: Do not attach files to the issue directly. Please use links to files hosted on other sites like Google Drive, Mega or similar.

**Comment by onepiecefreak3** [comment]
You can't.
Bclyt was since just experimental and isn't in development currently.
It also will stay incomplete for some time.

**Comment by leafthelast** [comment]
Thx onepiecefreak3.

I just want to learn a bit more about bclyt. Thanks for the reply!
