### ISSUE TITLE
Crash on attempt to load certain .ctxb files

### ISSUE THREAD

**Issue by CHEMI6DER** [IcySon55/Kuriimu#529]
Issue: bug report
Console: Nintendo 3DS
Format extension(s): ctxb
Type: image
Game Name: Luigi's Mansion 3DS Remake

First 8 bytes of the file:
.ctxb - [bytes in hex] 6374786280200000

More details:
Attempting to load a .ctxb file with imageFormat = 0x5867 and dataType = 0x0114 results in a crash.

Sample files:
[HomeNixSign.ctxb](https://yadi.sk/d/sqlZoQ4ebdDG0g)

**Comment by onepiecefreak3** [comment]
Problem solved in newest commit.
Issue closed.
