### ISSUE TITLE
.gui files for MT Framework Ace Attorney 3D games

### ISSUE THREAD

**Issue by Pol74698** [IcySon55/Kuriimu#532]
Issue: [plugin request | bug report | feature request] .gui format request
Console: 3DS/Android
Format extension(s): .gui
Type: texture (regions)
Game Name: Phoenix Wright Ace Attorney: Dual Destinies & Phoenix Wright Ace Attorney: Spirit of Justice

First 8 bytes of the file(s):
.gui - 47 55 49 00 12 1B 02 00 - GUI..... (DUAL DESTINIES)
.gui - 47 55 49 00 14 21 02 00 - GUI..!.. (SPIRIT OF JUSTICE)

More details:
These files should store the regions through which some textures are positioned (you'll see that in Dual Destinies' "All Rise" graphic, stored inside big_font_01). I would've linked Dai Gyakuten Saiban's files, but I can't access them

Sample files (if possible):
https://ufile.io/qut5z
(link expires in 30 days)

**Comment by onepiecefreak3** [comment]
.gui files in MT Framework games are the layouts, through which text and graphics are positioned. Such layouts are not supported in any way by Kuriimu or Kuriimu2 currently.
The issue will be closed, but be sure that the gui format will be the first format supported when Kuriimu2 will get a layout API at some point.
