### ISSUE TITLE
error while exporting ctxb file

### ISSUE THREAD

**Issue by ArcadeZtheWolf** [IcySon55/Kuriimu#533]
Issue: bug report
Console: 3DS
Format extension(s): CTXB
Type: Image
Game Name: The Legend Of Zelda: Majora's Mask

First 8 bytes of the file(s):
CTXB - 63 74 78 62 48 00 08 00 - ctxbH....

More details:
when I attempt to export the file "guideline_parts00.ctxb" it returns the error "system.collections.generic.keynotfoundexception: the given key was not present in the directory. at system.throwhelper.throwkeynotfoundexception() at system.collections.generic.dictionary`2.get_item(Tkey key) at image_ctxb.CTXB.Save(String filename) at Kukkii.converter.savefile.(boolean saveas)"

Sample files (if possible):
https://drive.google.com/file/d/1J_0U5jjSK5XaOlePcsIYzrEJJeBOlrKw/view?usp=sharing

**Comment by onepiecefreak3** [comment]
This error was not reproducable with Kuriimu commit bb26fc4f. And since 1.0.13 the ctxb plugin shouldn't have changed.
Please update the program and see if it works.
