### ISSUE TITLE
Add support for text editing in NSMB2

### ISSUE THREAD

**Issue by blinkpen** [IcySon55/Kuriimu#537]
Issue: [plugin request | bug report | feature request]
Console: 
Format extension(s): 
Type: [text | image | archive]
Game Name: 

First 8 bytes of the file(s):
<extension> - [bytes in hex] - [bytes in ASCII]

More details:
<details>

Sample files (if possible):
<links>

DELETE ME: Do not attach files to the issue directly. Please use links to files hosted on other sites like Google Drive, Mega or similar.

**Comment by mariomadproductions** [comment]
NSMB2's text files (MSBT) are supported.

**Comment by onepiecefreak3** [comment]
Since the issue does not contain any information beside the title wanting support for a specific game, and @mariomadproductions mentioning that the game uses MSBT, which Kuriimu supports, this issue will be closed.
In the future, please fill out the issue correctly and refer to Kuriimu2 instead.
