### ISSUE TITLE
Add support for editing fonts in NSMB2 (saving after importing images)

### ISSUE THREAD

**Issue by blinkpen** [IcySon55/Kuriimu#538]
Issue: [plugin request | bug report | feature request]
Console: 
Format extension(s): 
Type: [text | image | archive]
Game Name: 

First 8 bytes of the file(s):
<extension> - [bytes in hex] - [bytes in ASCII]

More details:
<details>

Sample files (if possible):
<links>

DELETE ME: Do not attach files to the issue directly. Please use links to files hosted on other sites like Google Drive, Mega or similar.

**Comment by onepiecefreak3** [comment]
This issue as well does not contain any information beside the title. Those are invalid issues and will generally not processed.
However, Kuriimu has no font capabilities and will never allow saving of its images. Kuriimu2 will get a font API in the future, so be sure to use it in the future, and make requests on the Kuriimu2 github.
