### ISSUE TITLE
(PLUGIN REQUEST) Yo-kai Sangokushi Image Files (.G1T)

### ISSUE THREAD

**Issue by kuronosuFear** [IcySon55/Kuriimu#539]
Issue: Plugin Request
Console: 3DS
Format extension(s): .GT1 / .G1T
Type: Image
Game Name: Yo-kai Watch Sangokushi

First 8 bytes of the file(s):
.GT1 / .G1T  - 47 54 31 47 30 36 30 30 - GT1G0600

More details:
Related to #530 
Kukkii can identify the image files, however, an error message says that they are currently unsupported.
It seems to be trying to identify the format based on the byte value at offset 0x25.

Error message:
System.Exception: Unsupported image format 0x09 (or any value at offset 0x25).
   at image_g1t.G1T..ctor(Stream input, Boolean vita)
   at image_g1t.G1tAdapter.Load(String filename)
   at Kukkii.Converter.OpenFile(String filename)

Sample files (if possible):
https://nofile.io/f/q8eb8SZJ9xE/00000000-0004ade0.GT1G0600
https://nofile.io/f/0uc7MoykfXC/00000001-000af140.GT1G0600
https://nofile.io/f/Vnsn4AhUTNR/00000002-000af1a0.GT1G0600
https://nofile.io/f/n24jUnPJpe2/00000003-000db740.GT1G0600
https://nofile.io/f/pmKcEK5m6Nr/00000004-000dde20.GT1G0600
https://nofile.io/f/Ha082jpFagb/00000005-000def80.GT1G0600
https://nofile.io/f/FgPXrCvuXm1/00000006-00173240.GT1G0600
https://nofile.io/f/Mo8W9AwaxEH/00000007-00184b80.GT1G0600
https://nofile.io/f/aCTVZS3qywF/00000008-00196480.GT1G0600
https://nofile.io/f/z19Qwq3Ghn3/00000009-001f0a60.GT1G0600

**Comment by onepiecefreak3** [comment]
Save and Load are working now for G1T from the platform 3DS.
Since G1T is used on many platforms with different settings in image processing, you have to add "3ds" somewhere into the filename.
The plugin will check for this "3ds" in the filename and chooses the correct settings for the G1T then.
Example: "image_3ds.g1t"; this will trigger the 3DS settings to be used.

**Comment by kuronosuFear** [comment]
Hi OPF,

I'd like to request support for additional files. Thank you so much!

Issue: Plugin Request
Console: 3DS
Format extension(s): .GT1 / .G1T
Type: Image
Game Name: Yo-kai Watch Sangokushi

First 8 bytes of the file(s):
.GT1 / .G1T - 47 54 31 47 30 36 30 30 - GT1G0600

Similar error to initial files when attempting to open with Kukkii v1.0.14:
System.Exception: Unsupported image format 0x3B (or any value at offset 0x25).
at image_g1t.G1T..ctor(Stream input, Boolean vita)
at image_g1t.G1tAdapter.Load(String filename)
at Kukkii.Converter.OpenFile(String filename)

Unsupported .3ds.g1t files:
https://nofile.io/f/zAv2CJUUGtM/00000013-X-00262200.3ds.g1t
https://nofile.io/f/kJwZOVRkJNq/00000014-X-00262200.3ds.g1t
https://nofile.io/f/ssDuKANaa8W/00000017-X-00524344.3ds.g1t
https://nofile.io/f/C54zeo5DPkt/00000036-X-00262200.3ds.g1t
https://nofile.io/f/PJwMbsyatAR/00017714-X-00262200.3ds.g1t
https://nofile.io/f/JKz5eceDJro/00017713-X-00262200.3ds.g1t
https://nofile.io/f/UfZ1SMucAX8/00017712-X-00262200.3ds.g1t
https://nofile.io/f/uKRjAwNwKaV/00017711-X-00262200.3ds.g1t
https://nofile.io/f/17WTj63SDsN/00003120-X-00131128.3ds.g1t
https://nofile.io/f/Jqkm09H3Qz9/00003119-X-00131128.3ds.g1t
https://nofile.io/f/7JVXupxWk3t/00003087-X-00262200.3ds.g1t
https://nofile.io/f/mwezYGjGccr/00003088-X-00262200.3ds.g1t
https://nofile.io/f/8J7xPJEHmPg/00003086-X-00262200.3ds.g1t
