### ISSUE TITLE
Special Characters seemingly not displaying in RS3DS Previewer

### ISSUE THREAD

**Issue by CakeLancelot** [IcySon55/Kuriimu#54]
Example:
https://cdn.discordapp.com/attachments/239097099101143040/293082019339042817/Capture.PNG

This is on the latest build as of 03-13-2017
All special characters seem to appear as question marks instead of the character itself like it once did. Perhaps it is caused by the rewritten font handling/rendering? If any other info is needed let me know.

**Comment by IcySon55** [comment]
Fixed via actually using the correct code points for the two non-working characters,
