### ISSUE TITLE
Professor Layton and the Curious Village Android .OBB

### ISSUE THREAD

**Issue by Timmerito** [IcySon55/Kuriimu#550]
Issue: plugin request
Console: Android
Format extension(s): obb
Type: archive
Game Name: Professor Layton and the Curious Village for Mobile

First 8 bytes of the file(s):
obb - B4 11 C2 02 37 2C 09 DF - ´.Â.7,.ß

More details:
It's encryped, and it can be extracted with a BMS script.

Sample files (if possible):
https://mega.nz/#!rjAjhIZa!wg3doooGXhzCRG5gv0KEBichkwZY8Jm7DyUDw4115SE

**Comment by onepiecefreak3** [comment]
This archive format is completely supported in the newest dev build and upcomgin Release 1.2.1 of Kuriimu2.
It can fully decrypt and encrypt the file as needed and can be edited as you like. If you have bug reports, please refer to the Kuriimu2 github.
