### ISSUE TITLE
(PLUGIN REQUEST) Yo-kai Sangokushi Image Files (.3ds.g1t)

### ISSUE THREAD

**Issue by kuronosuFear** [IcySon55/Kuriimu#551]
Hi OPF,

I'd like to request support for additional files. Thank you so much! Same with #539

Issue: Plugin Request
Console: 3DS
Format extension(s): .3ds.g1t
Type: Image
Game Name: Yo-kai Watch Sangokushi

First 8 bytes of the file(s):
.GT1 / .G1T - 47 54 31 47 30 36 30 30 - GT1G0600

Similar error to initial files when attempting to open with Kukkii v1.0.14:
System.Exception: Unsupported image format 0x3B (or any value at offset 0x25).
at image_g1t.G1T..ctor(Stream input, Boolean vita)
at image_g1t.G1tAdapter.Load(String filename)
at Kukkii.Converter.OpenFile(String filename)

Image formats requests for 0x3B, and 0x47

Unsupported .3ds.g1t files:
https://nofile.io/f/ZeVt9Aqabwt/UnsupportedG1T.zip

**Comment by IcySon55** [comment]
Solved by @kuronosuFear in PR #555
