### ISSUE TITLE
.tarc support from Tongari Boushi to Mahō no Machi

### ISSUE THREAD

**Issue by EmuPlays** [IcySon55/Kuriimu#552]
Issue: plugin request
Console: Nintendo 3DS
Format extension(s): .tarc
Type: Archive
Game Name: Tongari Boushi to Mahō no Machi

First 8 bytes of the file(s):
.tarc - 54 42 41 46 48 C4 AC 00 - TBAFHÄ¬.

More details:
The current plugin does not work, this error pops up
![image](https://user-images.githubusercontent.com/37835865/50352458-83956880-0545-11e9-9702-49472bb5a7b6.png)

Sample files (if possible):
[https://cdn.discordapp.com/attachments/471437763175120896/524690336023445515/menu_font.tarc
](https://cdn.discordapp.com/attachments/471437763175120896/524690336023445515/menu_font.tarc
)

**Comment by onepiecefreak3** [comment]
This issue is not reproducable on Release 1.2.0+ of Kuriimu2 with tarc files.
If there are more bugs for this format, please refer to the Kuriimu2 github in the future.
Issue closed.
