### ISSUE TITLE
Dragon Quest XI (3DS) Plugin

### ISSUE THREAD

**Issue by Koulucky** [IcySon55/Kuriimu#557]
Issue: [plugin request | bug report | feature request]
Console: 3DS
Format extension(s): .3ds
Type: Text
Game Name: Dragon Quest XI

More details:
I can't edit/open the DQ XI rom that has .3ds extension.

Sample file(s): https://download.tusfiles.net/d/yaky4qjdtr2fvxijidgjzuszlj6gwj225gtgffgcsmbagndogowzs2gvahmjearekswjacr5/DQXI-SSTOM-JPN-DecrTD-Ziperto.part1.rar, https://download.tusfiles.net/d/yak2wqrdtr2fvxijidgm5vsuciuk3a4bs6hex4lqvdscoyhdulhsyqn7ohbf5rbbppwanwhj/DQXI-SSTOM-JPN-DecrTD-Ziperto.part2.rar

**Comment by onepiecefreak3** [comment]
This bug is resolved in Kuriimu2.
