### ISSUE TITLE
[Plugin Request] Dokapon the World .cmb support

### ISSUE THREAD

**Issue by SixFingeredAmish** [IcySon55/Kuriimu#564]
Issue: [plugin request]
Console: PS2
Format extension(s): .cmb
Type: [archive]
Game Name: Dokapon the World

First 8 bytes of the file(s):
.bin 00 00 00 00 00 00 00 00 ........

More details:
I've tried using a hex editor to look at these .bin files but can't find any text from the game at all. I've consulted Etokapa and he/she thinks that the .bin files are encrypted/compressed/or in an archive and I should request here.

I appreciate any help you can give. Thank you.

Sample files (if possible):
https://mega.nz/#F!kwdSXY6a!15r-vqytzKI5NLr8zpv4VA

Updated to request .cmb files instead. Upon further inspection, it seems like the .bin files I was looking at earlier probably don't have the text.

**Comment by SixFingeredAmish** [comment]
Someone wrote a script for me! It works with quickbms.

**Comment by onepiecefreak3** [comment]
Could you link it, so we can support it later?

**Comment by SixFingeredAmish** [comment]
```
#Script for unpacking Dokapon the World .CMB PS2 Files.
#13.02.2019 - The Unknown

get START_OFFSET LONG
get FILENUMBER LONG
print Found %FILENUMBER% files.


for i = 0 < FILENUMBER

  GetDString FILENAME 84 
  Get SIZE LONG
  log FILENAME START_OFFSET SIZE

  xmath START_OFFSET " START_OFFSET + SIZE"

next i 
```

**Comment by onepiecefreak3** [comment]
Thanks
