### ISSUE TITLE
Feature Request Level 5 .fa Archives

### ISSUE THREAD

**Issue by Rytheex** [IcySon55/Kuriimu#566]
Issue: Feature request
Console: 3DS
Format extension(s): .fa (Level 5 Archive)
Type: archive
Game Name: Inazuma Eleven Go Galaxy Supernova (Sample game)

First 8 bytes of the file(s):
.fa - 41 52 43 30 48 00 00 00 64 - ARC0H...d

More details:
Add and delete features for Level 5 .fa archives :)

Sample files (if possible):
None

**Comment by onepiecefreak3** [comment]
One would need to edit the code.bin to make the game know, that a new file is there or another one missing. Therefore I don't quite know if one would want that feature.

**Comment by onepiecefreak3** [comment]
You can use the replace feature to replace existing files though

**Comment by onepiecefreak3** [comment]
Adding files to an ARC0 is supported in the newest dev build and upcoming Release of Kuriimu2.
