### ISSUE TITLE
Can't input Polish characters

### ISSUE THREAD

**Issue by bandithedoge** [IcySon55/Kuriimu#570]
Issue: bug report (?)
Console: -
Format extension(s): -
Type: text
Game Name: -

First 8 bytes of the file(s): -

More details:

I'm unable to input Polish characters (ążźćńłóę), since they are typed with the right alt key and a letter (example: right alt + "e" = "ę"). For example, when I want to type "ą", it just selects all text, since the right alt key is acting like the CTRL key. The same issue appears in other software as well, like Adobe Illustrator. The only workaround is to copy and paste characters from a text editor, but that's very annoying.

**Comment by IcySon55** [comment]
Since it's happening in other applications, there isn't much we can do about it. It appears to be a system wide thing for you. I just tried it and it's not happening for me.

**Comment by bandithedoge** [comment]
Is inputting Polish characters working for you? It also doesn't work for my friend who just downloaded Kuriimu.

**Comment by IcySon55** [comment]
Use left Alt maybe? This is tough to troubleshoot without a Polish keyboard.

**Comment by bandithedoge** [comment]
Polish keyboards use the right Alt only. You can just change the input in Windows since the Polish layout is the same as the English one.

**Comment by onepiecefreak3** [comment]
Since this bug occurs in other software of the user as well, like Adobe products, it's very likely a faulty setting on the users machine. A company like Adobe would have fixed this long ago.
Therefore this issue will be closed without further changes to the application.
