### ISSUE TITLE
BFFNT not supported from Switch Zelda BOTW

### ISSUE THREAD

**Issue by masagrator** [IcySon55/Kuriimu#573]
When i try to open this file with Kukkii, i got this error
![image](https://user-images.githubusercontent.com/8557858/52179333-69ec6f80-27d9-11e9-8e56-b898d2337e3e.png)
Example
[Ancient_00.zip](https://github.com/IcySon55/Kuriimu/files/2825713/Ancient_00.zip)
It was unpacked from SARC archive with Karameru.

**Comment by IcySon55** [comment]
You did completely ignored the issue template and also the note about not attaching files.
