### ISSUE TITLE
Bug: BFFNT won't open

### ISSUE THREAD

**Issue by masagrator** [IcySon55/Kuriimu#574]
Issue: bug report
Console: Nintendo Switch
Format extension(s): BFFNT
Type: archive
Game Name: Zelda Breath of the Wild

First 8 bytes of the file(s):
46 46 4E 54 FF FE 14 00

More details:
When I try to open with Kukkii BFFNT file unpacked from SARC archive, it shows error:
![52179333-69ec6f80-27d9-11e9-8e56-b898d2337e3e](https://user-images.githubusercontent.com/8557858/52193520-d013d980-284f-11e9-9647-704b975ec3f5.png)

Sample file:
https://drive.google.com/file/d/1lPoF-kBCza-J307h8ZPrA6NXOAHPZuRf/view?usp=sharing

**Comment by onepiecefreak3** [comment]
BFFNT's are font files and only supported to view the images in it. There will be no focus on fixing them beyond the point they are currently implemented.
Kuriimu2 will implement BFFNT's as font formats to support them better and have them savable as well in the future.
I will close this issue without further changes to the application, but be sure to check out Kuriimu2 in the future for font support. And be sure to create bug reports on the Kuriimu2 github if it still doesn't work.

**Comment by masagrator** [comment]
More than 2 years for any reply. Nice. :D
I completely forgot about this issue since I have managed to reverse font myself 2 years ago. 
So, yeah... Dunno what more to say after this long time. Good luck?
👍🏻
