### ISSUE TITLE
Suggestion: Allow opening of archives within archives

### ISSUE THREAD

**Issue by mariomadproductions** [IcySon55/Kuriimu#578]
Issue: feature request
Console: N/A
Format extension(s): N/A
Type: archive
Game Name: N/A

First 8 bytes of the file(s):
N/A

More details:
Suggestion: Allow opening of archives within archives. E.g. let the user open an NCA contained within an XCI without extracting the NCA (which can take a long time due to size).

Sample files (if possible):
N/A

**Comment by IcySon55** [comment]
This feature is planned for Kuriimu2 and it isn't possible within Kuriimu 1's API architecture.

**Comment by onepiecefreak3** [comment]
One major selling for Kuriimu2 from Day 1, and it is a possibility since its first releases. The system is also very reliable by now.
Since Kuriimu2 can do all that is requested already, this issue gets closed.
