### ISSUE TITLE
Atelier Rorona Image Files (.G1T)

### ISSUE THREAD

**Issue by lightfirst** [IcySon55/Kuriimu#579]
Issue: **plugin request** 
Console: **Nintendo Switch**
Format extension(s): **G1T**
Type: **image**
Game Name: **Atelier Rorona The Alchemist of Arland DX** 

First 8 bytes of the file(s):
47 54 31 47 30 36 30 30 2C 00 40 00 20 00 00 00        GT1G0600,

More details:
<details>
System.Exception: Unsupported image format 0x5F
image_g1t.G1t..ctor(Stream input, platform platform)
image_g1t.G1tAdapter.Load(String filename)
Kukkii.Converter.openFile(String filename)

Some g1t files in the same game are supported.
Some other files are not supported.

Sample files 
http://www.mediafire.com/file/24edgcbdnegjba2/NX.7z/file

**Comment by onepiecefreak3** [comment]
Dxt1 and Bc7 for the Switch in G1t are supported in the newest dev build and upcoming Release 1.2.1 of Kuriimu2.
For more formats necessary or other feature requests regarding this format, please refer to Kuriimu2.
