### ISSUE TITLE
(PLUGIN) Yo-kai Sangokushi .unknown filetype

### ISSUE THREAD

**Issue by NeonToaster1** [IcySon55/Kuriimu#580]
Issue: plugin request
Console: Nintendo 3DS
Format extension(s): .unknown
Type: image (possibly archive)
Game Name: Yo-kai Sangokushi

First 8 bytes of the file(s):
63 00 00 00 90 01 00 00 - 00018726-X-02170160.unknown

More details:
I'm speculating that these files hold models and texture data for Yo-kai Sangokushi. Tried looking at them in Karameru and got a false positive, opened it raw in Kukkii and it doesn't seem like it can recognize the file correctly either (comes out a garbled mess)

Sample files (if possible):
00018726-X-02170160.unknown - https://drive.google.com/file/d/1puvj2G7Q8PpAkkqE94Sh6ofIKTH2hAKi/view?usp=sharing

**Comment by NeonToaster1** [comment]
Extra sample files:
https://drive.google.com/file/d/1CR5Ufmyfl1YPrAEY4OJ0R2OT7dOSU3CC/view?usp=sharing
https://drive.google.com/file/d/16jUGmnmFYm1yMFljYw_ctO7Di7FkaW9U/view?usp=sharing
https://drive.google.com/file/d/1Dv_-Qtjr5EvxEx1N7s36cEAfi9sjcTL2/view?usp=sharing

**Comment by onepiecefreak3** [comment]
I don't know exactly where the unknown extension comes from (as I can see Karameru doesn't support the BIN/IDX format, which is the main archive of this game, and Kuriimu2 never used .unknown) but the files are still referenced by their internal index, as Kuriimu2 does.
The samples given refer to the following files as shown by Kuriimu2:
00018726.bin
00018731.bin
00018732.bin
00018733.bin

The files seem to be loose collections of textures (or generally files) tied together by a simple offset list.

**Comment by onepiecefreak3** [comment]
The newest dev build and upcoming Release 1.2.1 of Kuriimu2now support this format.
It's a manual plugin, which means it has to be manually selected at some point to load the format properly.
Select "BIN" under "plugin_koei_tecmo.dll" to open this format.
Issue closed.
