### ISSUE TITLE
(ISSUE) Issue opening .NARC files

### ISSUE THREAD

**Issue by NeonToaster1** [IcySon55/Kuriimu#582]
Issue: plugin request/bug report (???)
Console: Nintendo 3DS
Format extension(s): .NARC
Type: archive
Game Name: Puyo Puyo Chronicles

First 8 bytes of the file(s):
button.narc - 4E 41 52 43 FE FF 00 01

More details:
Karameru recognizes it as a .NARC file but gives this error
System.ArgumentOutOfRangeException: Index was out of
range. Must be non-negative and less than the size of the
collection.
Parameter name: index
   at
System.ThrowHelper.ThrowArgumentOutOfRangeException(E
xceptionArgument argument, ExceptionResource resource)
   at archive_nintendo.NARC.NARC..ctor(Stream input)
   at archive_nintendo.NARC.NarcManager.Load(String
filename)
   at Karameru.Manager.OpenFile(String filename)

Sample files (if possible):
button.narc - https://drive.google.com/file/d/1aYKrY0AyQ28DqpmORrzxhIvUswicdjnc/view?usp=sharing

**Comment by onepiecefreak3** [comment]
This issue is not reproducable on the newest dev build of Kuriimu2.
NARC support was ported to Kuriimu2 in its Release 1.2.0, which may also have this issue fixed.
For further bug reports and request, please refer to Kuriimu2.
