### ISSUE TITLE
Atelier Sophie G1T file

### ISSUE THREAD

**Issue by scese250** [IcySon55/Kuriimu#583]
Issue: plugin request
Console: PC
Format extension(s): G1T
Type: image
Game Name: Atelier Sophie: The Alchemist of the Mysterious Book

First 8 bytes of the file(s):
47 54 31 47 30 36 30 30 2C 00 00 01 20 00 00 00 GT1G0600

More details:
G1T - G1T Texture Adapter

System.Exception: Unsupported image format 0x01.

   en image_g1t.G1T..ctor(Stream input, Platform platform)

   en image_g1t.G1tAdapter.Load(String filename)

   en Kukkii.Converter.OpenFile(String filename)

Sample files (if possible):
https://www.dropbox.com/s/jv64oazku8d6mmo/MainFontHD1080_0.7z?dl=0

**Comment by onepiecefreak3** [comment]
The format is supported in the newest dev build and upcoming Release 1.2.1 of Kuriimu2. Please refer to it for future bug reports or feature requests regarding this format.
