### ISSUE TITLE
[Plugin Request] Animal Crossing New Leaf Script

### ISSUE THREAD

**Issue by Kyusetzu** [IcySon55/Kuriimu#588]
Issue: [Plugin Request]
Console: Nintendo 3DS Series
Format extension(s): MSBT (exported from UMSBT)
Type: [Text]
Game Name: Animal Crossing New Leaf (: Welcome Amiibo)

More details:
The textfiles for Animal Crossing are in a weird format.
Would love to have a good format for editing.
(https://i.imgur.com/cknMlIn.png)

Sample files (if possible):
https://drive.google.com/file/d/1IpL9WRUKyYJMiL382K5ptlOQ6gclxVEG/view?usp=drivesdk

**Comment by IcySon55** [comment]
Seems like you want a game plugin for AC. That will convert the byte data into tags like `<red>` or similar. The problem is that we'd have to spend a lot of time to figure out what they all mean to give them useful names. You should look around for a programmer that is interested in this game.
