### ISSUE TITLE
[Issue] jTEX Headerless Compression Issue

### ISSUE THREAD

**Issue by InochiPM** [IcySon55/Kuriimu#590]
Issue: Cannot open a jTEX file because it's compressed/Headerless.
Console: 3DS
Format extension(s): .jTEX (Headerless,Compressed)
Type: Sprite/image
Game Name: Tales of The World: Reve Unitia 

First 8 bytes of the file(s):
Worldmap_bg0.jtex - 11 80 00 08 06 80 00 00 - ◄Ç�◘♠Ç��

More details:
These files are for the game Tales of the Word: Reve Unitia, and all of the UI files are in jTEX format, someone made a jTEX tool to decode the files and export them as .PNG my problem is that i need to directly edit the textures inside the jTEX file. 

Some of them have spacing issues and when exported with the other tool they become all broken up. 
Especially the map names file.
![Worldmap_name](https://user-images.githubusercontent.com/13459080/56628134-a5e3e380-6616-11e9-8356-4a30b4c7ee91.png)
![TutorialWindow_menu_Window00](https://user-images.githubusercontent.com/13459080/56628161-beec9480-6616-11e9-9217-6952a56e0004.png)

Sample files (if possible):

https://www.dropbox.com/s/ek2wyhwsxpmy2s2/Worldmap_bg0.jtex?dl=0
https://www.dropbox.com/s/mwwqmniirdp8l4w/Worldmap_name.jtex?dl=0
https://www.dropbox.com/s/8hbo633pq44p0b3/TutorialWindow_menu_Window00.jtex?dl=0
https://www.dropbox.com/s/ph5tt8y0shvh7yl/TutorialWindow_menu_Window01.jtex?dl=0
https://www.dropbox.com/s/y4zftr3ykg683ri/TutorialWindow_menu_Window02.jtex?dl=0
https://www.dropbox.com/s/i7mk80xx4cikywg/TutorialWindow_menu_Window03.jtex?dl=0
https://www.dropbox.com/s/nsxao2349apbjd4/TutorialWindow_menu_Window04.jtex?dl=0
https://www.dropbox.com/s/uthqvg42kxd76oo/TutorialWindow_menu_Window05.jtex?dl=0

**Comment by matheuscardoso96** [comment]
Kukki>Tools>Compression>Nintendo>Decompress>General

**Comment by InochiPM** [comment]
> Kukkii>Tools>Compression>Nintendo>Decompress>General

Okay it worked and its decompressed, Now what do I do to compress the file? 
I tried to just save the decompressed jTEX but it crashed the game so what do i compress the files by? there are a lot of options in the Nintendo compress window.

**Comment by piratesephiroth** [comment]
most likely lz10 or lz11, I don't remember which of the two is it right now

**Comment by InochiPM** [comment]
> most likely lz10 or lz11, I don't remember which of the two is it right now

I tried lz10 and the game crashed lol
so ill try lz11 and hope it works.

**Comment by onepiecefreak3** [comment]
Looking at the header it's LZ11.
