### ISSUE TITLE
[Request] Automated releases

### ISSUE THREAD

**Issue by Colmines92** [IcySon55/Kuriimu#597]
Hello there, friends.
It's a fine work you all are doing there.

Is there any chance that you can continue to update the releases section with the latest compiled version of Kuriimu as it is released so people with very slow internet like me don't have to download and compile the whole project every time?

**Comment by IcySon55** [comment]
Every time?

Why don't you pull the project down using Git and then only pull down updates instead of the entire thing every time? That should drastically reduce the bandwidth needed.

Creating a proper release is quite a bit of work usually so I do it only when a bunch of new things are ready.

**Comment by onepiecefreak3** [comment]
This is done by Kuriimu2 at every commit to the dev branch. One can download those "Dev Builds" artifacts via the github actions of Kuriimu2.
If pushed to the master branch, it will create a new Release with a new version.
All builds are zipped in a ready-to-run package (assuming you have the correct .NET Core Framework version installed) with the best compression possible.

For more infos on this, please refer to the Kuriimu2 READ.ME, which also explains all these things and requirements for the application to be run.
