### ISSUE TITLE
Reporting bug - as requested by the software

### ISSUE THREAD

**Issue by futilityteam** [IcySon55/Kuriimu#598]
Issue: bug report
Console: DS
Format extension(s): .narc
Type: archive
Game Name: New Super Mario Bros.

First 8 bytes of the file(s):
<extension> - 4e415243feff0001 - NARC....

More details:
![image](https://user-images.githubusercontent.com/23103657/58385475-5ca9f980-7ff1-11e9-95ad-a63bc74c7af0.png)
<details>

Sample files (if possible):
https://ufile.io/bmtey579

**Comment by onepiecefreak3** [comment]
The newest dev build and Release 1.2.0 of Kuriimu2 can not reproduce the issue. It is possible that porting the plugin over, and testing it on more samples than before, this issue was fixed alongside the optimizations.
If there are more bug reports or requests, please refer to Kuriimu2.
