### ISSUE TITLE
[Plugin Request] Ar nosurge Plus: Ode to an Unborn Star (.g1t)

### ISSUE THREAD

**Issue by Megaflan** [IcySon55/Kuriimu#602]
Issue: I don't have time to look at this, but it should be quite simple, it's just a variant of the well known G1T image format.
Console: PSVITA
Format extension(s): .g1t
Type: image
Game Name: Ar nosurge Plus: Ode to an Unborn Star

First 8 bytes of the file(s):
0x4754314730363030 || GT1G0600

More details:
![imagen](https://user-images.githubusercontent.com/9650353/60073071-bf410300-971f-11e9-92e5-6eb3d51b01d9.png)

Sample files (if possible):
https://cdn.discordapp.com/attachments/376430646148726785/591717090654814218/battle.g1t

**Comment by Megaflan** [comment]
Changing the filename according this line of code works flawlessly.
`if (Path.GetFileName(filename).ToLower().Contains("vita")) platform = Platform.Vita;`

**Comment by lightfirst** [comment]
> 
> 
> Changing the filename according this line of code works flawlessly.
> `if (Path.GetFileName(filename).ToLower().Contains("vita")) platform = Platform.Vita;`

I am not sure how to change the filename. 
what does the filename look like?

**Comment by lightfirst** [comment]
ok, I make it work,  just add "vita" behind the file name
