### ISSUE TITLE
Edit with Kukkii or Kuriimu not working. 

### ISSUE THREAD

**Issue by TheMarioModder** [IcySon55/Kuriimu#607]
Issue: Bug Report

When right clicking any file in Karameru and pressing "Edit with Kukkii" or "Edit with Kuriimu" it will extract that file in the "temp" folder where Karameru is located and open up either Kukkii or Kuriimu, but the file wont show up.

**Comment by onepiecefreak3** [comment]
Files when opened with those options need to be reimported manually. Opening and editing them with the "Edit ..." option doesn't do any injection. This won't happen in Kuriimu2, the next iteration to this program.

**Comment by FireChat27** [comment]
I know it's late but I'm leaving the solution I found myself (cause I had the same issue).
Your kuriimu folder's path should **not** contain any space. That's as dumb as this.
