### ISSUE TITLE
Error when saving .fa file

### ISSUE THREAD

**Issue by ghost** [IcySon55/Kuriimu#613]
**Describe the bug**
Error when attempting to save a modified .FA file.

**To Reproduce**
1. Open .FA file in Karameru
2. Replace a .cfg.bin file
3. Save

**Expected behavior**
Expected to save the file

**Screenshots**
![](https://i.imgur.com/I9yqYa4.png)

**Desktop (please complete the following information):**
 - Version 1.0.14

**Additional context**
The game is Inazuma Eleven GO: Light

**Comment by onepiecefreak3** [comment]
ARC0 is one of the most tested format Kuriimu2 has to offer. It works for multiple currently active translation teams without a hitch.
It's safe to assume that this issue is not reproducable on Kuriimu2's newest dev build and Release 1.2.0, therefore it will be closed.
