### ISSUE TITLE
[plug-in request]Dragon Quest xi .pack files wont open

### ISSUE THREAD

**Issue by CommicKick69ing** [IcySon55/Kuriimu#618]
Issue: [Plugin Request]
Console: Nintendo 3DS Series
Format extension(s): .pack
Type: Text/Image
Game Name: dragon quest xi

More detail

Sample: [here](https://drive.google.com/open?id=1SN3GiWMNcYeapj9p2gRZ2cfukPpBu6Ss) are some script files

Example files a0001.pack / image
a_000.pack / text

**Comment by onepiecefreak3** [comment]
This bug is resolved in Kuriimu2.
