### ISSUE TITLE
Inazuma Eleven Japanese FA Files Error

### ISSUE THREAD

**Issue by Milozaki** [IcySon55/Kuriimu#620]
Game Name: Inazuma Eleven GO 2: Chrono Stone Neppuu & Raimei
Console: Nintendo 3DS
Format extension(s): FA
Type: archive

First 8 bytes of the file(s):
<extension> - [bytes in hex] - [bytes in ASCII]

More details:
<details>

Sample files (if possible):
<links>

DELETE ME: Do not attach files to the issue directly. Please use links to files hosted on other sites like Google Drive, Mega or similar.

**Comment by onepiecefreak3** [comment]
As one of the team leaders of a translation project, we worked together to fix all problems that the archive plugins for Level5 had.
I therefore assume this issue to be fixed.
