### ISSUE TITLE
EXSTETRA .RTEX file compression/decompression needed 

### ISSUE THREAD

**Issue by InochiPM** [IcySon55/Kuriimu#621]
Game Name: EXSTETRA
Console: 3DS
Format extension(s): .rtex
Type: [image files]

First 8 bytes of the file(s):
.rtex - 52 54 45 58 00 00 00 00 00 02 60 00 00 02 80 00 - RTEX�����`��€�

More details:
These are the files used for the textures of the game and curently there isnt a way to get into the files at all. 

Sample files (if possible):
https://app.box.com/s/5tvxksg11o8lxbbrp5a6w1m9ds5ggvek

**Comment by onepiecefreak3** [comment]
The file isn't compressed though. Please learn the difference between decompression and decoding.

**Comment by InochiPM** [comment]
> The file isn't compressed though. Please learn the difference between decompression and decoding.

Kukkii cannot open the files because of the lack of a plugin, and the huge issue that the textures have is a major swizzle. I understand now that their not compressed but the issue still remains that a plugin is required.

**Comment by onepiecefreak3** [comment]
That's true. I just wanted to point out that those terms are referencing completely different things. I also didn't mean to close the issue for a short period of time. I just hit the wrong button. That's also why it got reopened directly after that.

**Comment by onepiecefreak3** [comment]
This format was already requested by issue #458 and subsequently implemented in the newest dev build and upcoming Release 1.2.1 of Kuriimu2.
Issue closed.
