### ISSUE TITLE
error while opening arc files of MT Framework

### ISSUE THREAD

**Issue by o00O00o** [IcySon55/Kuriimu#623]
Issue: bug report
Console: Android (Mobile)
Format extension(s): .arc
Type: archive
Game Name: Gyakuten Saiban 5 / Phoenix Wright Ace Attorney: Dual Destinies

First 8 bytes of the file(s):
Gyakuten Saiban 5 :
00000000.arc - 41 52 43 43 07 00 15 00 - ARCC....
00000018.arc - 41 52 43 43 07 00 15 00 - ARCC....
00000100.arc - 41 52 43 43 07 00 15 00 - ARCC....

More details:
Tried to open the arc files extracted from main.obb with Karameru but failed.
This happens in the US and JP versions of the game. 

[arc files.zip](https://github.com/IcySon55/Kuriimu/files/3630532/arc.files.zip)

**Comment by o00O00o** [comment]
Could anybody give me some hints about opening this kinda .arc files, or some advice about which other forums I could ask for help in? Thanks in advance. Orz

**Comment by kongcaodm** [comment]
sorry for uploading the attached files directly, and here is an relevant offsite link. Thanks in advance. Orz
https://gbatemp.net/threads/error-while-opening-arc-files-of-mt-framework.549020/

**Comment by onepiecefreak3** [comment]
This bug cannot be reproduced on Release 1.2.0 and up of Kuriimu2.
ARCC is an encrypted version of Capcom's MT ARC format. Kuriimu2 can automatically detect, decrypt, and load those archives without a problem, as well as applying changes to them.
