### ISSUE TITLE
Inazuzma Chrono Stone FA Opening Error

### ISSUE THREAD

**Issue by plasmashadow** [IcySon55/Kuriimu#625]
Game Name: Inazuma Eleven GO 2: Chrono Stone Raimei (JPN)
Console: Nintendo 3DS
Format extension(s): FA
Type: archive

First 8 bytes of the file(s):
- [bytes in hex] - [bytes in ASCII]

More details:
trying to load ie5_a.fa (800mb) and ie5_b.fa (330mb) gives these errors 
![image](https://user-images.githubusercontent.com/56777153/67153468-a4ebf000-f2e1-11e9-8bcb-204e419146e8.png)

**Comment by onepiecefreak3** [comment]
This issue can not be reproduced on the newest dev build of Kuriimu2 and its Release 1.2.0.
Therefore this sissue gets closed.
