### ISSUE TITLE
RawJTEX don't open decompress .jtex file from CNPicross+ and PicrossE3

### ISSUE THREAD

**Issue by vulpes-vulpeos** [IcySon55/Kuriimu#629]
**Describe the bug**
When I try to open in Kukkii decompressed .jtex file from Club.Nintendo Picross+ and Picross E3 it gives an error System.Collections.Generic.KeyNotFoundException.
It works without issues with most .jtex file from Picross E8 and Picross E9, so I successfully ported english menu from E8 to E9.

**To Reproduce**
1. Open Kukkii.exe. Go Tools -> Nintendo -> Decompress -> General.
2. Select .jtex file from Club.Nintendo Picross+ (ex, BicroTutorialL_Pic01.jtex)
3. Save decompressed version.
4. Drag decompressed file (ex, BicroTutorialL_Pic01.decomp.jtex) into Kukkii window.
5. See error

**Expected behavior**
Expected behavior is to show image that is in that file.

**Screenshots**
https://imgur.com/a/IJCEsWC - screenshot of the error

**Desktop (please complete the following information):**
 - Version kuriimu: v1.0.14-e086e7f

**Additional context**
I tested Kukkii.exe on different files from Club.Nintendo Picross+ and Picross E3 and got this error. I know that they contain image, as there are same files in Picross E8 and E9 and they opened without error.

**Comment by onepiecefreak3** [comment]
Can you provide a sample file? Do not attach it directly to the issue, but upload it to a file hoster.

**Comment by vulpes-vulpeos** [comment]
https://www.dropbox.com/sh/93pafnogxumu9yw/AAAVl0CWa8EQiuXurDpfIrmia?dl=0 - here are some files. One is decompressed.

**Comment by IcySon55** [comment]
We temporarily solved this format with scripts because K1 can't handle unidentifiable formats properly. This issue will remain open for K2.
[JTEXC_ToPNG_ToJTEX.zip](https://github.com/IcySon55/Kuriimu/files/4703459/JTEXC_ToPNG_ToJTEX.zip)

**Comment by onepiecefreak3** [comment]
The newest dev build and upcoming Release 1.2.1 of Kuriimu2 supports uncompressed and compressed RawJTEX.
The plugin is manual, which means that the plugin has to be selected manually upon loading this file format. Select "Raw JTEX" under "plugin_nintendo" to load this file format.
the plugin can detect if this file format is compressed and automatically de-/compresses upon Load/Save respectively. No prior decompression needed as was the case in Kuriimu 1.
