### ISSUE TITLE
{Plugin Request} LAYTON’S MYSTERY JOURNEY: Katrielle and the Millionaires’ Conspiracy

### ISSUE THREAD

**Issue by Akuago220** [IcySon55/Kuriimu#631]
Game Name: LAYTON’S MYSTERY JOURNEY: Katrielle and the Millionaires’ Conspiracy
Console:  Nintendo Switch
Format extension(s): .xc .xi
Type: [image | model]

First 8 bytes of the file(s):
<extension> - [bytes in hex] - [bytes in ASCII]

More details:
Files are incompatible with current .xc and .xi plugins in suite.

Sample files (if possible):
https://www.mediafire.com/file/1emby0llhpykon6/Layton_Mystery_Journal_File_Samples.zip/file

**Comment by onepiecefreak3** [comment]
The IMGN format is properly supported in Kuriimu2's Release 1.2.0 and up.
The xc archives however still have bugs even in Kuriimu2's newest dev build. This will be researched further.

**Comment by onepiecefreak3** [comment]
From Switch onward, Level5 seemed to have introduced another compression scheme. Compression scheme 5, being ZLib, is used in the given samples to compress the name table.
In the newest dev build and upcoming Release 1.2.1 of Kuriimu2 this was fixed, so XPCK's from that platform are properly supported.
