### ISSUE TITLE
.XC Extract Error Karameru

### ISSUE THREAD

**Issue by supersonic29** [IcySon55/Kuriimu#635]
Game Name: Professor Layton vs Phoenix Wright
Console: 3DS
Format extension(s): .xc
Type: [archive]

When I extract the XC, the series of 71 .mtn2 files (animation files) in it will be correct for 0-11, under 1kb and broken for 12-69, and 70 will have an unusually large filesize and seemingly all the missing animations layered on one another.  Observed with any XC files I've opened with more than a few files.

Two tested examples with a large number of mtn2 files inside:
[Example XCs.zip](https://github.com/IcySon55/Kuriimu/files/3942791/Example.XCs.zip)

**Comment by caleb-mabry** [comment]
I've looked through the files that you've posted and don't see any issues with the outputs that they are giving. The XC files are giving the expected output. There may be a chance that what you are looking for can be found somewhere else within the archive.

**Comment by onepiecefreak3** [comment]
As already described (and also many times disproven with other members of the Level5 modding community) there currently is no issue with XPCK or subsequent archive formats by Level5 on 3DS. Kuriimu2 Release 1.2.0+ and newest dev builds cannot reproduce or find any problem with missing or corrupted files.
Everything you presented is all there is in the XPCK. As mentioned, this has been thoroughly proven.
Issue closed.
