### ISSUE TITLE
.TARC File error opening

### ISSUE THREAD

**Issue by InochiPM** [IcySon55/Kuriimu#636]
**Name of Game**
Tongari Boushi to Mahou no Machi 

**Describe the bug**
When trying to open the .tarc files from tongari boushi to mahou no machi it throws an error on all of the .tarc files except for one file. 

**To Reproduce**
1. drag and drop any tarc file into Karameru from Tongari Boushi. 
2. Error pops up. 

**Expected behavior**
a .tarc file is a package file, it is ever file in the game but since it wont show the internals of the game i cannot get into it. 

**Screenshots**
<img width="495" alt="Screen Shot 2019-12-17 at 12 40 15 AM" src="https://user-images.githubusercontent.com/13459080/71150857-81212980-2200-11ea-96d7-e33f67609b44.png">

**Desktop (please complete the following information):**
 - Version 1.0.14

**Sample Files**
https://app.box.com/s/8sngq0jjyse18u33jb32m8akgh4y9i16

**Comment by onepiecefreak3** [comment]
Please add a sample file for us to reproduce the behaviour, or name the game in question.

**Comment by InochiPM** [comment]
[item_common.zip](https://github.com/IcySon55/Kuriimu/files/3985767/item_common.zip)
Here is a sample file, one of them works and the other one doesn't open.

**Comment by InochiPM** [comment]
Hopefully this gets fixed soon, cause theres no other way to re-import the games files otherwise.

**Comment by caleb-mabry** [comment]
Could you please provide a few more files that work?

**Comment by InochiPM** [comment]
> Could you please provide a few more files that work?

I would if any of them opened, there was only one file that opened and it was the item_common.tarc let me get that file.
https://app.box.com/s/q8826ms7kh34vektfc0wy4qt7wa7bq7z

**Comment by caleb-mabry** [comment]
Are there more than just those 2 files? Any extra files will help.

**Comment by InochiPM** [comment]
> Are there more than just those 2 files? Any extra files will help.

Nope the only files that open are those and thats it. I checked every single file and they threw the same error except for one or two and im pretty sure its just those two item.tarcs

**Comment by onepiecefreak3** [comment]
Issue can not be reproduced in Kuriimu2's newest dev build. Therefore this issue will be closed.
