### ISSUE TITLE
Atelier Totori Image Files (.g1t)(0x45)

### ISSUE THREAD

**Issue by lightfirst** [IcySon55/Kuriimu#639]
Game Name: Atelier Totori The Alchemist of Arland plus 
Console: psv
Format extension(s): g1t
Type: [image]

First 8 bytes of the file(s):
  47543147303630302C00300020000000                       GT1G0600,

More details:
I try Latest commit ac2066a
G1T - G1T Texture Adapter
System.Exception: Unsupported image format 0x45.

some g1t working
Sample files :
http://www.mediafire.com/file/2xni7pbeammkn8g/Totori-g1t-psv.7z/file

**Comment by onepiecefreak3** [comment]
The format is supported in Kuriimu2 newest dev build and upcoming Release 1.2.1 and seems to work fine. If there are more bugs or feature requests regarding this format, please refer to Kuriimu2
