### ISSUE TITLE
Hayarigami 3 files

### ISSUE THREAD

**Issue by InochiPM** [IcySon55/Kuriimu#649]
Game Name: Hayarigami (流行り神３)
Console:  PSP
Format extension(s):  .DAT
Type: [archive]

First 8 bytes of the file(s):
START.DAT - 4E 49 53 50 41 43 4B 00 00 00 00 00 4D 00 00 00 - NISPACK�����M���
TITLE02.DAT - 4E 49 53 50 41 43 4B 00 00 00 00 00 03 00 00 00 - NISPACK��������

More details:
These files for Hayarigami 3 are a bit more difficult, as they are all .DAT archive files that house other files inside of them like .tx2 files. 

in TITLE02.DAT there are .txp and .did files. 

Sample files (if possible):
http://www.mediafire.com/folder/slge62z88kbup/HAYARIGAMI_3

**Comment by onepiecefreak3** [comment]
The newest dev build and upcoming Release 1.2.1 of Kuriimu2 supports this format.
The plugin can automatically detect and load the file format.
