### ISSUE TITLE
Dragon quest xi .pack files not opening

### ISSUE THREAD

**Issue by Gamwize** [IcySon55/Kuriimu#657]
When I try to open dragon quest xi .pack files I get a message that there is no plugin installed that can open this file while there is an option for Dragon quest xi .pack files.

**To Reproduce**
Open any of the Dragon quest xi .pack files in karameru.

**Expected behavior**
I expected to see an archive of all the files that are stored in the .pack files.

I'm on version 1.0.14-e086e7f

**Additional context**
I'm not experienced with github so I don't know if I'm doing this whole issue thing wrong. please excuse me if I do.
I'm also using a decrypted version of dragon quest xi.

**Comment by onepiecefreak3** [comment]
Many bugs regarding PACK files in Dragon Quest XI are resolved in Kuriimu2.
You might not be able to open PACA files (they also have the .pack extension), and will get an appropriate error message that said PACK file is not supported.

**Comment by blashy101** [comment]
> Many bugs regarding PACK files in Dragon Quest XI are resolved in Kuriimu2. You might not be able to open PACA files (they also have the .pack extension), and will get an appropriate error message that said PACK file is not supported.

The PACA header PACK files are compressed with Backwards LZ77, Kuriimu2 can do this process.

**Comment by onepiecefreak3** [comment]
> > Many bugs regarding PACK files in Dragon Quest XI are resolved in Kuriimu2. You might not be able to open PACA files (they also have the .pack extension), and will get an appropriate error message that said PACK file is not supported.
> 
> The PACA header PACK files are compressed with Backwards LZ77, Kuriimu2 can do this process.

I know it can, I'm the developer of everything in it ^^

I didn't realize though, that they were compressed? Because in my samples they aren't. So maybe those are more recent version of the file? This issue IS 5 years old after all.
