### ISSUE TITLE
Arc files in Skyward Sword (NTSC-U 1.0) rom not showing files in Karameru

### ISSUE THREAD

**Issue by APerson13** [IcySon55/Kuriimu#658]
Game Name: The Legend of Zelda: Skyward Sword
Console: Wii
Format extension(s): arc
Type: archive

First 8 bytes of the file(s):
arc - 55 AA 38 2D 00 00 00 20 - Uª8-��� 

More details: 
I also tried unpacking with both Arcman and Arctool: Arcman offset all the files inside and Arctool made the nbst files inside either too long or too short, rendering them unreadable.

Attached file is located at root\DATA\files\US\Object\en_US in the rom.

Sample files (if possible):
https://drive.google.com/open?id=1yNwhqzUni_ICcT8M8zFefrixoaFzWmxi

**Comment by onepiecefreak3** [comment]
The archive is fully openable and savable with Kuriimu2. Please upgrade to Kuriimu2.
This issue will be closed.
