### ISSUE TITLE
[Plugin request] PBI files

### ISSUE THREAD

**Issue by AlePlumber** [IcySon55/Kuriimu#663]
Game Name: Inazuma Eleven Go: Galaxy
Console: Nintendo 3ds
Format extension(s):  .pbi
Type: archive

First 8 bytes of the file(s):
58 50 56 49

More details:
We want to edit these files to change the length and width of the xi files in the game, beacause you can do a larger xi file but the game will only use the default width and lenght

Sample files (if possible):

https://drive.google.com/file/d/1cH_vngArkU5LzNJuNugOpxItpGorC37z/view?usp=sharing

**Comment by onepiecefreak3** [comment]
Since PBI's are no archive and are also not a kind of format Kuriimu will support in the near future, I will close this issue. Further discussion around alternatives or what wants to be achieved here will happen on Discord. There is currently no public tool to edit PBI, PVB or RES.bin
