### ISSUE TITLE
[Issue] Opening a JTEX with Kukkii

### ISSUE THREAD

**Issue by ouone** [IcySon55/Kuriimu#665]
**Describe the bug**
When opening a decompressed JTEX file through Kukkii running on MacOS Mojave via Wine Stable, an error window pops up, displaying the error message - 'System.IndexOutOfRangeException: Index was outside the bounds of the array'. These files are not able to be exported, despite being viewable from the main application.

**To Reproduce**
1. Download and extract the latest version of Kuriimu (v1.0.14-e086e7f) on MacOS Mojave v10.14.6
2. Open Kukkii with Wine Stable Version 5.0
3. Decrypt the .jtex file through Tools > Compression > Nintendo > Decompress > General 
4. Open the decrypted .jtex file through either the 'Open' icon, or File > Open
5. See error

**Expected behavior**
It is expected for the decompressed JTEX file to open, and display the file's properties to the right of the window under 'Properties', as well as a viewfinder, displaying a smaller version of what the user is seeing on the main window.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/25887064/85693679-cc6d4500-b719-11ea-8779-82b899a974ea.png)
![Screen Shot 2020-06-26 at 12 18 35 am](https://user-images.githubusercontent.com/25887064/85737343-a60fcf80-b742-11ea-9806-5bef296aaa7d.png)

**Desktop (please complete the following information):**
 - Kuriimu Version v1.0.14-e086e7f
- Wine Stable Version 5.0
- MacOS Mojave Version 10.14.6

**Additional context**
This issue occurs with some of the JTEX files extracted from the romfs of 'Nikki's Travel Plaza/Quiz'.
Here are 3 examples of these JTEX files - https://mega.nz/folder/2Y5UlCxA#kExX3aNSBYudJDPI--LVmQ

**Comment by onepiecefreak3** [comment]
This issue does not occur on Kuriimu2 anymore, since the property grid does exist anymore.
It was replaced by different UI design.
Since Kuriimu1 is discontinued and succeeded by Kuriimu2, this issue is therefore resolved.
