### ISSUE TITLE
CTXB saving error

### ISSUE THREAD

**Issue by JokerDKha** [IcySon55/Kuriimu#666]
Describe the bug
When saving CTXB file through Kukkii running on window an error window pops up, displaying the error message - 'CTXB - CTR TeXture Box Adapter'

To Reproduce
Download and extract the latest version of Kuriimu (v1.0.14-e086e7f) on Window 10
Open Kukkii 
Export PNG to Window 10
Edit PNG with Photoshop
Import PNG again to Kukkii
Save and Save as File CTXB
See error

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/56380626/85929877-65e75300-b8e2-11ea-98bb-310a960ced0e.png)

**Desktop (please complete the following information):**
 - Window 10

**Additional context**

[ctxb-file.zip](https://github.com/IcySon55/Kuriimu/files/4841089/ctxb-file.zip)

**Comment by onepiecefreak3** [comment]
This error is not reproducable on Kuriimu2. Since Kuriimu1 is discontinued and succeeded by Kuriimu2, this issue is considered resolved.
