### ISSUE TITLE
Blue Reflection [PCSG00987] Texture Repack

### ISSUE THREAD

**Issue by kevin168** [IcySon55/Kuriimu#669]
Game Name: Blue Reflection [PCSG00987]
Console: PSV (PS Vita)
Format extension(s): g1t
Type: image / texture

First 8 bytes of the file(s):
<g1t> - [4754314730363030] - [GT1G0600]

More details:
need support to correctly repack g1t files. file could be repacked with kukkii, but character not loaded correctly.
tried also without changing any texture, just simply open and save using kukkii.
but there is no texture being shown. picture attached in sample files.
maybe texture need to be swizzled back before repacking?

Sample files :
https://mega.nz/file/wA1nxDhB#GYbn9-cEWstn0pZys_z4QgzO1Oyiup5yCI6cr23nsxE

**Comment by Megaflan** [comment]
Try to rename the extension to vita.g1t

**Comment by kevin168** [comment]
Yes, i've done that before asking for help.
Kukkii won't open the file without any "vita" filename.

Simple unpack and repack, without any modification, produce much different in g1t file.

Check on several bytes using hexeditor, seems that texture file being modified or unswizzled after repack.

Don't know much about this one, but i can see that every image size changed.

Ex:
Original = 0xA0
Repack = 0x80

**Comment by kevin168** [comment]
Dig up some more into this, 
i've been trying to manually replacing some texture using several sw available on the net.

1. Replace one texture (clothes texture) with another using import *.png format.
( Confirmed that kukkii can replace and swizzled image back into *.g1t )
checked *.dds files inside "repacked" *.g1t manually 

Problem with Kukkii : 
- "Replaced" texture (*.dds) is missing 1 mipmap layer,
- Repacked *.g1t got some broken value, can't be load into PSV
 i try to unpack "repacked" *.g1t using "gust_g1t" and get this error : 

Assertion failed: expected_size >=  texture_size + (unint32_t)size_of(g1t_tex_header)

ps. i know this isn't gust repo, but this error info is better than nothing. 

2. I extract back "modded" *.dds from *.g1t using switch_toolbox, then check it manually on the file comparing with the original one.

i've conclusion :
- 1st and 2nd mipmap layer actually have different swizzle pattern (kukkii only re-create 1 mipmap layer)
- 1st layer swizzled by kukkii is correctly same as the original swizzled image.

then i try to manually create dds using directx tex tool, i can't find any other sw that have ability to generate custom mipmaps.
copied 1st swizzled layer ( 512x512 ) into 2nd mipmap layer ( 256x256 )


repack it back using gust_g1t, but the image pixel is swizzled incorrectly.
![IMG_20200909_005130](https://user-images.githubusercontent.com/2064547/92562712-9bc09480-f2a0-11ea-99fc-e144c753f5da.jpg)


i also try using only 1 layer, but only show full black image on the character.
![IMG_20200905_002623](https://user-images.githubusercontent.com/2064547/92562684-9105ff80-f2a0-11ea-92f3-b569e2585c93.jpg)

**Comment by onepiecefreak3** [comment]
This bug may have been caused by ignoring the given mipmaps. While an entry denoted, for example, two mipmaps, it was only given one in total. I don't know if this completely stopped loading the textures, or if only the mipmaps are not loaded. It's possible that the game is actually smart enough to load the original textures normally, which could mean that the textures pop up the closer you get to the object receiving those textures.

Only an assumption and it obviously doesn't have to. Properly handling mip maps is now implemented in the newest dev build and upcoming Release 1.2.1 of Kuriimu2. For future bug reports and feature requests regarding the format, please refer to Kuriimu2.
