### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ArisuTheLoli** [IcySon55/Kuriimu#670]
![8](https://user-images.githubusercontent.com/73005444/96324941-9fc09e80-1024-11eb-9496-8ccca99beb0f.png)
Hello I would like to translate a game but every time I try to open a text or an PNG files with Kuriimu or Kukkii, it shows me this error and I would like to have if it was possible to help me! This is the first time I use Github! Thanks in advance to the people who will help me!

Oh yes, The name of the game is : Beyblade Burst God

**Comment by onepiecefreak3** [comment]
Issue was opened on Kuriimu2's github.
