### ISSUE TITLE
When I compress with Revlz77, there seems to be a problem here

### ISSUE THREAD

**Issue by lidawei97688** [IcySon55/Kuriimu#672]
https://github.com/IcySon55/Kuriimu/blob/3f05ffc993e0908929e92373c455acb633b8f28d/src/Kontract/Compression/RevLZ77.cs#L195

**Comment by christophSiebert** [comment]
This issue is known and will not be fixed, since Kuriimu is deprecated. Please use Kuriimu2 to not have this problem anymore.

**Comment by onepiecefreak3** [comment]
Since Kuriimu is deprecated, this will not be patched. Please use Kuriimu2 to not have this problem anymore.
