### ISSUE TITLE
Karameru enhancments

### ISSUE THREAD

**Issue by IcySon55** [IcySon55/Kuriimu#84]
1. Directory extraction
2. Complete archive extraction directories and all
3. Complete archive import with options (add, replace only, delete not in source)
4. Directory import with the same options. Maybe I make it all just one function and UI and the user performs the directory extract from the currently invisible root node (show the node as the filename perhaps)

**Comment by onepiecefreak3** [comment]
Directory extraction works now.
Only point 3 and 4 are left.

**Comment by onepiecefreak3** [comment]
Directory import now possible.

**Comment by IcySon55** [comment]
All important functions have been completed to my liking.
